### PR TITLE
Bug 2096207: Add missing glibc-langpack-en for specified locale

### PR DESCRIPTION
**Pull request by cobexer**

### CODE REVIEW

**Comment by cobexer** [comment]
See issues https://github.com/openshift/jenkins/issues/960 and https://github.com/openshift/jenkins/issues/1224

@akram maybe you can have a look?

**Comment by akram** [comment]
/retitle Bug 2096207: Add missing glibc-langpack-en for specified locale

**Comment by sll552** [comment]
This fix would be very welcome, but it seems that it didn't get merged in any release branch, and therefore is not available in an actual container. Is there any reason for this? @akram

**Pull request merged**
