### PR TITLE
Upgrade to job-dsl 1.70

### PR DESCRIPTION
**Pull request by svenstaro**
I think 1.70 has some [excellent changes](https://github.com/jenkinsci/job-dsl-plugin/wiki#release-notes). Please consider this.

### CODE REVIEW

**Comment by gabemontero** [comment]
thanks @svenstaro ... agree the updates seem ok

assuming this passes our regression testing the centos image on dockerhub should be upgraded later today; for the rhel image, this will be part of the 4.0 image shipped most likely at the end 2018

**Comment by svenstaro** [comment]
@gabemontero can you check out the failure? I don't get it. I think it's just a timeout of some kind.

**Comment by gabemontero** [comment]
I also have tests running again in https://github.com/openshift/jenkins/pull/708 ... a PR that has already passed once ... we'll see what happens now against a later openshift/origin

**Comment by gabemontero** [comment]
now we are hitting ci hiccups

will see if there is a known env issue ...then retry in a bit

**Pull request merged**
