### PR TITLE
goto 0.9.1 of openshift-client

### PR DESCRIPTION
**Pull request by gabemontero**
the plugin update includes the change for https://github.com/openshift/jenkins-client-plugin/issues/5

@csrwng @jupierce @bparees fyi

### CODE REVIEW

**Comment by bparees** [comment]
lgtm

**Comment by gabemontero** [comment]
Looks like there have been a series of plugin updates up in jenkins land, ultimately leading to not being able to load the github plugin.  Our friend the scm api plugin seems to be at the root.  Independent of the openshift client plugin change:

```
SEVERE: Failed Loading plugin GitHub plugin v1.26.0 (github)
java.io.IOException: GitHub plugin v1.26.0 failed to load.
 - SCM API Plugin v2.0.2 is older than required. To fix, install v2.0.3 or later.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:621)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:516)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$7.runTask(Jenkins.java:1085)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Feb 13, 2017 8:58:08 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin GitHub Branch Source Plugin v2.0.2 (github-branch-source)
java.io.IOException: GitHub Branch Source Plugin v2.0.2 failed to load.
 - GitHub plugin v1.26.0 failed to load. Fix this plugin first.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:621)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:516)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$7.runTask(Jenkins.java:1085)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Feb 13, 2017 8:58:08 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Pipeline REST API for Blue Ocean v1.0.0-b23 (blueocean-pipeline-api-impl)
java.io.IOException: Pipeline REST API for Blue Ocean v1.0.0-b23 failed to load.
 - GitHub Branch Source Plugin v2.0.1 failed to load. Fix this plugin first.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:621)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:516)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$7.runTask(Jenkins.java:1085)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Feb 13, 2017 8:58:08 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Events API for Blue Ocean v1.0.0-b23 (blueocean-events)
java.io.IOException: Events API for Blue Ocean v1.0.0-b23 failed to load.
 - Pipeline REST API for Blue Ocean v1.0.0-b23 failed to load. Fix this plugin first.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:621)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:516)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$7.runTask(Jenkins.java:1085)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Feb 13, 2017 8:58:08 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Dashboard for Blue Ocean v1.0.0-b23 (blueocean-dashboard)
java.io.IOException: Dashboard for Blue Ocean v1.0.0-b23 failed to load.
 - Events API for Blue Ocean v1.0.0-b23 failed to load. Fix this plugin first.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:621)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:516)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$7.runTask(Jenkins.java:1085)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Feb 13, 2017 8:58:08 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Personalization for Blue Ocean v1.0.0-b23 (blueocean-personalization)
java.io.IOException: Personalization for Blue Ocean v1.0.0-b23 failed to load.
 - Events API for Blue Ocean v1.0.0-b23 failed to load. Fix this plugin first.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:621)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:516)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$7.runTask(Jenkins.java:1085)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Feb 13, 2017 8:58:08 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin BlueOcean beta v1.0.0-b12 (blueocean)
java.io.IOException: BlueOcean beta v1.0.0-b12 failed to load.
 - Pipeline REST API for Blue Ocean v1.0.0-b12 failed to load. Fix this plugin first.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:621)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:516)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$7.runTask(Jenkins.java:1085)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

@bparees - do you want me to start changing the other plugin versions with this pull, or use a separate one?

**Comment by gabemontero** [comment]
@bparees  - Interestingly, the test log indicated it was an issue with the centos image, but when I run `make test` locally off of my branch it works.

Any idea if it was really the rhel image that failed? Or could something like this be intermittent or build env dependent?

Gotta head home, but I'll try spinning up a ami and try testing rhel images as well.

**Comment by bparees** [comment]
> do you want me to start changing the other plugin versions with this pull, or use a separate one?

you can change them in this one.

> Any idea if it was really the rhel image that failed? Or could something like this be intermittent or build env dependent?

shouldn't be, we're not installing any blueocean plugins in the rhel image.  I'm not sure why your local test would have succeeded though.

whenever i've hit this before it's been consistent in both the PR tester and my local machine.

**Comment by bparees** [comment]
is it possible your local build used a cache from when you built it previously w/ this change, perhaps before the other plugin updates came in?

**Comment by gabemontero** [comment]
On Mon, Feb 13, 2017 at 6:47 PM Ben Parees <notifications@github.com> wrote:

> is it possible your local build used a cache from when you built it
> previously w/ this change, perhaps before the other plugin updates came in?
>
Entirely possible.  I'll clear out the cache and see what happens.

**Pull request merged**
