### PR TITLE
bump sync plugin to 0.1.4

### PR DESCRIPTION
**Pull request by jimmidyson**
Need to wait until synced to Jenkins update centre

### CODE REVIEW

**Comment by jimmidyson** [comment]
0.1.2 is now available from update sites. Ping @tdawson @bparees.

**Comment by jimmidyson** [comment]
Hold off on merging - found another bug to fix quickly...

**Comment by bparees** [comment]
holding.

**Comment by jimmidyson** [comment]
Ready to merge once 0.1.3 is synced to jenkins update centre (not sure of schedule - have to check for when https://updates.jenkins-ci.org/download/plugins/openshift-sync/0.1.3/openshift-sync.hpi). Off out for a bit but back online later so will ping you if you haven't managed to merge this by then - thanks!

**Comment by jimmidyson** [comment]
[test]

**Comment by jimmidyson** [comment]
Weird errors:

```
sh: cannot set terminal process group (-1): Inappropriate ioctl for device
sh: no job control in this shell
sh: cannot set terminal process group (-1): Inappropriate ioctl for device
sh: no job control in this shell
+ sudo env PATH=/data/src/github.com/openshift/source-to-image/_output/local/go/bin:/data/src/github.com/openshift/source-to-image/_output/local/bin/linux/amd64:/data/src/github.com/openshift/origin/_output/etcd/bin:/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64:/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin SKIP_SQUASH=1 make test TARGET=centos7
The command '/bin/sh -c curl https://pkg.jenkins.io/redhat-stable/jenkins.repo -o /etc/yum.repos.d/jenkins.repo &&     rpm --import https://pkg.jenkins.io/redhat-stable/jenkins-ci.org.key &&     yum install -y centos-release-scl-rh &&     INSTALL_PKGS="rsync gettext git tar zip unzip java-1.8.0-openjdk java-1.8.0-openjdk-devel jenkins-1.651.3-1.1 nss_wrapper" &&     yum -y --setopt=tsflags=nodocs install $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum clean all  &&     localedef -f UTF-8 -i en_US en_US.UTF-8 &&     curl -L https://github.com/openshift/origin/releases/download/v1.3.0/openshift-origin-client-tools-v1.3.0-3ab7af3d097b57f933eccef684a714f2368804e7-linux-64bit.tar.gz |     tar -zx &&     mv openshift*/oc /usr/local/bin &&     rm -rf openshift-origin-client-tools-*' returned a non-zero code: 2
```

**Comment by bparees** [comment]
the ioctl errors don't mean anything, the real problem is this:
```
The command '/bin/sh -c curl https://pkg.jenkins.io/redhat-stable/jenkins.repo -o /etc/yum.repos.d/jenkins.repo &&     rpm --import https://pkg.jenkins.io/redhat-stable/jenkins-ci.org.key &&     yum install -y centos-release-scl-rh &&     INSTALL_PKGS="rsync gettext git tar zip unzip java-1.8.0-openjdk java-1.8.0-openjdk-devel jenkins-1.651.3-1.1 nss_wrapper" &&     yum -y --setopt=tsflags=nodocs install $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum clean all  &&     localedef -f UTF-8 -i en_US en_US.UTF-8 &&     curl -L https://github.com/openshift/origin/releases/download/v1.3.0/openshift-origin-client-tools-v1.3.0-3ab7af3d097b57f933eccef684a714f2368804e7-linux-64bit.tar.gz |     tar -zx &&     mv openshift*/oc /usr/local/bin &&     rm -rf openshift-origin-client-tools-*' returned a non-zero code: 2
```

which probably just means there was a network glitch grabbing an rpm.

[test]

**Comment by jimmidyson** [comment]
Few more fixes in 0.1.4 - needs to be packaged by @tdawson if you can please, before we merge this I think.

**Comment by bparees** [comment]
Why before merging? If I merge it now the centos image will be fixed. 
Troy will have to package the new plugin and build a new RHEL image as always.

**Comment by jimmidyson** [comment]
The build logs showed installing the previous version rpm so I assumed you'd want to wait until rpm packaged & used in this build for testing. But that's a bit of a chicken & egg situation I guess. Merge away if you're happy.

**Comment by bparees** [comment]
Yeah that's just the internal RHEL image being built, largely moot at this point.

**Comment by tdawson** [comment]
rpms built:
  jenkins-plugin-openshift-pipeline-1.0.37-1.el7
  jenkins-plugin-openshift-sync-0.1.4-1.el7
puddles created and synced to mirrors
images created and pushed to registry.ops:
  openshift3/jenkins-1-rhel7:1.651.2-41
  openshift3/jenkins-2-rhel7:2.19-8

**Pull request merged**
