### PR TITLE
move to 1.0.11 of openshift pipeline plugin

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees PTAL

This version has 2 bugzilla fixes from QE testing of my 2 plugin cards this sprint, as well as an upstream ask around exiting failed builds more expediently, followed by an NPE fix that @sspeiche found.

### CODE REVIEW

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
@gabemontero you'll have to rebase so you can pick up this change:
https://github.com/openshift/jenkins/pull/98

and then the test should pass.  but we probably want to wait to merge this until the rhel rpm is published so the rebuild/push picks up everything in one shot.

**Comment by gabemontero** [comment]
@bparees just rebased off of https://github.com/openshift/jenkins/pull/98 's merging into master.

And yes, agreed on merge timing re: rhel ... that's why I pinged Troy while this was still in progress vs. waiting until this merged.

**Comment by bparees** [comment]
sounds like the rpm is created.

**Pull request merged**
