### PR TITLE
[release-4.9] OCPBUGS-3173: Add glibc-langpack-en package in agent-base image

### PR DESCRIPTION
**Pull request by divyansh42**
Signed-off-by: divyansh42 <diagrawa@redhat.com>

### CODE REVIEW

**Comment by divyansh42** [comment]
/assign @mbharatk 
for lgtm
/assign @coreydaley 
for backport-risk-assessed and approved

**Comment by divyansh42** [comment]
/assign @jitendar-singh 
for cherry-pick-approved

**Comment by coreydaley** [comment]
/assign @akram 
for approve (I don't have approve rights before 4.10)

**Pull request merged**
