### PR TITLE
match route timeout template updates in origin

### PR DESCRIPTION
**Pull request by gabemontero**
@openshift/sig-developer-experience fyi

### CODE REVIEW

**Comment by bparees** [comment]
lgtm

**Comment by gabemontero** [comment]
@bparees can you put a `/` in front of your lgtm?  thanks

**Comment by bparees** [comment]
@gabemontero fyi you can workaround that limit by just putting the label on the PR directly, for future reference.

**Comment by gabemontero** [comment]
ah ok thanks @bparees ... good to know if i have a late night PR to merge :-)

**Pull request merged**
