### PR TITLE
Update Jenkins patch version to 2.46.3

### PR DESCRIPTION
**Pull request by jtescher**

### CODE REVIEW

**Comment by bparees** [comment]
[test] (will probably fail until we get https://github.com/openshift/jenkins/pull/299 landed)

@smunilla @tdawson can we start the process of packing this new jenkins LTS for rhel?

**Comment by tdawson** [comment]
I thought we were doing jenkins updates once a quarter, or when there are security updates (which usually is once a quarter).
Is there a bugfix in this one that is causing us to update it early this time?

**Comment by tdawson** [comment]
New package built (jenkins-2.46.3-1.el7) it has the rhaos-3.6 tag.  I will leave the puddle and release stuff up to @smunilla.

**Comment by bparees** [comment]
> Is there a bugfix in this one that is causing us to update it early this time?

i haven't actually looked at what is in the new LTS, was just trying to align with it since it came out and we occasionally get beat up for not being more current.  If creating new RPMs for each LTS is too burdensome we can go back to trying to just pick up the LTS once per OCP release.

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
@jtescher can you rebase this against master?  I think your branch doesn't have the fix to the plugin installer script which is why the CI test is failing to install some plugins.

**Comment by jtescher** [comment]
@bparees rebased 👍

**Comment by bparees** [comment]
[test]

Ben Parees | OpenShift

**Comment by bparees** [comment]
@jtescher thanks, will merge this on monday when our queue re-opens.

**Comment by bparees** [comment]
[merge]

**Pull request merged**
