### PR TITLE
use a tag for slave image config and drop .net slave image config

### PR DESCRIPTION
**Pull request by bparees**
backport of https://github.com/openshift/jenkins/pull/431

### CODE REVIEW

**Comment by bparees** [comment]
@jim-minter ptal

**Comment by jim-minter** [comment]
lgtm

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
@stevekuznetsov @jupierce 

```
[workspace] $ /bin/bash /tmp/jenkins7239328668415508161.sh
+ approve.sh jenkins openshift-3.7 none
[ERROR] No approval criteria are configured for 'openshift-3.7' branch of 'jenkins' repo.
```

can we get some approval criteria for our branches in this repo?

**Pull request merged**
