### PR TITLE
bump to v1.0.14 of openshift pipeline plugin

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees or @csrwng (assuming you have merge power for the jenkins repo as well) - pls hit the merge button when you get the chance.  Pulling in the the plugin version for the DSL additions for my card this sprint.

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by csrwng** [comment]
@gabemontero I don't have merge power in this repo (nor for any other repo that I know of). But just fyi... in other repos under the radar of the openshift-bot you can just comment [merge] and that's enough. All you need is the ability to comment.

**Comment by gabemontero** [comment]
Ah ... I thought you had to have merge power in order for that comment to
take effect.  Or perhaps what you are saying is that that is only for the
origin repo (and with say source-to-image or jenkins
we are under the honor system to get peer review wrt use of that comment)?

In any event, I'll wait a bit and see if @bparees checks email (again)
during his PTO ;-)

**Comment by csrwng** [comment]
Yes, we are under the honor system :-)

**Comment by gabemontero** [comment]
[merge]

**Comment by gabemontero** [comment]
Yeah @csrwng , my adding the [merge] tag did not initiate a merge.  Believe I have to either wait for @bparees , or perhaps @mfojtik has merge powers for the jenkins repo ?

**Comment by mfojtik** [comment]
Done :)

**Comment by gabemontero** [comment]
thank your sir ;-)

**Comment by bparees** [comment]
1) this repo isn't monitored by the bot (none of our image repos are. They
are monitored by a github PR tester job to test the pull with a test tag,
but it won't merge stuff)
2) for repos the bot does monitor, you still need merge tag permissions,
the bot won't merge for just anyone who comments.  @csrwng you have merge
tag permission on origin (permission to tag for merging, which is different
from permission to outright merge a PR yourself)

**Comment by csrwng** [comment]
> you have merge
> tag permission on origin (permission to tag for merging, which is different
> from permission to outright merge a PR yourself)

ha good to know, I thought you only needed permission to create the comment

**Pull request merged**
