### PR TITLE
Bug 1950384: Revert "Update jenkins to 2.277.2"

### PR DESCRIPTION
**Pull request by jkhelil**
This reverts commit 50112effa52caec214ca232bf6670be30245a055.

### CODE REVIEW

**Comment by jkhelil** [comment]
/retitle Bug 1950384: Revert "Update jenkins to 2.277.2"

**Comment by adambkaplan** [comment]
/override e2e-aws-jenkins

The Jenkins suite currently uses the quay.io/redhat-developer/nfs-server image, which has not been added to the OCP test suite mirror. Either an exception needs to be granted, or the image needs to be mirrored to the ocp community images repo. See https://github.com/openshift/origin/blob/master/test/extended/util/image/README.md

**Pull request merged**
