### PR TITLE
add pipeline-graph-analysis:1.2

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero this seems to build + start up ok for me, can you pull it down and build it yourself and double check though?

**Comment by bparees** [comment]
```
$ docker run -P 3bec1869650b
Generating kubernetes-plugin configuration (/opt/openshift/configuration/config.xml.tpl) ...
Copying Jenkins configuration to /var/lib/jenkins ...
Copying 48 Jenkins plugins to /var/lib/jenkins ...
Creating initial Jenkins 'admin' user ...
Running from: /usr/lib/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
Nov 03, 2016 7:56:03 PM winstone.Logger logInternal
INFO: Beginning extraction from war file
Nov 03, 2016 7:56:04 PM org.eclipse.jetty.util.log.JavaUtilLog info
INFO: jetty-winstone-2.9
Nov 03, 2016 7:56:06 PM org.eclipse.jetty.util.log.JavaUtilLog info
INFO: NO JSP Support for , did not find org.apache.jasper.servlet.JspServlet
Jenkins home directory: /var/lib/jenkins found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
Nov 03, 2016 7:56:06 PM org.eclipse.jetty.util.log.JavaUtilLog info
INFO: Started SelectChannelConnector@0.0.0.0:8080
Nov 03, 2016 7:56:06 PM winstone.Logger logInternal
INFO: Winstone Servlet Engine v2.0 running: controlPort=disabled
Nov 03, 2016 7:56:07 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started initialization
Nov 03, 2016 7:56:27 PM jenkins.InitReactorRunner$1 onAttained
INFO: Listed all plugins
Nov 03, 2016 7:56:27 PM jenkins.InitReactorRunner$1 onAttained
INFO: Prepared all plugins
Nov 03, 2016 7:56:27 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started all plugins
Nov 03, 2016 7:56:35 PM hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1 error
WARNING: Failed to instantiate optional component org.jenkinsci.plugins.workflow.steps.scm.GitStep$DescriptorImpl; skipping
Nov 03, 2016 7:56:35 PM hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1 error
WARNING: Failed to instantiate optional component org.csanchez.jenkins.plugins.kubernetes.ServiceAccountCredential$DescriptorImpl; skipping
Nov 03, 2016 7:56:36 PM io.fabric8.kubernetes.client.Config tryServiceAccount
WARNING: Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
Nov 03, 2016 7:56:37 PM io.fabric8.jenkins.openshiftsync.GlobalPluginConfiguration configChange
SEVERE: Failed to configure OpenShift Jenkins Sync Plugin: java.net.UnknownHostException: kubernetes.default.svc: Name or service not known
Nov 03, 2016 7:56:37 PM jenkins.InitReactorRunner$1 onAttained
INFO: Augmented all extensions
Nov 03, 2016 7:56:38 PM jenkins.InitReactorRunner$1 onAttained
INFO: Loaded all jobs
Nov 03, 2016 7:56:38 PM hudson.model.AsyncPeriodicWork$1 run
INFO: Started Download metadata
Nov 03, 2016 7:56:39 PM org.jenkinsci.main.modules.sshd.SSHD start
INFO: Started SSHD at port 36873
Nov 03, 2016 7:56:39 PM jenkins.InitReactorRunner$1 onAttained
INFO: Completed initialization
Nov 03, 2016 7:56:39 PM org.springframework.context.support.AbstractApplicationContext prepareRefresh
INFO: Refreshing org.springframework.web.context.support.StaticWebApplicationContext@11d737da: display name [Root WebApplicationContext]; startup date [Thu Nov 03 19:56:39 UTC 2016]; root of context hierarchy
Nov 03, 2016 7:56:39 PM org.springframework.context.support.AbstractApplicationContext obtainFreshBeanFactory
INFO: Bean factory for application context [org.springframework.web.context.support.StaticWebApplicationContext@11d737da]: org.springframework.beans.factory.support.DefaultListableBeanFactory@621ff456
Nov 03, 2016 7:56:39 PM org.springframework.beans.factory.support.DefaultListableBeanFactory preInstantiateSingletons
INFO: Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@621ff456: defining beans [authenticationManager]; root of factory hierarchy
Nov 03, 2016 7:56:39 PM org.springframework.context.support.AbstractApplicationContext prepareRefresh
INFO: Refreshing org.springframework.web.context.support.StaticWebApplicationContext@348b3ba8: display name [Root WebApplicationContext]; startup date [Thu Nov 03 19:56:39 UTC 2016]; root of context hierarchy
Nov 03, 2016 7:56:39 PM org.springframework.context.support.AbstractApplicationContext obtainFreshBeanFactory
INFO: Bean factory for application context [org.springframework.web.context.support.StaticWebApplicationContext@348b3ba8]: org.springframework.beans.factory.support.DefaultListableBeanFactory@4a9f8888
Nov 03, 2016 7:56:39 PM org.springframework.beans.factory.support.DefaultListableBeanFactory preInstantiateSingletons
INFO: Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@4a9f8888: defining beans [filter,legacy]; root of factory hierarchy
Nov 03, 2016 7:56:39 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started initialization
Nov 03, 2016 7:56:39 PM jenkins.InitReactorRunner$1 onAttained
INFO: Listed all plugins
Nov 03, 2016 7:56:39 PM jenkins.InitReactorRunner$1 onAttained
INFO: Prepared all plugins
Nov 03, 2016 7:56:39 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started all plugins
Nov 03, 2016 7:56:39 PM jenkins.InitReactorRunner$1 onAttained
INFO: Augmented all extensions
Nov 03, 2016 7:56:39 PM jenkins.InitReactorRunner$1 onAttained
INFO: Loaded all jobs
Nov 03, 2016 7:56:39 PM jenkins.InitReactorRunner$1 onAttained
INFO: Completed initialization
Nov 03, 2016 7:56:39 PM hudson.WebAppMain$3 run
INFO: Jenkins is fully up and running
Nov 03, 2016 7:56:41 PM hudson.model.UpdateSite updateData
INFO: Obtained the latest update center data file for UpdateSource default
Nov 03, 2016 7:56:41 PM hudson.model.DownloadService$Downloadable load
INFO: Obtained the updated data file for hudson.tasks.Maven.MavenInstaller
Nov 03, 2016 7:56:41 PM hudson.model.DownloadService$Downloadable load
INFO: Obtained the updated data file for hudson.tasks.Ant.AntInstaller
Nov 03, 2016 7:56:42 PM hudson.model.DownloadService$Downloadable load
INFO: Obtained the updated data file for hudson.tools.JDKInstaller
Nov 03, 2016 7:56:42 PM hudson.model.AsyncPeriodicWork$1 run
INFO: Finished Download metadata. 4,108 ms
```

**Comment by bparees** [comment]
@tdawson looks like the new plugin versions have dragged a new dependency, pipeline-graph-analysis:1.2, so we're going to need an rpm for that too and we'll have to add it to the list of packages in dockerfile.rhel7 :(

**Comment by gabemontero** [comment]
I was able to build and run jenkins-1-centos7 locally with these updates

**Pull request merged**
