### PR TITLE
Bug 2103556: Bump Jenkins 2.346.1 and various plugins bumps [release-4.10]

### PR DESCRIPTION
**Pull request by akram**
- Fix ci
- Add locales to local build
- Remove chmod on jvm-exports
- Add symlink to old jenkins.war location
- Update various plugins dependencies

### CODE REVIEW

**Comment by akram** [comment]
@coreydaley can we get this one merged before the 4.11 ?
while you are answering, I will try to reference a JIRA instead to see if the workflow is more reslilent

**Comment by dustymabe** [comment]
man.. being a subscriber to this bot chatter is pretty frustrating.. I just want to know when this merges.. Can the gods make it happen soon?

**Pull request closed without merging**
