### PR TITLE
Bug 1700314: clean up zombie process in openshift/jenkins agent image…

### PR DESCRIPTION
**Pull request by gabemontero**
… pods by employing dumb-init

### CODE REVIEW

**Comment by gabemontero** [comment]
@pradeepto @sthaha @waveywaves fyi

**Comment by gabemontero** [comment]
hmmmmm ... looks like the 3.11 e2e-gcp is skipping all the extended tests, including our jenkins e2e

sigh

**Comment by gabemontero** [comment]
I've opened https://github.com/openshift/release/issues/3647 to see start sorting out the e2e-gcp job

**Comment by gabemontero** [comment]
/hold

pending https://github.com/openshift/release/issues/3647 resolution, or relenting to manual replication of the PR testing against 3.11

**Comment by gabemontero** [comment]
So I built this manually, and using our nodejs image that was built off of a slave-base with dumb-init, it did not go so well:

```
oc logs nodejs-nk6k3
[dumb-init] a346a0409326460f7727faf1c012580fce7c8a999945af11d1ab9366c1df36f1: No such file or directory
```

Have some investigation to do.

**Comment by gabemontero** [comment]
ok got it working with a manual test case ... will run full e2e suite next

**Comment by gabemontero** [comment]
I have manually verified this change running `openshift-tests run openshift/jenkins-e2e` against a 3.11 cluster where the jenkins images were updated to use this change

we'll leave on hold until customer comes back on the "which 3.x releases" questions and then adjust the commit msg to the correct bugzilla based on whether we have to clone bugs, etc.

I'm not going to push on https://github.com/openshift/release/issues/3647 until we get past 4.x GA focus

**Comment by svenstaro** [comment]
Should this be included in the v3.11 tag as shown on https://hub.docker.com/r/openshift/jenkins-slave-base-centos7/tags?

I get this:
```
[svenstaro:~] 2 % docker pull openshift/jenkins-slave-base-centos7
Using default tag: latest
latest: Pulling from openshift/jenkins-slave-base-centos7
Digest: sha256:86db243d917e14dcd0abf0b47ceb2875fc01de338f13dfeed915bf03f9818259
Status: Image is up to date for openshift/jenkins-slave-base-centos7:latest
[svenstaro:~] % docker run --entrypoint ls openshift/jenkins-slave-base-centos7 /usr/bin/dumb-init
ls: cannot access /usr/bin/dumb-init: No such file or directory
```

**Comment by gabemontero** [comment]
You might be hitting a stale docker registry cache @svenstaro 

When I pull I get a different sha:

```
$ docker pull docker.io/openshift/jenkins-slave-base-centos7:v3.11
v3.11: Pulling from openshift/jenkins-slave-base-centos7
Digest: sha256:669da158fce7ac119ab3d9403c1862cdd35a2010bf707dbe4e1baa52fa6d6ede
Status: Downloaded newer image for openshift/jenkins-slave-base-centos7:v3.11
```

That sha/digest also matches the one from our last push job:  https://ci.openshift.redhat.com/jenkins/job/push_jenkins_images/298/consoleFull

Then when I run your command, where I updated what you typed to specify the v3.11 tag (perhaps another problem or the problem), it finds dumb-init:

```
$ docker run --entrypoint ls openshift/jenkins-slave-base-centos7:v3.11 /usr/bin/dumb-init
/usr/bin/dumb-init
$
```

**Comment by svenstaro** [comment]
Thanks @gabemontero, that was an excellent hint. My problem is that I didn't use the proper tag `v3.11` but assumed that master would have the changes which is not the case.

**Pull request merged**
