### PR TITLE
Bug 1972351: Bump jenkins version 2.289.1

### PR DESCRIPTION
**Pull request by akram**

### CODE REVIEW

**Comment by akram** [comment]
flake:
```
level=error msg=Error: [ERR]: Error building changeset: InvalidChangeBatch: [Tried to create resource record set [name='api-int.ci-op-rhwy6tr6-93a8f.origin-ci-int-aws.dev.rhcloud.com.', type='A'] but it already exists]
level=error msg=	status code: 400, request id: fdf6743a-2a4d-4f06-adb4-57b9a98e7a8b
```
/retest

**Comment by akram** [comment]
flake:
```
ps://api.ci-op-6qnf70k8-93a8f.origin-ci-int-aws.dev.rhcloud.com:6443/api?timeout=32s": dial tcp 52.52.235.121:6443: connect: connection refused, skipping gathering machineconfigs.machineconfiguration.openshift.io due to error: Get "https://api.ci-op-6qnf70k8-93a8f.origin-ci-int-aws.dev.rhcloud.com:6443/api?timeout=32s": dial tcp 52.52.235.121:6443: connect: connection refused, skipping gathering kubeletconfigs.machineconfiguration.openshift.io due to error: Get "https://api.ci-op-6qnf70k8-93a8f.origin-ci-int-aws.dev.rhcloud.com:6443/api?timeout=32s": dial tcp 52.52.235.121:6443: connect: connection refused, skipping gathering containerruntimeconfigs.machineconfiguration.openshift.io due to error: Get "https://api.ci-op-6qnf70k8-93a8f.origin-ci-int-aws.dev.rhcloud.com:6443/api?timeout=32s": dial tcp 52.52.235.121:6443: connect: connection refused, skipping gathering configs.samples.operator.openshift.io/cluster due to error: Get "https://api.ci-op-6qnf70k8-93a8f.origin-ci-int-aws.dev.rhcloud.com:6443/api?timeout=32s": dial tcp 52.52.235.121:6443: connect: connection refused, skipping gathering namespaces/openshift-cluster-samples-operator due to error: Get "https://api.ci-op-6qnf70k8-93a8f.origin-ci-int-aws.dev.rhcloud.com:6443/api/v1/namespaces/openshift-cluster-samples-operator": dial tcp 52.52.235.121:6443: connect: connection refused, skipping gathering namespaces/openshift due to error: Get "https://api.ci-op-6qnf70k8-93a8f.origin-ci-int-aws.dev.rhcloud.com:6443/api/v1/namespaces/openshift": dial tcp 52.52.235.121:6443: connect: connection refused]The connection to the server api.ci-op-6qnf70k8-93a8f.origin-ci-int-aws.dev.rhcloud.com:6443 was refused - did you specify the right host or port?
```
/retest

**Comment by akram** [comment]
Flake again
```
level=error msg=Error: [ERR]: Error building changeset: InvalidChangeBatch: [Tried to create resource record set [name='api.ci-op-6qnf70k8-93a8f.origin-ci-int-aws.dev.rhcloud.com.', type='A'] but it already exists]
level=error msg=	status code: 400, request id: 7f70e769-c8bc-4fd9-b91*-5e6999ac718*
level=error
level=error msg=  on ../tmp/openshift-install-4797*8636/route53/base.tf line 4*, in resource "aws_route53_record" "api_external_alias":
level=error msg=  4*: resource "aws_route53_record" "api_external_alias" {

```

/retest

**Comment by akram** [comment]
/hold
wait for a bit, until flakes get stabilized

**Comment by gabemontero** [comment]
@jkhelil @akram I see you all overrode the e2e's 

are we sure this change will fix the e2e-*-builds failures we are seeing in openshift/origin and other repos?

did you confirm that whatever issues you were seeing were beyond the e2e-*-builds failures? ... not seeing any detail here on the precise nature of any flakes you encountered here.

@adambkaplan FYI

**Comment by jkhelil** [comment]
@gabemontero Yes we need to new kubernetes-client-api, bumped in the PR

**Comment by gabemontero** [comment]
> @gabemontero Yes we need to new kubernetes-client-api, bumped in the PR

ok thanks @jkhelil

**Comment by akram** [comment]
ART requests:
https://issues.redhat.com/browse/ART-3066
https://issues.redhat.com/browse/ART-3065

**Pull request merged**
