### PR TITLE
Bug 1793321: [4.2] Remove use of /etc/passwd and upgrade plugins versions

### PR DESCRIPTION
**Pull request by akram**
Makes use of /etc/passwd g=rw not required
Updates Jenkins version
Updates Jenkins plugins

### CODE REVIEW

**Comment by akram** [comment]
/test e2e-aws-jenkins

terrafom flake with dns on aws

**Comment by akram** [comment]
https://updates.jenkins.io/ starts to be flaky
/retest

**Comment by akram** [comment]
/test e2e-aws-jenkins

channel close error on maven agent

**Comment by akram** [comment]
/test e2e-aws-jenkins

```
http://pkg.jenkins.io/redhat-stable/repodata/cc03defca69a6d524cd42f66a8b9aae6d6326387f5d768dd6c528ceda87ecf0b-primary.sqlite.bz2: [Errno 12] Timeout on http://pkg.jenkins.io/redhat-stable/repodata/cc03defca69a6d524cd42f66a8b9aae6d6326387f5d768dd6c528ceda87ecf0b-primary.sqlite.bz2: (28, 'Connection timed out after 30001 milliseconds')
```

**Comment by akram** [comment]
/test e2e-aws-jenkins
```
evel=fatal msg="failed to fetch Terraform Variables: failed to fetch dependency of \"Terraform Variables\": failed to fetch dependency of \"Bootstrap Ignition Config\": failed to fetch dependency of \"Common Manifests\": failed to generate asset \"DNS Config\": getting public zone for \"origin-ci-int-aws.dev.rhcloud.com\": listing hosted zones: Throttling: Rate exceeded\n\tstatus code: 400, request id: e459d132-bb31-43ff-b557-120fd1f45153"
```

**Comment by gabemontero** [comment]
`Feb  6 16:40:05.784: INFO: At 2020-02-06 16:30:14 +0000 UTC - event for nodejs-mongodb-example: {buildconfig-controller } BuildConfigInstantiateFailed: error instantiating Build from BuildConfig e2e-test-jenkins-pipeline-tgszq/nodejs-mongodb-example (0): Error resolving ImageStreamTag nodejs:12 in namespace openshift: unable to find latest tagged image`

need a 4.2 cherrypick of https://github.com/openshift/origin/pull/24391 as well ... I've started that with https://github.com/openshift/origin/pull/24511

**Comment by gabemontero** [comment]
nodejs-mongodb-example-1 build had this:

```
logSnippet: |-
      Caching blobs under "/var/cache/blobs".
      Warning: Pull failed, retrying in 5s ...
      Warning: Pull failed, retrying in 5s ...
      Warning: Pull failed, retrying in 5s ...
      error: build error: After retrying 2 times, Pull image sti...r: unable to retrieve auth token: invalid username/password
    message: Generic Build failure - check logs for details.
```

Perhaps an underlying auth blip ... certainly not the prior SCL image EOL stuff.

Let's see how consistent it is.

/retest

**Comment by gabemontero** [comment]
> nodejs-mongodb-example-1 build had this:
> 
> ```
> logSnippet: |-
>       Caching blobs under "/var/cache/blobs".
>       Warning: Pull failed, retrying in 5s ...
>       Warning: Pull failed, retrying in 5s ...
>       Warning: Pull failed, retrying in 5s ...
>       error: build error: After retrying 2 times, Pull image sti...r: unable to retrieve auth token: invalid username/password
>     message: Generic Build failure - check logs for details.
> ```
> 
> Perhaps an underlying auth blip ... certainly not the prior SCL image EOL stuff.
> 
> Let's see how consistent it is.
> 
> /retest

Or is this a function of the user/password stuff is not working for the nodejs agent image ?

May need to create a vanilla jenkins PR for comparison.

**Comment by gabemontero** [comment]
CI build issue with last run

/retest

**Pull request merged**
