### PR TITLE
🔒 Upgrade plugin versions for security-1266

### PR DESCRIPTION
**Pull request by grdryn**
From https://jenkins.io/security/advisory/2019-01-08/#SECURITY-1266:

```
SECURITY-1266 / CVE pending

Script Security sandbox protection could be circumvented during the
script compilation phase by applying AST transforming annotations such
as @Grab to source code elements.

Both the pipeline validation REST APIs and actual script/pipeline
execution are affected.

This allowed users with Overall/Read permission, or able to control
Jenkinsfile or sandboxed Pipeline shared library contents in SCM, to
bypass the sandbox protection and execute arbitrary code on the
Jenkins master.

All known unsafe AST transformations in Groovy are now prohibited in
sandboxed scripts.
```

On the Update page in the Plugin Manager inside Jenkins, for the
"Pipeline: Declarative" (pipeline-model-definition), there's the
following warning message in red:

> Warning: This plugin requires dependent plugins be upgraded and at
> least one of these dependent plugins claims to use a different
> settings format than the installed version. Jobs using that plugin
> may need to be reconfigured, and/or you may not be able to cleanly
> revert to the prior version without manually restoring old
> settings. Consult the plugin release notes for details.

### CODE REVIEW

**Comment by gabemontero** [comment]
ah well ... with ci/openshift-jenkins retired I'll have to devise a new way to get the plugin list @bparees ... probably rebuild the centos image manually after this merges to initiate our internal rhel rpm jobs

**Comment by grdryn** [comment]
> ah well ... with ci/openshift-jenkins retired I'll have to devise a new way to get the plugin list

In case it's useful, here's the part of my Jenkins CD(-ish) pipeline that does that (checks every night for a new image from you guys at DockerHub, and if so, rebuilds my image on top and stages and deploys it):

```groovy
final String res = httpRequest(
    ignoreSslErrors: true,
    acceptType: 'APPLICATION_JSON',
    authentication: '<an admin user token credential>',
    url: 'https://<jenkins url>/pluginManager/api/json?depth=1&wrapper=plugins'
).content

final Map json = readJSON text: res
final List<String> pairs = json.plugins.collect({ "${it.shortName}:${it.version}" }).sort()
println pairs.join('\n')
// writes it to installed.txt file & commits & pushes it back to the repo
```

**Comment by gabemontero** [comment]
`curl https://pkg.jenkins.io/` flakes

**Comment by gabemontero** [comment]
hey @grdryn - the PR test just hit a flake that is fixed with the changes that went into v1.0.24 of the client plugin

how about you update that plugin's version to 1.0.24 with this PR, and hopefully that will help this one pass

or if you prefer I make that update in a separate PR, and then you rebase this PR, let me know

**Comment by gabemontero** [comment]
@bparees - the chicken / egg situation with our jenkins CI is officiall in the way with getting PRs to pass

a) the jenkins e2e client plugin flake is appearing pretty consistently now
b) since we are forcing the e2e test to pick up dockerhub jenkins images, it is not picking up the 1.0.24 version of the plugin that will fix it (the jenkins client plugin job still has the older `Checking watch output again in 10000ms` messages indicative of not having the fix
c) but because of the flake we are trying to fix we can't merge this PR (or the other openshift/jenkins PRs)

I think we minimally need to 
1) green button this one (I saw the PR pass when the flake was less consistent)
2) create a PR for the new login PR version for oapi removal, green button that (its PR passed tests against 3.11); 
3) I submit the rhel RPM job
4) in parallel, once we publish to dockerhub with that, this should at least get the remove oapi PR passing 

Once that is done, then for the remaining Jenkins PRs, I go in and revert openshift/origin 's forcing the jenkins imagestream to take the image from dockerhub.  The samples operator image ref stuff merged.  So then the remaining jenkins PRs should see their jenkins imagestreams use the payload, and thus they should be testing against the actual changes from their respective PRs

**Comment by bparees** [comment]
@gabemontero sounds good, i'll merge this one and let's make sure the new image gets pushed to dockerhub.

**Comment by grdryn** [comment]
thanks folks! Should I guess I should soon update my downstream CD job to check quay.io rather than docker.io for new images built from this repo?

**Comment by bparees** [comment]
@grdryn yeah.  technically for now it'll go to both places, but the long term home is `quay.io/openshift/origin-jenkins:v4.0`  (note that the name changed slightly).

**Comment by gabemontero** [comment]
Installed plugins:
```
ace-editor:1.0.1
apache-httpcomponents-client-4-api:4.5.5-3.0
authentication-tokens:1.1
blueocean-autofavorite:1.2.2
blueocean-bitbucket-pipeline:1.9.0
blueocean-commons:1.9.0
blueocean-config:1.9.0
blueocean-core-js:1.9.0
blueocean-dashboard:1.9.0
blueocean-display-url:2.2.0
blueocean-events:1.9.0
blueocean-github-pipeline:1.9.0
blueocean-git-pipeline:1.9.0
blueocean-i18n:1.9.0
blueocean-jira:1.9.0
blueocean:1.9.0
blueocean-jwt:1.9.0
blueocean-personalization:1.9.0
blueocean-pipeline-api-impl:1.9.0
blueocean-pipeline-editor:1.9.0
blueocean-pipeline-scm-api:1.9.0
blueocean-rest-impl:1.9.0
blueocean-rest:1.9.0
blueocean-web:1.9.0
branch-api:2.0.20
cloudbees-bitbucket-branch-source:2.2.12
cloudbees-folder:6.6
conditional-buildstep:1.3.1
config-file-provider:3.2
credentials-binding:1.15
credentials:2.1.18
display-url-api:2.2.0
docker-commons:1.11
docker-workflow:1.14
durable-task:1.26
favorite:2.3.1
git-client:2.7.3
github-api:1.90
github-branch-source:2.3.6
github:1.29.2
github-organization-folder:1.6
git:3.9.1
git-server:1.7
handlebars:1.1
handy-uri-templates-2-api:2.1.6-1.0
htmlpublisher:1.16
jackson2-api:2.8.11.3
jenkins-design-language:1.9.0
jira:3.0.2
job-dsl:1.70
jquery-detached:1.2.1
jsch:0.1.54.1
junit:1.26.1
kubernetes-credentials:0.3.0
kubernetes:1.12.8
lockable-resources:2.3
mailer:1.21
mapdb-api:1.0.9.0
matrix-auth:2.2
matrix-project:1.12
mercurial:2.3
momentjs:1.1
openshift-client:1.0.24
openshift-login:1.0.13
openshift-sync:1.0.31
parameterized-trigger:2.35.2
pipeline-build-step:2.7
pipeline-github-lib:1.0
pipeline-graph-analysis:1.7
pipeline-input-step:2.8
pipeline-milestone-step:1.3.1
pipeline-model-api:1.3.4.1
pipeline-model-declarative-agent:1.1.1
pipeline-model-definition:1.3.4.1
pipeline-model-extensions:1.3.4.1
pipeline-rest-api:2.10
pipeline-stage-step:2.3
pipeline-stage-tags-metadata:1.3.4.1
pipeline-stage-view:2.10
pipeline-utility-steps:2.1.0
plain-credentials:1.4
pubsub-light:1.12
run-condition:0.10
scm-api:2.2.8
script-security:1.50
sse-gateway:1.16
ssh-credentials:1.14
structs:1.17
subversion:2.10.3
token-macro:2.0
variant:1.1
workflow-aggregator:2.6
workflow-api:2.30
workflow-basic-steps:2.11
workflow-cps-global-lib:2.11
workflow-cps:2.61.1
workflow-durable-task-step:2.22
workflow-job:2.26
workflow-multibranch:2.20
workflow-remote-loader:1.4
workflow-scm-step:2.6
workflow-step-api:2.16
workflow-support:2.22
```

**Comment by gabemontero** [comment]
rhel rpm job for osbs builds: https://buildvm.openshift.eng.bos.redhat.com:8443/job/devex/job/devex%252Fjenkins-plugins/85/

**Comment by gabemontero** [comment]
https://buildvm.openshift.eng.bos.redhat.com:8443/job/devex/job/devex%252Fjenkins-plugins/86/

**Comment by gabemontero** [comment]
3.11 PR is https://github.com/openshift/jenkins/pull/780

**Pull request merged**
