### PR TITLE
bump to latest sync plugin version

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
waiting on new version of plugin to show up in https://updates.jenkins-ci.org/download/plugins/openshift-sync/

**Comment by bparees** [comment]
[test]

**Comment by tnozicka** [comment]
@bparees This is not reflected in the `latest` image! (Just in `dev` image; I though that one was deprecated?).

```bash
$ docker pull openshift/jenkins-1-centos7:dev && docker run -it --rm -u 0 openshift/jenkins-1-centos7:dev /usr/bin/grep 'openshift-sync' /opt/openshift/base-plugins.txt
openshift-sync:0.0.12
```

```bash
$ docker pull openshift/jenkins-1-centos7:latest && docker run -it --rm -u 0 openshift/jenkins-1-centos7:latest /usr/bin/grep 'openshift-sync' /opt/openshift/base-plugins.txt
openshift-sync:0.0.11
```

**Comment by bparees** [comment]
@tnozicka our image build infrastructure is having some issues, the new image hasn't been built/published yet.  hopefully soon.

**Comment by tnozicka** [comment]
@bparees  ok, I will wait :) 
(I just wanted to make sure you know about it.)

**Comment by bparees** [comment]
@tnozicka try now (centos image)

**Comment by tnozicka** [comment]
@bparees thanks, it works now

**Pull request merged**
