### PR TITLE
cleanup jenkins versions

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero ptal

**Comment by smunilla** [comment]
:+1: Looks to match what we do for enterprise.

**Comment by gabemontero** [comment]
ooooh ... didn't know that we could pass in wildcards like `jenkins-2.*` and presumably get the latest version

**Comment by bparees** [comment]
just updated the centos file to use 2.73.3 since i'm in here.

**Comment by bparees** [comment]
@gabemontero me either.  copied it from the dist-git repo.

**Comment by bparees** [comment]
[merge]

**Pull request merged**
