### PR TITLE
Bug 2041888: bump openshift-sync to 1.0.53

### PR DESCRIPTION
**Pull request by gabemontero**
/assign @akram 
/assign @adambkaplan

### CODE REVIEW

**Comment by gabemontero** [comment]
unrelated install fail

/retest

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Comment by gabemontero** [comment]
2022-01-28T00:48:08.258147871Z Installed plugins:
2022-01-28T00:48:08.264030953Z ace-editor:1.1
2022-01-28T00:48:08.269358568Z ant:1.11
2022-01-28T00:48:08.274765090Z apache-httpcomponents-client-4-api:4.5.13-1.0
2022-01-28T00:48:08.280110803Z authentication-tokens:1.4
2022-01-28T00:48:08.285449667Z blueocean-autofavorite:1.2.4
2022-01-28T00:48:08.290744567Z blueocean-bitbucket-pipeline:1.24.8
2022-01-28T00:48:08.296034740Z blueocean-commons:1.24.8
2022-01-28T00:48:08.301525888Z blueocean-config:1.24.8
2022-01-28T00:48:08.307010263Z blueocean-core-js:1.24.8
2022-01-28T00:48:08.312347972Z blueocean-dashboard:1.24.8
2022-01-28T00:48:08.317695679Z blueocean-display-url:2.4.1
2022-01-28T00:48:08.323016161Z blueocean-events:1.24.8
2022-01-28T00:48:08.328365083Z blueocean-github-pipeline:1.24.8
2022-01-28T00:48:08.333654081Z blueocean-git-pipeline:1.24.8
2022-01-28T00:48:08.339027883Z blueocean-i18n:1.24.8
2022-01-28T00:48:08.344254363Z blueocean:1.24.8
2022-01-28T00:48:08.349558232Z blueocean-jwt:1.24.8
2022-01-28T00:48:08.354887950Z blueocean-personalization:1.24.8
2022-01-28T00:48:08.360174602Z blueocean-pipeline-api-impl:1.24.8
2022-01-28T00:48:08.365505467Z blueocean-pipeline-editor:1.24.8
2022-01-28T00:48:08.370782349Z blueocean-pipeline-scm-api:1.24.8
2022-01-28T00:48:08.376048440Z blueocean-rest-impl:1.24.8
2022-01-28T00:48:08.381278769Z blueocean-rest:1.24.8
2022-01-28T00:48:08.386569231Z blueocean-web:1.24.8
2022-01-28T00:48:08.391825883Z bootstrap4-api:4.6.0-3
2022-01-28T00:48:08.397149863Z bouncycastle-api:2.25
2022-01-28T00:48:08.402614818Z branch-api:2.6.4
2022-01-28T00:48:08.408116874Z caffeine-api:2.9.2-29.v717aac953ff3
2022-01-28T00:48:08.413446777Z checks-api:1.7.2
2022-01-28T00:48:08.418838895Z cloudbees-bitbucket-branch-source:2.4.4
2022-01-28T00:48:08.424108806Z cloudbees-folder:6.16
2022-01-28T00:48:08.429442769Z config-file-provider:3.8.1
2022-01-28T00:48:08.434754230Z configuration-as-code-groovy:1.1
2022-01-28T00:48:08.440013753Z configuration-as-code:1.54
2022-01-28T00:48:08.445297611Z credentials-binding:1.27
2022-01-28T00:48:08.450593801Z credentials:2.6.1
2022-01-28T00:48:08.455857081Z display-url-api:2.3.5
2022-01-28T00:48:08.461175025Z docker-commons:1.18
2022-01-28T00:48:08.466447312Z durable-task:493.v195aefbb0ff2
2022-01-28T00:48:08.471727877Z echarts-api:5.0.2-1
2022-01-28T00:48:08.477029800Z favorite:2.3.1
2022-01-28T00:48:08.482360373Z font-awesome-api:5.15.2-2
2022-01-28T00:48:08.487765797Z git-client:3.10.0
2022-01-28T00:48:08.493158691Z github-api:1.114.2
2022-01-28T00:48:08.498595921Z github-branch-source:2.6.0
2022-01-28T00:48:08.504177974Z github:1.34.0
2022-01-28T00:48:08.509713356Z git:4.10.0
2022-01-28T00:48:08.515081009Z git-server:1.9
2022-01-28T00:48:08.520347887Z google-oauth-plugin:1.0.6
2022-01-28T00:48:08.525542064Z groovy:2.4
2022-01-28T00:48:08.530834637Z handy-uri-templates-2-api:2.1.6-1.0
2022-01-28T00:48:08.536131080Z htmlpublisher:1.25
2022-01-28T00:48:08.541505180Z jackson2-api:2.13.0-230.v59243c64b0a5
2022-01-28T00:48:08.546908668Z jenkins-design-language:1.24.8
2022-01-28T00:48:08.552267030Z jira:3.5
2022-01-28T00:48:08.557593514Z job-dsl:1.77
2022-01-28T00:48:08.562934467Z jquery3-api:3.6.0-1
2022-01-28T00:48:08.568291440Z jsch:0.1.55.2
2022-01-28T00:48:08.573589347Z junit:1.52
2022-01-28T00:48:08.578902303Z kubernetes-client-api:5.10.1-171.vaa0774fb8c20
2022-01-28T00:48:08.584136809Z kubernetes-credentials:0.9.0
2022-01-28T00:48:08.589535311Z kubernetes:1.31.0
2022-01-28T00:48:08.594860203Z lockable-resources:2.11
2022-01-28T00:48:08.600323275Z mailer:1.34
2022-01-28T00:48:08.605789627Z mapdb-api:1.0.9.0
2022-01-28T00:48:08.611199262Z matrix-auth:2.6.8
2022-01-28T00:48:08.616639864Z matrix-project:1.19
2022-01-28T00:48:08.621966192Z mercurial:2.15
2022-01-28T00:48:08.627238422Z metrics:4.0.2.8
2022-01-28T00:48:08.632508094Z oauth-credentials:0.4
2022-01-28T00:48:08.637761177Z okhttp-api:3.12.12.2
2022-01-28T00:48:08.643126288Z openshift-client:1.0.35
2022-01-28T00:48:08.654858166Z openshift-login:1.0.26
2022-01-28T00:48:08.660343762Z openshift-sync:1.0.53
2022-01-28T00:48:08.665776914Z pam-auth:1.6
2022-01-28T00:48:08.671102226Z pipeline-build-step:2.14
2022-01-28T00:48:08.676598298Z pipeline-graph-analysis:1.10
2022-01-28T00:48:08.681928276Z pipeline-input-step:2.12
2022-01-28T00:48:08.687184036Z pipeline-milestone-step:1.3.1
2022-01-28T00:48:08.692374407Z pipeline-model-api:1.9.3
2022-01-28T00:48:08.697739137Z pipeline-model-definition:1.8.4
2022-01-28T00:48:08.703310957Z pipeline-model-extensions:1.9.3
2022-01-28T00:48:08.708909944Z pipeline-rest-api:2.15
2022-01-28T00:48:08.714238910Z pipeline-stage-step:2.5
2022-01-28T00:48:08.719585366Z pipeline-stage-tags-metadata:1.8.4
2022-01-28T00:48:08.724930216Z plain-credentials:1.7
2022-01-28T00:48:08.730240033Z plugin-util-api:2.4.0
2022-01-28T00:48:08.735516331Z popper-api:1.16.1-2
2022-01-28T00:48:08.740784910Z prometheus:2.0.10
2022-01-28T00:48:08.746003575Z pubsub-light:1.13
2022-01-28T00:48:08.751269883Z scm-api:2.6.5
2022-01-28T00:48:08.756591272Z script-security:1.78
2022-01-28T00:48:08.761827711Z snakeyaml-api:1.29.1
2022-01-28T00:48:08.767129851Z sse-gateway:1.24
2022-01-28T00:48:08.772400875Z ssh-credentials:1.19
2022-01-28T00:48:08.777686865Z structs:1.23
2022-01-28T00:48:08.782888047Z subversion:2.15.1
2022-01-28T00:48:08.788158118Z token-macro:266.v44a80cf277fd
2022-01-28T00:48:08.793484732Z trilead-api:1.0.13
2022-01-28T00:48:08.798845938Z variant:1.4
2022-01-28T00:48:08.804267690Z workflow-api:2.47
2022-01-28T00:48:08.809692524Z workflow-basic-steps:2.20
2022-01-28T00:48:08.814950074Z workflow-cps-global-lib:2.17
2022-01-28T00:48:08.820184981Z workflow-cps:2.94
2022-01-28T00:48:08.825448195Z workflow-durable-task-step:2.35
2022-01-28T00:48:08.830685108Z workflow-job:2.41
2022-01-28T00:48:08.835971532Z workflow-multibranch:2.26
2022-01-28T00:48:08.841141777Z workflow-scm-step:2.13
2022-01-28T00:48:08.846393621Z workflow-step-api:2.24
2022-01-28T00:48:08.851659244Z workflow-support:3.8

**Comment by gabemontero** [comment]
ART req:  https://issues.redhat.com/browse/ART-3715

**Pull request merged**
