### PR TITLE
Bug 1705123: clean up zombie process in openshift/jenkins agent image…

### PR DESCRIPTION
**Pull request by gabemontero**
… pods by employing dumb-init

### CODE REVIEW

**Comment by gabemontero** [comment]
@pradeepto @sthaha @waveywaves

**Comment by gabemontero** [comment]
aws vpc quota pain with e2e-aws-jenkins

**Comment by gabemontero** [comment]
/hold

per discussion with @adambkaplan we are going to start holding non critical CVE items until after 4.1.0 GA

**Comment by gabemontero** [comment]
interesting that the agent test did not fail like with my manual testing in 3.11

perhaps some ci-operator idiosyncrasies  need to be sorted out with our nodejs/maven agents building off of the slave-base we just built

**Comment by gabemontero** [comment]
have verified this change against a 3.11 cluster as part of https://github.com/openshift/jenkins/pull/844

this PR is currently blocked by needing https://github.com/cri-o/cri-o/pull/2323 as part of https://bugzilla.redhat.com/show_bug.cgi?id=1705319

**Comment by gabemontero** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1705319 is marked on qa and @bparees 's disable jenkins ext test PR has not merged yet

let's see what happens

@bparees @adambkaplan fyi

/retest

**Comment by gabemontero** [comment]
ok manually monitoring my repeat of the image builds, I confirmed that jenkins-slave-base sha `5bc91371b7f368b25a6c20affa4f8864862c94ea9d3e55b3a11e8156b546e0ff` served as the base of the nodejs and maven image builds

But given recent discussion with @adambkaplan and @bparees on forum-devex, given the lack of ICTs in the api.ci/ci-operator equation, it is possible my prior test run where I had the error in the ENTRYPOINT/CMD split in the jenkins-slave-base dockerfile, we may have hit a timing window wrt using the prior version/sha for the slavebase IST in the ci pipeline.

**Comment by gabemontero** [comment]
I've retriggered the e2e-aws-jenkins run to reverify

**Comment by gabemontero** [comment]
assuming test passes this time, we are OK for ON_QE ... still leaving hold since we are targeting this fix for 4.1.z

**Comment by adambkaplan** [comment]
@gabemontero If you think is a low-risk change, I would go ahead and merge this.
Otherwise keep on hold.

**Comment by gabemontero** [comment]
@adambkaplan yeah it is *probably* low risk, and I've been debating your point in my head since crafting the PR, but I still haven't convinced myself yet that it is a slam dunk low risk.

**Comment by gabemontero** [comment]
also need https://github.com/openshift/ocp-build-data/pull/126 for the osbs/brew side

**Pull request merged**
