### PR TITLE
switch to JDK 1.8 to fully enable OpenShift Java REST Client

### PR DESCRIPTION
**Pull request by gabemontero**
@mfojtik @bparees please merge at your earliest convenience

### CODE REVIEW

**Comment by bparees** [comment]
Change the RHEL docker file too?

**Comment by gabemontero** [comment]
Yep I'll push that one too this weekend.

Gabe

**Comment by gabemontero** [comment]
rhel dockerflie updated ... thx for the catch

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
lgtm.

**Pull request merged**
