### PR TITLE
Fix formatting in PLUGINS.md

### PR DESCRIPTION
**Pull request by Jurrie**

### CODE REVIEW

**Review by apoorvajagtap — APPROVED** [review]
Thanks for your contribution @Jurrie

**Comment by Jurrie** [comment]
Marked `/remove-lifecycle stale`, but I'm not sure how to continue here. @divyansh42 ? @apoorvajagtap ?

**Comment by Jurrie** [comment]
Marked /remove-lifecycle stale, but I'm not sure how to continue here. @divyansh42 ? @apoorvajagtap ?

**Pull request closed without merging**
