### PR TITLE
bump sync plugin

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by bparees** [comment]
@tdawson fyi

**Comment by bparees** [comment]
jenkins apppears to have failed to start entirely:
```
Created container 9fcc3307c0561c41d257bca84613327ec165915df1e6175781fc409a278eb154
Testing HTTP connection...
Sending GET request to http://172.17.0.2:8080/
Sending GET request to http://172.17.0.2:8080/
Sending GET request to http://172.17.0.2:8080/
Sending GET request to http://172.17.0.2:8080/
Sending GET request to http://172.17.0.2:8080/
Sending GET request to http://172.17.0.2:8080/
Sending GET request to http://172.17.0.2:8080/
Sending GET request to http://172.17.0.2:8080/
Sending GET request to http://172.17.0.2:8080/
Sending GET request to http://172.17.0.2:8080/
Sending GET request to http://172.17.0.2:8080/
Sending GET request to http://172.17.0.2:8080/
Sending GET request to http://172.17.0.2:8080/
Sending GET request to http://172.17.0.2:8080/
Sending GET request to http://172.17.0.2:8080/
Sending GET request to http://172.17.0.2:8080/
Sending GET request to http://172.17.0.2:8080/
Sending GET request to http://172.17.0.2:8080/
Sending GET request to http://172.17.0.2:8080/
Sending GET request to http://172.17.0.2:8080/
Stopping and removing container 9fcc3307c0561c41d257bca84613327ec165915df1e6175781fc409a278eb154...
9fcc3307c0561c41d257bca84613327ec165915df1e6175781fc409a278eb154
Dumping logs for 9fcc3307c0561c41d257bca84613327ec165915df1e6175781fc409a278eb154
Generating kubernetes-plugin configuration (/opt/openshift/configuration/config.xml.tpl) ...
Copying Jenkins configuration to /var/lib/jenkins ...
Copying 48 Jenkins plugins to /var/lib/jenkins ...
Creating initial Jenkins 'admin' user ...
Running from: /usr/lib/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
Jenkins home directory: /var/lib/jenkins found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
9fcc3307c0561c41d257bca84613327ec165915df1e6175781fc409a278eb154
Done.
ERROR: jenkins-centos7 failed testing.
```

[test]

**Comment by jimmidyson** [comment]
Different error this time:

```
WARNING: Failed to instantiate optional component org.csanchez.jenkins.plugins.kubernetes.ServiceAccountCredential$DescriptorImpl; skipping
Nov 21, 2016 10:26:57 PM io.fabric8.kubernetes.client.Config tryServiceAccount
WARNING: Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
Nov 21, 2016 10:26:57 PM io.fabric8.jenkins.openshiftsync.GlobalPluginConfiguration configChange
INFO: Waiting for Jenkins to be started
Nov 21, 2016 10:28:37 PM winstone.Logger logInternal
INFO: JVM is terminating. Shutting down Winstone
```

**Comment by jimmidyson** [comment]
[test]

**Comment by bparees** [comment]
i'm going to build this locally and see if i can get more details.

**Comment by bparees** [comment]
jenkins v2 hangs on startup for me w/ this new plugin version (appears to be same same hang you quoted above):
https://gist.github.com/bparees/aaa6a0e9a0e9d85ef4930e837b47bfc5

jenkins v1 has the same issue.

reverting to the 0.0.17 plugin (and no other changes) results in a successful startup.

**Comment by jimmidyson** [comment]
Fixed in https://github.com/jenkinsci/openshift-sync-plugin/pull/28 - sorry about that! Let's wait for this to pass before I ask Troy to repackage this time :(

**Comment by tdawson** [comment]
This has made it up to the jenkins sites.  I'm starting the rpm build.  Feel free to merge it.

**Comment by bparees** [comment]
tests passed, merging.  thanks @jimmidyson!

**Comment by jimmidyson** [comment]
Phew.

**Comment by tdawson** [comment]
rpm:
  jenkins-plugin-openshift-sync-0.1.1-1.el7
Images:
  openshift3/jenkins-1-rhel7:1.651.2-40
  openshift3/jenkins-2-rhel7:2.19-7

**Comment by jimmidyson** [comment]
Thanks @tdawson!

**Pull request merged**
