### PR TITLE
JKNS-463: Containerfile for Konflux

### PR DESCRIPTION
**Pull request by adambkaplan**
- Add Containerfile for onboarding openshift/jenkins to Konflux.
- Script to install jenkins.war updated to skip upstream RPM install if we source it from a Konflux-built artifact.

### CODE REVIEW

**Comment by adambkaplan** [comment]
/cherry-pick release-4.17

Technically we will be releasing + onboarding off of the `release-4.17` branch.

**Review by sayan-biswas — APPROVED** [review]

**Pull request merged**
