### PR TITLE
WIP: install openshift-sync via in-repo vs. download/rpm

### PR DESCRIPTION
**Pull request by gabemontero**
this install an internally built version of the sync plugin that is identified as level  `1.0.51-515f66705b6242d5255d17a12e2c9de11ef10611` where the git commit level for the plugin is https://github.com/openshift/jenkins-sync-plugin/commit/515f66705b6242d5255d17a12e2c9de11ef10611

### CODE REVIEW

**Comment by gabemontero** [comment]
terraform failures in e2e-aws, e2e-aws-jenkins-sync-plugin

**Comment by gabemontero** [comment]
@adambkaplan @akram FYI - here is how we could bump sync plugin by injecting it in repo vs. the upstream jenkins update center while we are locked out of `mvn release:prepare release:perform`

see this PR's description for the version id of the plugin

and if you look at the e2e results at https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_jenkins/1357/pull-ci-openshift-jenkins-master-e2e-aws-jenkins-sync-plugin/1471214879355441152/artifacts/e2e-aws-jenkins-sync-plugin/jenkins-sync-plugin-e2e/build-log.txt  you'll see the new test `TestSecretCredentialSyncAfterStartup` that @alicerum for our bug scenario and fix passed.

**Comment by gabemontero** [comment]
if we go this route I'll remove the WIP indicator and associate https://bugzilla.redhat.com/show_bug.cgi?id=2016058 with this PR @akram @adambkaplan

**Comment by gabemontero** [comment]
And you'll noticed sync plugin was now downloaded from the update center during the CI image build, and *ALL* the sync plugin tests passed :-) :

```
2021-12-15T20:31:41.027343079Z Installed plugins:
2021-12-15T20:31:41.033538684Z ace-editor:1.1
2021-12-15T20:31:41.038835960Z ant:1.11
2021-12-15T20:31:41.044195965Z apache-httpcomponents-client-4-api:4.5.13-1.0
2021-12-15T20:31:41.049433495Z authentication-tokens:1.4
2021-12-15T20:31:41.054813010Z blueocean-autofavorite:1.2.4
2021-12-15T20:31:41.060043990Z blueocean-bitbucket-pipeline:1.24.8
2021-12-15T20:31:41.065337042Z blueocean-commons:1.24.8
2021-12-15T20:31:41.070482961Z blueocean-config:1.24.8
2021-12-15T20:31:41.075846152Z blueocean-core-js:1.24.8
2021-12-15T20:31:41.081053003Z blueocean-dashboard:1.24.8
2021-12-15T20:31:41.086414728Z blueocean-display-url:2.4.1
2021-12-15T20:31:41.092084115Z blueocean-events:1.24.8
2021-12-15T20:31:41.097561136Z blueocean-github-pipeline:1.24.8
2021-12-15T20:31:41.102955424Z blueocean-git-pipeline:1.24.8
2021-12-15T20:31:41.108231678Z blueocean-i18n:1.24.8
2021-12-15T20:31:41.113548997Z blueocean:1.24.8
2021-12-15T20:31:41.118885932Z blueocean-jwt:1.24.8
2021-12-15T20:31:41.124590835Z blueocean-personalization:1.24.8
2021-12-15T20:31:41.130085987Z blueocean-pipeline-api-impl:1.24.8
2021-12-15T20:31:41.135442101Z blueocean-pipeline-editor:1.24.8
2021-12-15T20:31:41.140651135Z blueocean-pipeline-scm-api:1.24.8
2021-12-15T20:31:41.146007913Z blueocean-rest-impl:1.24.8
2021-12-15T20:31:41.151262893Z blueocean-rest:1.24.8
2021-12-15T20:31:41.156645026Z blueocean-web:1.24.8
2021-12-15T20:31:41.161907504Z bootstrap4-api:4.6.0-3
2021-12-15T20:31:41.167278968Z bouncycastle-api:2.25
2021-12-15T20:31:41.172726799Z branch-api:2.6.4
2021-12-15T20:31:41.178061236Z caffeine-api:2.9.2-29.v717aac953ff3
2021-12-15T20:31:41.183421130Z checks-api:1.7.2
2021-12-15T20:31:41.188809505Z cloudbees-bitbucket-branch-source:2.4.4
2021-12-15T20:31:41.194120736Z cloudbees-folder:6.16
2021-12-15T20:31:41.199475509Z config-file-provider:3.8.1
2021-12-15T20:31:41.204816665Z configuration-as-code-groovy:1.1
2021-12-15T20:31:41.210092362Z configuration-as-code:1.54
2021-12-15T20:31:41.215452591Z credentials-binding:1.27
2021-12-15T20:31:41.220694615Z credentials:2.6.1
2021-12-15T20:31:41.226213266Z display-url-api:2.3.5
2021-12-15T20:31:41.231628594Z docker-commons:1.17
2021-12-15T20:31:41.236938825Z durable-task:493.v195aefbb0ff2
2021-12-15T20:31:41.242345222Z echarts-api:5.0.2-1
2021-12-15T20:31:41.247648357Z favorite:2.3.1
2021-12-15T20:31:41.252955669Z font-awesome-api:5.15.2-2
2021-12-15T20:31:41.258291581Z git-client:3.10.0
2021-12-15T20:31:41.263683373Z github-api:1.114.2
2021-12-15T20:31:41.269080226Z github-branch-source:2.6.0
2021-12-15T20:31:41.274425278Z github:1.34.0
2021-12-15T20:31:41.279786148Z git:4.10.0
2021-12-15T20:31:41.285121251Z git-server:1.9
2021-12-15T20:31:41.290465688Z google-oauth-plugin:1.0.6
2021-12-15T20:31:41.295694965Z groovy:2.4
2021-12-15T20:31:41.300909069Z handy-uri-templates-2-api:2.1.6-1.0
2021-12-15T20:31:41.306211407Z htmlpublisher:1.25
2021-12-15T20:31:41.311644825Z jackson2-api:2.13.0-230.v59243c64b0a5
2021-12-15T20:31:41.316993408Z jenkins-design-language:1.24.8
2021-12-15T20:31:41.322255173Z jira:3.5
2021-12-15T20:31:41.327829869Z job-dsl:1.77
2021-12-15T20:31:41.333208101Z jquery3-api:3.6.0-1
2021-12-15T20:31:41.338508002Z jsch:0.1.55.2
2021-12-15T20:31:41.343890228Z junit:1.52
2021-12-15T20:31:41.349147702Z kubernetes-client-api:5.10.1-171.vaa0774fb8c20
2021-12-15T20:31:41.354426759Z kubernetes-credentials:0.9.0
2021-12-15T20:31:41.359661362Z kubernetes:1.31.1
2021-12-15T20:31:41.364990438Z lockable-resources:2.11
2021-12-15T20:31:41.370242152Z mailer:1.34
2021-12-15T20:31:41.375549916Z mapdb-api:1.0.9.0
2021-12-15T20:31:41.380848633Z matrix-auth:2.6.8
2021-12-15T20:31:41.386201023Z matrix-project:1.19
2021-12-15T20:31:41.391393467Z mercurial:2.15
2021-12-15T20:31:41.396635887Z metrics:4.0.2.8
2021-12-15T20:31:41.401834518Z oauth-credentials:0.4
2021-12-15T20:31:41.407113954Z okhttp-api:3.12.12.2
2021-12-15T20:31:41.412406508Z openshift-client:1.0.35
2021-12-15T20:31:41.417849688Z openshift-login:1.0.26
2021-12-15T20:31:41.423245105Z pam-auth:1.6
2021-12-15T20:31:41.428725337Z pipeline-build-step:2.14
2021-12-15T20:31:41.434188120Z pipeline-graph-analysis:1.10
2021-12-15T20:31:41.439446492Z pipeline-input-step:2.12
2021-12-15T20:31:41.444873605Z pipeline-milestone-step:1.3.1
2021-12-15T20:31:41.450104674Z pipeline-model-api:1.9.3
2021-12-15T20:31:41.455427071Z pipeline-model-definition:1.8.4
2021-12-15T20:31:41.460750254Z pipeline-model-extensions:1.9.3
2021-12-15T20:31:41.466103676Z pipeline-rest-api:2.15
2021-12-15T20:31:41.471305500Z pipeline-stage-step:2.5
2021-12-15T20:31:41.476624302Z pipeline-stage-tags-metadata:1.8.4
2021-12-15T20:31:41.481892777Z plain-credentials:1.7
2021-12-15T20:31:41.487062628Z plugin-util-api:2.4.0
2021-12-15T20:31:41.492236457Z popper-api:1.16.1-2
2021-12-15T20:31:41.497474619Z prometheus:2.0.10
2021-12-15T20:31:41.502808408Z pubsub-light:1.13
2021-12-15T20:31:41.508088465Z scm-api:2.6.5
2021-12-15T20:31:41.513450640Z script-security:1.78
2021-12-15T20:31:41.518694781Z snakeyaml-api:1.29.1
2021-12-15T20:31:41.524054835Z sse-gateway:1.24
2021-12-15T20:31:41.529643405Z ssh-credentials:1.19
2021-12-15T20:31:41.535064878Z structs:1.23
2021-12-15T20:31:41.540375007Z subversion:2.15.1
2021-12-15T20:31:41.545701038Z token-macro:266.v44a80cf277fd
2021-12-15T20:31:41.550956408Z trilead-api:1.0.13
2021-12-15T20:31:41.556297792Z variant:1.4
2021-12-15T20:31:41.561783502Z workflow-api:2.47
2021-12-15T20:31:41.567199138Z workflow-basic-steps:2.20
2021-12-15T20:31:41.572654642Z workflow-cps-global-lib:2.17
2021-12-15T20:31:41.577906461Z workflow-cps:2.94
2021-12-15T20:31:41.583257788Z workflow-durable-task-step:2.35
2021-12-15T20:31:41.588432462Z workflow-job:2.41
2021-12-15T20:31:41.593663968Z workflow-multibranch:2.26
2021-12-15T20:31:41.598896091Z workflow-scm-step:2.13
2021-12-15T20:31:41.604142820Z workflow-step-api:2.24
2021-12-15T20:31:41.609352017Z workflow-support:3.8

```

**Comment by akram** [comment]
@gabemontero well done ; even I really feel uncomfortable with the solution. At least, it as the benefit to be here and working.
Let's give a deadline for accounts.jenkins.io to be back online today 4PM UTC, and then make the decision of merging this one.

**Comment by gabemontero** [comment]
/close

but as we discussed in scrum today, a useful experiment that we could mutate in the future for other possible items

**Pull request closed without merging**
