### PR TITLE
validate packages get installed

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@mfojtik @gabemontero ptal.

note this will probably fail until we sort out why the rhel pipeline rpm isn't being found.

**Comment by gabemontero** [comment]
cool

On the centos side, I believe we can depend on:

`./1/Dockerfile:RUN /usr/local/bin/plugins.sh /opt/openshift/base-plugins.txt && \`

appropriately failing if it failed to download the plugin from the Jenkins update center, no?  That script has validation logic and exits with a non-zero if the download failed.

**Comment by bparees** [comment]
that was my assumption.

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[test]

**Comment by gabemontero** [comment]
@bparees in case you didn't have a chance to look, v1.0.7 of the plugin installed just fine in the latest default test check.

**Comment by bparees** [comment]
Thanks, had not gotten around to checking again.

**Pull request merged**
