### PR TITLE
create container.yaml for odcs multi-arch builds

### PR DESCRIPTION
**Pull request by jeffdyoung**
create container.yaml for odcs multi-arch builds
@dorzel @adammhaile Please review.

### CODE REVIEW

**Comment by bparees** [comment]
@jeffdyoung do you not need this for all the slave/agent images?

**Comment by jeffdyoung** [comment]
@bparees The ART tooling should create what is needed for the slave/agent containers. If not, I will open another PR. This is our first pass at a x86 + ppc64le simultaneous build, so expect a bit of trial and error. :)

**Comment by bparees** [comment]
> @bparees The ART tooling should create what is needed for the slave/agent containers. 

i'm confused since you put this file in the folder for only one of the images.....

**Comment by dorzel** [comment]
+1

**Comment by jeffdyoung** [comment]
@bparees I think oit will create (something like) this container.yml by default:
```
compose:
   signing_intent: release
   pulp_repos: true
platforms:
   only:
  - x86_64
  - ppc64le
```

If it finds a container.yaml in the upstream directories, then it will add what is in the **compose.packages** section. 
In this case:
```
compose:
  packages:
    - dumb-init
    - atomic-openshift-clients
    - jenkins-2-plugins
  signing_intent: release
  pulp_repos: true
platforms:
  only:
  - x86_64
  - ppc64le
```


I have to admit, that I'm not quite sure how oit operates (or exactly why OSBS/ODCS doesn't seem to need compose.packages for the other Dockerfiles). 
I do know that @adammhaile needs these things in place upstream so we can move forward with ODCS builds for OCP.

**Comment by bparees** [comment]
[shrug]
/lgtm

**Comment by gabemontero** [comment]
The e2e job failed building the test image with:

```
2018/10/04 06:27:07 Build jenkins-e2e-tests failed, printing logs:
Pulling image "docker-registry.default.svc:5000/ci-op-drj4hw4k/pipeline@sha256:541003e446505e868000fc9cb89a58f40b9ea72b66c0680bf3daf7b1ea447915" ...
error: error copying source path /go/src/github.com/openshift/jenkins/test-e2e/. to .: API error (404): {"message":"lstat /var/lib/docker/overlay2/f5779d4e78738830ff229f7a6c9e4989f03a3a393f7d13b38775d1e0eebc06ad/merged/go/src/github.com/openshift/jenkins/test-e2e/.: no such file or directory"}
```

Not something I've seen before.  Would not think this PR's changes have any influence.  We'll start paying attention to see how consistent this is, and ping DPTP/testplatform if it is.

**Comment by gabemontero** [comment]
Yeah still same error.

I'll try some test PRs for comparison, and then solicit help accordingly.

**Comment by bparees** [comment]
/hold

Holding until @gabemontero or someone from @openshift/sig-continuous-delivery can look at why the job is continously failing.  Looks like it expects the jenkins repo to contain test code.

also it seems like we need a sig for the developer productivity team.

**Comment by gabemontero** [comment]
Launched https://github.com/openshift/jenkins/pull/714 for some comparison prior any #forum-testplatorm / DPTP jiras / bugzillas

**Comment by stevekuznetsov** [comment]
Can you please create an issue in `openshift/release` for this?

**Comment by gabemontero** [comment]
https://github.com/openshift/release/issues/1860 created ... thanks @stevekuznetsov

**Comment by gabemontero** [comment]
@stevekuznetsov quickly discovered we had not injected an analagous test-e2e dir in the 3.10 branch ... will get that in, then retest this

**Comment by gabemontero** [comment]
https://github.com/openshift/jenkins/pull/716

**Comment by gabemontero** [comment]
@bparees let's just green button merge this one ... I don't see how adding that file will affect our centos image all all, so the e2e test doesn't tell us anything wrt what shows up in dist git based brew images, etc.

It most likely could be a bit before sorting out the e2e 3.10 branch testing ...

**Pull request merged**
