### PR TITLE
Bug 1972366: Bump jenkins version 2.289.2

### PR DESCRIPTION
**Pull request by akram**

### CODE REVIEW

**Comment by maximili0n** [comment]
Hi @akram, 
when can I expect the PR to be merged?
Best regards
Maximilian

**Comment by jkhelil** [comment]
/retitle Bug 1972366: Bump jenkins version 2.289.2

**Comment by adambkaplan** [comment]
Installed plugins:
```
ace-editor:1.1
ant:1.11
apache-httpcomponents-client-4-api:4.5.10-2.0
authentication-tokens:1.4
blueocean-autofavorite:1.2.3
blueocean-bitbucket-pipeline:1.24.4
blueocean-commons:1.24.4
blueocean-config:1.24.4
blueocean-core-js:1.24.4
blueocean-dashboard:1.24.4
blueocean-display-url:2.2.0
blueocean-events:1.24.4
blueocean-github-pipeline:1.24.4
blueocean-git-pipeline:1.24.4
blueocean-i18n:1.24.4
blueocean:1.24.4
blueocean-jwt:1.24.4
blueocean-personalization:1.24.4
blueocean-pipeline-api-impl:1.24.4
blueocean-pipeline-editor:1.24.4
blueocean-pipeline-scm-api:1.24.4
blueocean-rest-impl:1.24.4
blueocean-rest:1.24.4
blueocean-web:1.24.4
bouncycastle-api:2.18
branch-api:2.5.6
cloudbees-bitbucket-branch-source:2.4.4
cloudbees-folder:6.15
conditional-buildstep:1.3.1
config-file-provider:3.7.1
configuration-as-code-groovy:1.1
configuration-as-code:1.47
credentials-binding:1.23
credentials:2.3.15
display-url-api:2.3.4
docker-commons:1.16
docker-workflow:1.23
durable-task:1.35
echarts-api:4.7.0-4
favorite:2.3.1
git-client:3.5.1
github-api:1.114.2
github-branch-source:2.6.0
github:1.33.0
git:4.5.2
git-server:1.7
google-oauth-plugin:1.0.0
groovy:2.2
handlebars:1.1
handy-uri-templates-2-api:2.1.6-1.0
htmlpublisher:1.21
jackson2-api:2.12.1
jenkins-design-language:1.24.4
jira:3.0.17
job-dsl:1.77
jquery3-api:3.5.1-1
jquery-detached:1.2.1
jsch:0.1.55.2
junit:1.30
kubernetes-client-api:4.13.2-1
kubernetes-credentials:0.7.0
kubernetes:1.29.0
lockable-resources:2.10
mailer:1.32.1
mapdb-api:1.0.9.0
matrix-auth:2.6.2
matrix-project:1.18
mercurial:2.12
metrics:4.0.2.6
momentjs:1.1
oauth-credentials:0.3
okhttp-api:3.12.12.2
openshift-client:1.0.34
openshift-login:1.0.26
openshift-sync:1.0.46
pam-auth:1.6
parameterized-trigger:2.36
pipeline-build-step:2.12
pipeline-github-lib:1.0
pipeline-graph-analysis:1.10
pipeline-input-step:2.11
pipeline-milestone-step:1.3.1
pipeline-model-api:1.7.2
pipeline-model-declarative-agent:1.1.1
pipeline-model-definition:1.6.0
pipeline-model-extensions:1.7.2
pipeline-rest-api:2.10
pipeline-stage-step:2.3
pipeline-stage-tags-metadata:1.6.0
pipeline-stage-view:2.10
pipeline-utility-steps:2.5.0
plain-credentials:1.7
plugin-util-api:1.2.2
prometheus:2.0.0
pubsub-light:1.13
run-condition:0.10
scm-api:2.6.4
script-security:1.75
snakeyaml-api:1.27.0
sse-gateway:1.24
ssh-credentials:1.18.1
structs:1.20
subversion:2.13.2
token-macro:2.13
trilead-api:1.0.8
variant:1.4
workflow-aggregator:2.6
workflow-api:2.40
workflow-basic-steps:2.18
workflow-cps-global-lib:2.15
workflow-cps:2.87
workflow-durable-task-step:2.31
workflow-job:2.39
workflow-multibranch:2.22
workflow-remote-loader:1.5
workflow-scm-step:2.11
workflow-step-api:2.23
workflow-support:3.6
```

**Pull request merged**
