### PR TITLE
Added Agent for nodejs 10

### PR DESCRIPTION
**Pull request by waveywaves**
This adds an agent for Nodejs10  as Nodejs8 is approaching end of Long Term Support.
wrt issue #907

### CODE REVIEW

**Comment by waveywaves** [comment]
/assign @akram 

This still needs to be tested manually. Hence WIP.

**Comment by waveywaves** [comment]
@akram can you test this on your side as well. Doesn't seem to be causing any issues on mine.

**Comment by gabemontero** [comment]
@akram @waveywaves are you guys aware of the various steps involved with getting new openshift images introduced?

If not ....

there are items on both the api.ci test cluster side, as well as the ART/OSBS/Brew side, and ultimately getting it on the TBR.

@siamaksade I think should know at least about the "getting in the RH container catalog" piece.

reach out to the DPTP (James Russell is the lead) and ART (Tim Bielawa is the lead) if you have not already

**Comment by akram** [comment]
@gabemontero , I discussed these points indeed with @waveywaves privately, and I wanted to be sure indeed that we understand fully the lifecycle of the images before merging it. The merge will not happen before that.

**Comment by gabemontero** [comment]
cool / sounds good @akram - thanks

**Pull request closed without merging**
