### PR TITLE
bump sync, pipeline plugins

### PR DESCRIPTION
**Pull request by gabemontero**
fixes https://github.com/openshift/jenkins-sync-plugin/issues/163
fixes https://github.com/openshift/jenkins-plugin/issues/151

among others, as in pulls in the requisite plug versions into the jenkins image 

@openshift/devex fyi

### CODE REVIEW

**Comment by gabemontero** [comment]
[merge]

**Comment by bparees** [comment]
you talk to @jupierce about respinning the rpms w/ these, or did that already happen?

**Comment by gabemontero** [comment]
i was going to talk to @jupierce relatively soon, but am going to batch things a bit ... expecting a few more tweaks to plugins in the next week or so

**Comment by gabemontero** [comment]
and was going to wait until @coreydaley 's client plugin stuff merges, and assess where we are at with rhel vs. centos

**Comment by bparees** [comment]
k

**Comment by gabemontero** [comment]
[test]

**Pull request merged**
