### PR TITLE
full server not required for jenkins images

### PR DESCRIPTION
**Pull request by akostadinov**
Only client tools seem to be needed for Jenkins images. Do we have use cases
which require full server.

@droslean FYI

### CODE REVIEW

**Comment by gabemontero** [comment]
maybe the unit test failure is a gradle flake ... no idea why changing where we get oc from would matter there 


the e2e failure was with our old e2e set, with flaky tests given image push issues

going to retest

**Comment by gabemontero** [comment]
@bparees found a possible cause for the gradle failure (if it is persistent):  https://github.com/keeganwitt/docker-gradle/issues/57

Here is the gradle log from the failed test:

```
[1mSTEP[0m: printing container logs
OPENSHIFT_JENKINS_JVM_ARCH='', CONTAINER_MEMORY_IN_MB='8796093022207', using /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre/bin/java
OPENSHIFT_JENKINS_JVM_ARCH='', CONTAINER_MEMORY_IN_MB='8796093022207', using /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/bin/javac
[0mStarting a Gradle Daemon (subsequent builds will be faster)


[2A[1B[1m> Starting Daemon[m[17D[1B[1A[1m> Starting Daemon[m[17D[1B[1A[1m> Starting Daemon[m[17D[1B[1A[1m> Starting Daemon[m[17D[1B[1A[1m> Starting Daemon[m[17D[1B[1A[1m> Starting Daemon[m[17D[1B[1A[1m> Starting Daemon[m[17D[1B[1A[1m> Starting Daemon[m[17D[1B[1A[1m> Starting Daemon[m[17D[1B[1A[1m> Starting Daemon[m[17D[1B[1A[1m> Starting Daemon[m[17D[1B[1A[1m> Starting Daemon[m[17D[1B[1A[1m> Starting Daemon[m[17D[1B[1A> IDLE[0K[6D[1B[2A
[31mFAILURE: [39m[31mBuild failed with an exception.[39m[0K

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
[33m> [39mCould not create service of type CrossBuildFileHashCache using BuildSessionScopeServices.createCrossBuildFileHashCache().

* Try:
Run with [1m--stacktrace[m option to get the stack trace. Run with [1m--info[m or [1m--debug[m option to get more log output.

* Get more help at https://help.gradle.org

[31;1mBUILD FAILED[0;39m in 2s
```

The implication would be there is some directory presence/permission difference between origin and origin-cli.  Not sure what it would be off hand.  Some experimentation is possibly required, adding the --stacktrace, etc. args.

**Comment by gabemontero** [comment]
cluster standup failure on e2e

/test e2e-gcp

**Comment by gabemontero** [comment]
yum failure this time

**Comment by akostadinov** [comment]
btw I didn't update the e2e image because I thought it may require additional packages comared to origin-cli. If something fails with it, it is totally not from this PR.
If e2e shouldn't require full server, then I can update it as well.

**Comment by gabemontero** [comment]
the e2e image does not come into play with the failure I previously described in the ci/openshift-jenkins job @akostadinov

**Comment by bparees** [comment]
closing in deference to https://github.com/openshift/jenkins/pull/774 which uses the quay registry for the centos images explicitly.

**Pull request closed without merging**
