### PR TITLE
remove all v1 related content

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
/assign @gabemontero 

our Makefile and CI jobs were already ignoring v1 (which is too bad, i was hoping we could speed them up by removing the v1 build/test step)

**Comment by gabemontero** [comment]
do we want to delete the openshift/imagestream json file references?

**Comment by gabemontero** [comment]
There is also this comment in the Makefile:  `:# the image name (jenkins-1-centos7 in this case).  For the slave`

**Comment by bparees** [comment]
> do we want to delete the openshift/imagestream json file references?

no, we can never remove those.  People can still have resources that reference that imagestream tag.

> There is also this comment in the Makefile: :# the image name (jenkins-1-centos7 in this case). For the slave

fixed

**Pull request merged**
