### PR TITLE
bump blueocean to latest (1.1.4)

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/jenkins/issues/316

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
On Fri, Aug 4, 2017 at 11:28 AM, Ben Parees <notifications@github.com>
wrote:

> lgtm but i guess we still need to sort out getting this into rhel.
>
correct ... my thought was using
https://github.com/openshift/jenkins/pull/328 for that;
I think the ball is still in @smunilla 's court for that one, but of course
if that is not correct
advise

**Comment by bparees** [comment]
sounds right to me.

**Comment by gabemontero** [comment]
[merge]

**Pull request merged**
