### PR TITLE
Fixing/updating smoke tests with removal of nodejs and maven images

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by coreydaley** [comment]
/assign @divyansh42 @mbharatk @apoorvajagtap
for lgtm
/label px-approved
/label docs-approved
/label qe-approved

cc @smatula

**Comment by coreydaley** [comment]
/assign @smatula
Please let me know if this meets/does not meet your needs.

**Comment by smatula** [comment]
Looks like the script fails.

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_jenkins/1668/pull-ci-openshift-jenkins-master-e2e-jenkins-image-tests/1656390564246982656/artifacts/test/build-log.txt

No oc command and KUBECONFIG not set.

Would expect step to fail because of this also.

**Comment by coreydaley** [comment]
> Looks like the script fails.
> 
> https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_jenkins/1668/pull-ci-openshift-jenkins-master-e2e-jenkins-image-tests/1656390564246982656/artifacts/test/build-log.txt
> 
> No oc command and KUBECONFIG not set.
> 
> Would expect step/job to fail because of this also.

Let's sync up on Slack and try to figure out what the issue is. Please ping me whenever you are available.

**Pull request merged**
