### PR TITLE
Bug 1802297:  handle ingress certificate signed by custom ca

### PR DESCRIPTION
**Pull request by akram**

### CODE REVIEW

**Comment by akram** [comment]
I am investigating the e2e-aws-jenkins and still don't understanding how it was working in the past. Seems that `oc run --image=docker.io/openshift/origin-jenkins` doest not work well, but that's probably not the issue.
2 series of tests are failing, still looking at if for 4.2 . The stock image in 4.2 have also issues on startup.

This e2e-aws is really flaking me out
/test e2e-aws

**Comment by akram** [comment]
The upstream build was causing issue because the base image quay.io/openshift/origin-cli:latest suddenly changed the `oc run` command that creates pods instead of deployments.
Now, we are sticking to : quay.io/openshift/origin-cli:4.2

**Comment by akram** [comment]
waiting for https://github.com/openshift/origin/pull/25183

**Comment by bparees** [comment]
did not merge in time for the current Z, will be re-evaluated by the next patch manager.  Note to patch manager: this PR is blocked pending a fix to the test code here: https://github.com/openshift/origin/pull/25183

so once that test code fix merges, this should be unheld and cherry pick approved.

**Comment by akram** [comment]
/test e2e-aws-jenkins
--

**Comment by akram** [comment]
anoter flake:
```
error: unable to connect to image repository default-route-openshift-image-registry.apps.build01.ci.devcluster.openshift.com/ci-op-jrq4d35m/stable@sha256:cd035ba7a19a77a82df2829e86a14e51b075c6d37f1d25536c1d39bd20a0c996: endpoint "https://default-route-openshift-image-registry.apps.build01.ci.devcluster.openshift.com" does not support v2 API

```


/test images

**Pull request merged**
