### PR TITLE
Add kubernetes plugin slave auto-discovery

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
@bparees FYI (tested and working on centos7 image)

**Comment by bparees** [comment]
lgtm (pending packages becoming available in rhel)

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[test]

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
@bparees this is a bug in this code... if user provide custom `config.xml` we override it when we generating kubernetes config. Fixed that and will merge this when Jenkins get green.

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
