### PR TITLE
test-final-tag-into-cluster-e2e-setup

### PR DESCRIPTION
**Pull request by gabemontero**
/hold

### CODE REVIEW

**Comment by gabemontero** [comment]
hmmm ... hopefully a temporary rpm mirror problem:

```
 No match for argument: xmlstarlet
Error: Unable to find a match: xmlstarlet
error: build error: error building at STEP "RUN ln -s /usr/lib/jenkins /usr/lib64/jenkins &&     INSTALL_PKGS="dejavu-sans-fonts wget rsync gettext git tar zip unzip openssl bzip2 java-11-openjdk java-11-openjdk-devel java-1.8.0-openjdk java-1.8.0-openjdk-devel jq glibc-locale-source xmlstarlet" &&     yum install -y $INSTALL_PKGS &&     rpm -V  $INSTALL_PKGS &&     yum clean all  &&     localedef -f UTF-8 -i en_US en_US.UTF-8": error while running runtime: exit status 1 
```

**Comment by akram** [comment]
@gabemontero the `xmlstarlet` issue was fixed for 4.11, 4.10 and 4.9 by ART: they used to Content Shared Repository (CSR) containing a custom build of it.
I will ping them on slack to see if there wasn't something missing since then.

**Comment by gabemontero** [comment]
OK client plugin e2e's still look good:

```
Starting step jenkins-client-plugin-tests.
./hack/tag-ci-image.sh
Jenkins image from CI pipeline:jenkins: registry.build03.ci.openshift.org/ci-op-83qylp3t/pipeline@sha256:360887d99dc2855698c628b930eeda334162bfb662de863b81123ccfb5c06c2a
Tagging the CI generated Jenkins image registry.build03.ci.openshift.org/ci-op-83qylp3t/pipeline@sha256:360887d99dc2855698c628b930eeda334162bfb662de863b81123ccfb5c06c2a from pipeline:jenkins into the test cluster's jenkins imagestream in the openshift namespace
Current contents of the jenkins imagestream in the openshift namespace
Name:			jenkins
Namespace:		openshift
Created:		10 minutes ago
Labels:			samples.operator.openshift.io/managed=true
Annotations:		openshift.io/display-name=Jenkins
			openshift.io/image.dockerRepositoryCheck=2022-03-21T21:42:36Z
			samples.operator.openshift.io/version=4.11.0-0.ci.test-2022-03-21-212239-ci-op-83qylp3t-latest
Image Repository:	image-registry.openshift-image-registry.svc:5000/openshift/jenkins
Image Lookup:		local=false
Unique Images:		1
Tags:			2

2 (latest)
  tagged from registry.build03.ci.openshift.org/ci-op-83qylp3t/stable@sha256:360887d99dc2855698c628b930eeda334162bfb662de863b81123ccfb5c06c2a
    prefer registry pullthrough when referencing this tag

  Provides a Jenkins 2.X server on RHEL. For more information about using this container image, including OpenShift considerations, see https://github.com/openshift/jenkins/blob/master/README.md.
  Tags: jenkins

  * registry.build03.ci.openshift.org/ci-op-83qylp3t/stable@sha256:360887d99dc2855698c628b930eeda334162bfb662de863b81123ccfb5c06c2a
      10 minutes ago
Tagging registry.build03.ci.openshift.org/ci-op-83qylp3t/pipeline@sha256:360887d99dc2855698c628b930eeda334162bfb662de863b81123ccfb5c06c2a into the jenkins imagestream in the openshift namespace
Tag openshift/jenkins:2 set to registry.build03.ci.openshift.org/ci-op-83qylp3t/pipeline@sha256:360887d99dc2855698c628b930eeda334162bfb662de863b81123ccfb5c06c2a.
New contents of the jenkins imagestream in the openshift namespace
Name:			jenkins
Namespace:		openshift
Created:		10 minutes ago
Labels:			samples.operator.openshift.io/managed=true
Annotations:		openshift.io/display-name=Jenkins
			openshift.io/image.dockerRepositoryCheck=2022-03-21T21:52:56Z
			samples.operator.openshift.io/version=4.11.0-0.ci.test-2022-03-21-212239-ci-op-83qylp3t-latest
Image Repository:	image-registry.openshift-image-registry.svc:5000/openshift/jenkins
Image Lookup:		local=false
Unique Images:		1
Tags:			2

2 (latest)
  tagged from registry.build03.ci.openshift.org/ci-op-83qylp3t/pipeline@sha256:360887d99dc2855698c628b930eeda334162bfb662de863b81123ccfb5c06c2a

  * registry.build03.ci.openshift.org/ci-op-83qylp3t/pipeline@sha256:360887d99dc2855698c628b930eeda334162bfb662de863b81123ccfb5c06c2a
      10 minutes ago
```

**Comment by gabemontero** [comment]
And sync plugin is good:

```
Starting step jenkins-sync-plugin-e2e.
hack/tag-ci-image.sh
Jenkins image from CI pipeline:jenkins: registry.build03.ci.openshift.org/ci-op-83qylp3t/pipeline@sha256:360887d99dc2855698c628b930eeda334162bfb662de863b81123ccfb5c06c2a
Tagging the CI generated Jenkins image registry.build03.ci.openshift.org/ci-op-83qylp3t/pipeline@sha256:360887d99dc2855698c628b930eeda334162bfb662de863b81123ccfb5c06c2a from pipeline:jenkins into the test cluster's jenkins imagestream in the openshift namespace
Current contents of the jenkins imagestream in the openshift namespace
Name:			jenkins
Namespace:		openshift
Created:		8 minutes ago
Labels:			samples.operator.openshift.io/managed=true
Annotations:		openshift.io/display-name=Jenkins
			openshift.io/image.dockerRepositoryCheck=2022-03-21T21:43:11Z
			samples.operator.openshift.io/version=4.11.0-0.ci.test-2022-03-21-212239-ci-op-83qylp3t-latest
Image Repository:	image-registry.openshift-image-registry.svc:5000/openshift/jenkins
Image Lookup:		local=false
Unique Images:		1
Tags:			2

2 (latest)
  tagged from registry.build03.ci.openshift.org/ci-op-83qylp3t/stable@sha256:360887d99dc2855698c628b930eeda334162bfb662de863b81123ccfb5c06c2a
    prefer registry pullthrough when referencing this tag

  Provides a Jenkins 2.X server on RHEL. For more information about using this container image, including OpenShift considerations, see https://github.com/openshift/jenkins/blob/master/README.md.
  Tags: jenkins

  * registry.build03.ci.openshift.org/ci-op-83qylp3t/stable@sha256:360887d99dc2855698c628b930eeda334162bfb662de863b81123ccfb5c06c2a
      8 minutes ago
Tagging registry.build03.ci.openshift.org/ci-op-83qylp3t/pipeline@sha256:360887d99dc2855698c628b930eeda334162bfb662de863b81123ccfb5c06c2a into the jenkins imagestream in the openshift namespace
Tag openshift/jenkins:2 set to registry.build03.ci.openshift.org/ci-op-83qylp3t/pipeline@sha256:360887d99dc2855698c628b930eeda334162bfb662de863b81123ccfb5c06c2a.
New contents of the jenkins imagestream in the openshift namespace
Name:			jenkins
Namespace:		openshift
Created:		8 minutes ago
Labels:			samples.operator.openshift.io/managed=true
Annotations:		openshift.io/display-name=Jenkins
			openshift.io/image.dockerRepositoryCheck=2022-03-21T21:51:34Z
			samples.operator.openshift.io/version=4.11.0-0.ci.test-2022-03-21-212239-ci-op-83qylp3t-latest
Image Repository:	image-registry.openshift-image-registry.svc:5000/openshift/jenkins
Image Lookup:		local=false
Unique Images:		1
Tags:			2

2 (latest)
  tagged from registry.build03.ci.openshift.org/ci-op-83qylp3t/pipeline@sha256:360887d99dc2855698c628b930eeda334162bfb662de863b81123ccfb5c06c2a

  * registry.build03.ci.openshift.org/ci-op-83qylp3t/pipeline@sha256:360887d99dc2855698c628b930eeda334162bfb662de863b81123ccfb5c06c2a
      8 minutes ago
```

closing out

**Pull request closed without merging**
