### PR TITLE
Fix Localdev Dockerfile

### PR DESCRIPTION
**Pull request by divyansh42**
Earlier Localdev Dockerfile was resulting in an error when built on Local machine.
This PR provides fix for the same.
Signed-off-by: divyansh42 <diagrawa@redhat.com>

### CODE REVIEW

**Comment by coreydaley** [comment]
/assign @jitendar-singh 
for cherry-pick-approved
/assign @mbharatk 
for lgtm

**Comment by divyansh42** [comment]
There is already a PR for this fix: https://github.com/openshift/jenkins/pull/1496

**Pull request closed without merging**
