### PR TITLE
[release-4.5] Bug 1952560: bump config-file-provider to 3.7.1

### PR DESCRIPTION
**Pull request by jkhelil**

### CODE REVIEW

**Comment by jkhelil** [comment]
https://issues.redhat.com/browse/ART-3033

**Comment by jitendar-singh** [comment]
jsingh@fugaku  ~  oc new-project jenkins-test
Now using project "jenkins-test" on server "https://api.ci-ln-lgtnz52-f76d1.origin-ci-int-gce.dev.openshift.com:6443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app rails-postgresql-example

to build a new example application in Ruby. Or use kubectl to deploy a simple Kubernetes application:

    kubectl create deployment hello-node --image=k8s.gcr.io/serve_hostname

 jsingh@fugaku  ~  oc new-app jenkins-ephemeral
--> Deploying template "openshift/jenkins-ephemeral" to project jenkins-test

     Jenkins (Ephemeral)
     ---------
     Jenkins service, without persistent storage.
     
     WARNING: Any data stored will be lost upon pod destruction. Only use this template for testing.

     A Jenkins service has been created in your project.  Log into Jenkins with your OpenShift account.  The tutorial at https://github.com/openshift/origin/blob/master/examples/jenkins/README.md contains more information about using this template.

     * With parameters:
        * Jenkins Service Name=jenkins
        * Jenkins JNLP Service Name=jenkins-jnlp
        * Enable OAuth in Jenkins=true
        * Memory Limit=1Gi
        * Jenkins ImageStream Namespace=openshift
        * Disable memory intensive administrative monitors=false
        * Jenkins ImageStreamTag=jenkins:2
        * Allows use of Jenkins Update Center repository with invalid SSL certificate=false

--> Creating resources ...
    route.route.openshift.io "jenkins" created
    deploymentconfig.apps.openshift.io "jenkins" created
    serviceaccount "jenkins" created
    rolebinding.authorization.openshift.io "jenkins_edit" created
    service "jenkins-jnlp" created
    service "jenkins" created
--> Success
    Access your application via route 'jenkins-jenkins-test.apps.ci-ln-lgtnz52-f76d1.origin-ci-int-gce.dev.openshift.com' 
    Run 'oc status' to view your app.
 jsingh@fugaku  ~  oc get pods -w
NAME               READY   STATUS              RESTARTS   AGE
jenkins-1-2kll8    0/1     ContainerCreating   0          1s
jenkins-1-deploy   1/1     Running             0          6s
jenkins-1-2kll8    0/1     ContainerCreating   0          2s
jenkins-1-2kll8    0/1     ContainerCreating   0          9s
jenkins-1-2kll8    0/1     Running             0          24s
jenkins-1-2kll8    1/1     Running             0          90s
jenkins-1-deploy   0/1     Completed           0          96s
^C%                                                                                                                                                                                            ✘ jsingh@fugaku  ~  oc rsh jenkins-1-2kll8
sh-4.2$  cat /var/lib/jenkins/plugins/config-file-provider/META-INF/MANIFEST.MF |grep Implementation-Version
Implementation-Version: 3.7.1

**Pull request merged**
