### PR TITLE
move authentication content to login plugin readme

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees ptal

### CODE REVIEW

**Comment by bparees** [comment]
this one lgtm but i'm going to let you merge it in case you decide you want to make some tweaks after my feedback on the other one.

**Comment by gabemontero** [comment]
update based on return of some content previously moved the login plugin readme pushed

**Comment by bparees** [comment]
lgtm

**Comment by gabemontero** [comment]
[merge]

**Comment by gabemontero** [comment]
Looks like there was a network hiccup attempting to mark the merge's test as successful:

```
+ test_pull_requests --mark_test_success --repo jenkins --config /var/lib/jenkins/.test_pull_requests_jenkins.json
  Marking SUCCESS for pull request #--repo in repo ''
/usr/share/ruby/net/http/response.rb:119:in `error!': 404 "Not Found" (Net::HTTPServerException)
	from /bin/test_pull_requests:543:in `block in get_comments'
	from /bin/test_pull_requests:535:in `each'
	from /bin/test_pull_requests:535:in `get_comments'
	from /bin/test_pull_requests:1074:in `get_comment_matching_regex'
	from /bin/test_pull_requests:1090:in `get_comment_with_prefix'
	from /bin/test_pull_requests:779:in `mark_test_success'
	from /bin/test_pull_requests:2358:in `<main>'
Build step 'Execute shell' marked build as failure
```

@stevekuznetsov - does it make sense to add some delay / retry for this command?  Or can you tell from the output above whether an attempt was made to an invalid address?

I'll try merging again in the interim.

[merge]

**Comment by gabemontero** [comment]
well ... we can't seem to add the label "kind/test-flake" to bugs in this repo

opened a general bug ... let's see what happens:  flake https://github.com/openshift/jenkins/issues/294

[merge]

**Comment by bparees** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
It doesn't look like `"${JENKINS_PULL_ID}"` was set for that command for some reason. re[test][merge] can we reproduce it?

**Comment by stevekuznetsov** [comment]
Accidentally deleted my comment -- it looks like "${JENKINS_PULL_ID}"` didn't get threaded through the job for that command. Added some debugging re[merge]

**Comment by stevekuznetsov** [comment]
I guess you could call that progress...

```
+ test_pull_requests --mark_test_success 293 --repo jenkins --config /var/lib/jenkins/.test_pull_requests_jenkins.json
  Marking SUCCESS for pull request #293 in repo 'jenkins'
/bin/test_pull_requests:780:in `mark_test_success': undefined method `[]' for nil:NilClass (NoMethodError)
	from /bin/test_pull_requests:2358:in `<main>'
```

**Comment by stevekuznetsov** [comment]
Ah, this is an issue because Rosie is trying to mark this pull request successful for _tests_ when no test tag has been placed. That's an error my end on configuration, let me fix that.

**Comment by stevekuznetsov** [comment]
[merge]

**Pull request merged**
