### PR TITLE
Revert xmlstarlet usage

### PR DESCRIPTION
**Pull request by coreydaley**
Revert xmlstarlet usage so that we can merge/backport multiple CVE fixes
Tracking in [Bug 2117742](https://bugzilla.redhat.com/show_bug.cgi?id=2117742)

### CODE REVIEW

**Review by adambkaplan — APPROVED** [review]
/lgtm

I would use the BZ to track when xmlstarlet is restored. Alternatively, if you discover that xmlstarlet isn't needed after all, then you can simply close the BZ.

**Comment by coreydaley** [comment]
I will open another bugzilla to track restoring it, I thought I might need these bugzillas for the backports.

**Pull request merged**
