### PR TITLE
[JKNS-345] Remove all legacy pieces from Jenkins repository

### PR DESCRIPTION
**Pull request by mbharatk**
Removing all the unused legacy Docker files, agents, and unused scripts.

### CODE REVIEW

**Comment by coreydaley** [comment]
There may be a pull request needed to openshift/release first to remove the building of the nodejs and maven images, or something similar in the process that needs to be disabled first

**Comment by coreydaley** [comment]
The makefile also, I believe, automatically tries to build the nodejs and maven images, so it will need to be changed also: https://github.com/openshift/jenkins/blob/master/Makefile#L11

**Comment by mbharatk** [comment]
@coreydaley I'm going through openshift/release to find the maven and nodejs image building and found these https://github.com/mbharatk/release/blob/6cb71e19022aed34a8e6d21dc1798b90bab4dc26/ci-operator/config/openshift/jenkins/openshift-jenkins-master.yaml#L37-L54 and https://github.com/mbharatk/release/blob/6cb71e19022aed34a8e6d21dc1798b90bab4dc26/ci-operator/config/openshift/jenkins-openshift-login-plugin/openshift-jenkins-openshift-login-plugin-master.yaml#L6-L9

Along with these I'll also look for anything else that should be removed

**Comment by mbharatk** [comment]
@coreydaley should [this](https://github.com/openshift/jenkins/blob/2f5b86e25e6fe4ee5cb03a08f14a2f375b35da5a/Makefile#L16) also be changed to rhel8 ans what about the centos7, is it deprecated?

**Comment by coreydaley** [comment]
Are you able to run the `make build` command on your local machine and have it work without throwing any errors?

**Comment by coreydaley** [comment]
@mbharatk Yes, lets go ahead and setup a pull request to remove https://github.com/mbharatk/release/blob/6cb71e19022aed34a8e6d21dc1798b90bab4dc26/ci-operator/config/openshift/jenkins/openshift-jenkins-master.yaml#L37-L54 first, i think that is causing the main issue with your pull request here.

**Comment by coreydaley** [comment]
nodejs and maven imagestreams should also be removed: https://github.com/openshift/jenkins/tree/master/openshift/imagestreams

**Comment by coreydaley** [comment]
Looks like there are some smoke tests that refer to the nodejs and maven images also: https://github.com/coreydaley/openshift-jenkins/blob/master/smoke/features

**Comment by coreydaley** [comment]
It would be worth running the following commands to see what is left that could be removed:
```
# find . -name "*maven*" | grep -v ".git"
# grep -r "maven" * 
# find . -name "*nodejs*" | grep -v ".git"
# grep -r "nodejs" *
```

**Comment by coreydaley** [comment]
/hold
while we remove more items that refer to maven and nodejs

**Comment by fbm3307** [comment]
@coreydaley @mbharatk @jkhelil 
These Imagestreams needs to be removed too from openshift/library, as they are referenced there for Samples operator, this will break Samples operator at current time also.

**Pull request merged**
