### PR TITLE
[3.11] Bug 1929718: Openshift 3.11 Various fixes

### PR DESCRIPTION
**Pull request by jkhelil**
Running with OpenShift 3
OpenShift 3 is based on an older version of Kubernetes, which is not anymore directly supported since Kubernetes plugin version 1.26.0.
To get agents working for Openshift 3, add this Node Selector to your Pod Templates:
beta.kubernetes.io/os=linux

### CODE REVIEW

**Comment by akram** [comment]
for the record @jkhelil , can you please add to the PR description the following message:
```
Running with OpenShift 3
OpenShift 3 is based on an older version of Kubernetes, which is not anymore directly supported since Kubernetes plugin version 1.26.0.
To get agents working for Openshift 3, add this Node Selector to your Pod Templates:
beta.kubernetes.io/os=linux
```

/LGTM

**Comment by jkhelil** [comment]
https://issues.redhat.com/browse/ART-3076

**Comment by jkhelil** [comment]
https://issues.redhat.com/browse/ART-3077

**Pull request merged**
