### PR TITLE
JKNS-289: complete switch from ocp payload to cpaas images for both jenkins and base agent ocp images

### PR DESCRIPTION
**Pull request by gabemontero**
after this merges, and openshift/library's cron job picks it up, the we'll do the official library sync for jenkins in https://github.com/openshift/cluster-samples-operator/pull/416 and be done with OCP for this

/assign @coreydaley 
/assign @akram 
/assign @jkhelil

### CODE REVIEW

**Comment by adambkaplan** [comment]
/label px-approved

This does not change our product experience - we are already shipping two imagestreams for each image.

**Comment by adambkaplan** [comment]
/label docs-approved

This does not have any impact to product documentation that isn't already covered elswhere (we are already shipping two imagestreams).

**Comment by adambkaplan** [comment]
/cc @jitendar-singh @prietyc123 

For QE approval

**Comment by gabemontero** [comment]
we can defer approval from qe to https://github.com/openshift/cluster-samples-operator/pull/416 as that merging is when these change are actually consumable in the product

/label qe-approved

**Comment by gabemontero** [comment]
multitude of unrelated meltdowns from aws vpc to api server meltdowns (cannot even recognize the buildconfig kind)

/retest

**Comment by gabemontero** [comment]
also the changes here have no efffect on these e2e's .... the samples operator in the e2e runs does not use the imagestreams from this repo

**Comment by gabemontero** [comment]
/hold

need to update the client plugin repo to properly groupify api ref's

```
ERROR: create returned an error;
        {err=unable to recognize no matches for kind "BuildConfig" in version "v1"
```

**Comment by gabemontero** [comment]
> @gabemontero: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/e2e-aws-jenkins-client-plugin 	[6e145d6](https://github.com/openshift/jenkins/commit/6e145d6812dcba32f1e24178730edd7c1fb34f7a) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_jenkins/1434/pull-ci-openshift-jenkins-master-e2e-aws-jenkins-client-plugin/1517788834207633408) 	true 	`/test e2e-aws-jenkins-client-plugin`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openshift&repo=jenkins&pr=1434). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:gabemontero).

my dumb self by default removed the branch .... temporarily restored it until this passes / merges
then will re-delete and switch test back to master branch

**Pull request merged**
