### PR TITLE
Bug 1950175: Build with Go 1.16

### PR DESCRIPTION
**Pull request by yselkowitz**
Closes #1244, #1245﻿

### CODE REVIEW

**Comment by yselkowitz** [comment]
CI failure appears unrelated.
/assign @sbose78

**Comment by waveywaves** [comment]
/retest

@yselkowitz  I agree, they do seem unrelated

**Comment by LorbusChris** [comment]
there seems to be a problem with the AWS infra, not sure what's causing it.
> msg=Error: error updating LB Target Group (arn:aws:elasticloadbalancing:us-east-1:460538899914:targetgroup/**************-f86ad-5b2b9-aext/3068e8521bb722ec) tags: error tagging resource (arn:aws:elasticloadbalancing:us-east-1:460538899914:targetgroup/**************-f86ad-5b2b9-aext/3068e8521bb722ec): TargetGroupNotFound: Target groups 'arn:aws:elasticloadbalancing:us-east-1:460538899914:targetgroup/**************-f86ad-5b2b9-aext/3068e8521bb722ec' not found 

might be transient.
/retest

**Comment by yselkowitz** [comment]
These images have not been built for over two weeks due to this.
/assign @bparees

**Comment by yselkowitz** [comment]
Failure looks completely unrelated to this PR:
```
Cluster accessed images that were not mirrored to the testing repository or already part of the cluster, see test/extended/util/image/README.md in the openshift/origin repo:

quay.io/redhat-developer/nfs-server:latest from pods:
  ns/e2e-test-jenkins-pipeline-7l227 pod/nfs-server node/ip-10-0-164-3.ec2.internal
```

**Comment by bparees** [comment]
/hold

failing tests need investigation/mitigation

**Comment by yselkowitz** [comment]
Please note that there haven't been any successful 4.8 builds of Jenkins in almost **three** weeks, and the test error is clearly unrelated to this PR.

**Comment by waveywaves** [comment]
/rename Bug 1950175 : Build with Go 1.16

**Comment by waveywaves** [comment]
/retitle Bug 1950175 : Build with Go 1.16

**Comment by waveywaves** [comment]
/retitle Bug 1950175: Build with Go 1.16

**Comment by yselkowitz** [comment]
New CI failures are presumably a result of the k8s 1.21 rebase.

**Comment by waveywaves** [comment]
> New CI failures are presumably a result of the k8s 1.21 rebase.

@yselkowitz Any idea when the rebase happened ?

**Comment by yselkowitz** [comment]
Within the last week.

**Comment by LorbusChris** [comment]
Blocked by https://github.com/openshift/origin/pull/26088
/hold

**Comment by yselkowitz** [comment]
nfs-server fix merged
/hold cancel
/retest

**Pull request merged**
