### PR TITLE
🔒 Upgrade plugins for Jenkins security advisory 2019-01-28

### PR DESCRIPTION
**Pull request by grdryn**
https://jenkins.io/security/advisory/2019-01-28/

### CODE REVIEW

**Comment by gabemontero** [comment]
as always thanks @grdryn !

**Comment by gabemontero** [comment]
also, heads up @grdryn , we are about to the point with v4.0 where we will pushing the non-subscription, centos based, images to quay.io

I earlier today updated this repo's readme with the new pull specs

the dockerhub ones will be there for a bit longer perhaps, but I think @bparees has an itchy trigger finger when it comes to nuking the v4.0 tags on dockerhub :-) and our old ci.openshift jenkins job for pushing out there

**Comment by bparees** [comment]
> the dockerhub ones will be there for a bit longer perhaps, but I think @bparees has an itchy trigger finger when it comes to nuking the v4.0 tags on dockerhub :-) and our old ci.openshift jenkins job for pushing out there

accurate :)

the dockerhub v4.0+latest tags are already behind in that I didn't bother to manually run the push job after the last couple jenkins merges to master, so i'd rather get rid of it entirely and have people ask where it went, than be getting stale content.

**Comment by grdryn** [comment]
@gabemontero @bparees Way ahead of you! :smiley_cat: I follow all activity on this repo in case I miss anything, and yesterday I updated my nightly CD pipeline that rebuilds on new images from here so that we build on `latest` from the quay.io repo rather than the docker hub one. :+1:

**Comment by gabemontero** [comment]
Installed plugins:
```
ace-editor:1.0.1
apache-httpcomponents-client-4-api:4.5.5-3.0
authentication-tokens:1.3
blueocean-autofavorite:1.2.2
blueocean-bitbucket-pipeline:1.10.2
blueocean-commons:1.10.2
blueocean-config:1.10.2
blueocean-core-js:1.10.2
blueocean-dashboard:1.10.2
blueocean-display-url:2.2.0
blueocean-events:1.10.2
blueocean-github-pipeline:1.10.2
blueocean-git-pipeline:1.10.2
blueocean-i18n:1.10.2
blueocean-jira:1.10.2
blueocean:1.10.2
blueocean-jwt:1.10.2
blueocean-personalization:1.10.2
blueocean-pipeline-api-impl:1.10.2
blueocean-pipeline-editor:1.10.2
blueocean-pipeline-scm-api:1.10.2
blueocean-rest-impl:1.10.2
blueocean-rest:1.10.2
blueocean-web:1.10.2
branch-api:2.0.20
cloudbees-bitbucket-branch-source:2.2.15
cloudbees-folder:6.6
conditional-buildstep:1.3.1
config-file-provider:3.5
credentials-binding:1.15
credentials:2.1.18
display-url-api:2.2.0
docker-commons:1.11
docker-workflow:1.14
durable-task:1.26
favorite:2.3.1
git-client:2.7.3
github-api:1.90
github-branch-source:2.3.6
github:1.29.2
github-organization-folder:1.6
git:3.9.3
git-server:1.7
handlebars:1.1
handy-uri-templates-2-api:2.1.6-1.0
htmlpublisher:1.16
jackson2-api:2.8.11.3
jenkins-design-language:1.10.2
jira:3.0.5
job-dsl:1.70
jquery-detached:1.2.1
jsch:0.1.54.1
junit:1.26.1
kubernetes-credentials:0.3.0
kubernetes:1.12.8
lockable-resources:2.3
mailer:1.21
mapdb-api:1.0.9.0
matrix-auth:2.2
matrix-project:1.12
mercurial:2.3
momentjs:1.1
openshift-client:1.0.24
openshift-login:1.0.16
openshift-sync:1.0.31
parameterized-trigger:2.35.2
pipeline-build-step:2.7
pipeline-github-lib:1.0
pipeline-graph-analysis:1.7
pipeline-input-step:2.8
pipeline-milestone-step:1.3.1
pipeline-model-api:1.3.4.1
pipeline-model-declarative-agent:1.1.1
pipeline-model-definition:1.3.4.1
pipeline-model-extensions:1.3.4.1
pipeline-rest-api:2.10
pipeline-stage-step:2.3
pipeline-stage-tags-metadata:1.3.4.1
pipeline-stage-view:2.10
pipeline-utility-steps:2.1.0
plain-credentials:1.4
pubsub-light:1.12
run-condition:0.10
scm-api:2.2.8
script-security:1.50
sse-gateway:1.16
ssh-credentials:1.14
structs:1.17
subversion:2.10.3
token-macro:2.6
variant:1.1
workflow-aggregator:2.6
workflow-api:2.32
workflow-basic-steps:2.11
workflow-cps-global-lib:2.11
workflow-cps:2.61.1
workflow-durable-task-step:2.26
workflow-job:2.29
workflow-multibranch:2.20
workflow-remote-loader:1.4
workflow-scm-step:2.6
workflow-step-api:2.16
workflow-support:2.22
```

**Comment by gabemontero** [comment]
rhel plugin rpm job https://buildvm.openshift.eng.bos.redhat.com:8443/job/devex/job/devex%252Fjenkins-plugins/93/

**Comment by gabemontero** [comment]
dist git http://pkgs.devel.redhat.com/cgit/rpms/jenkins-2-plugins/commit/?h=rhaos-4.0-rhel-7&id=5163da7d1823d689809f335b7c0850edd387f6b6

**Pull request merged**
