### PR TITLE
OCPBUGS-13869: Mitigate CVEs and other updates

### PR DESCRIPTION
**Pull request by coreydaley**
- Mitigate CVEs
- Fix jar command
- disable dependency checking for plugins
- update plugins to latest versions

### CODE REVIEW

**Comment by coreydaley** [comment]
/assign @divyansh42 @mbharatk @apoorvajagtap
for lgtm
/label px-approved
/label docs-approved
/label qe-approved

**Review by divyansh42 — COMMENTED** [review]
/lgtm

**Comment by jlebon** [comment]
A bit late but, OOC what was the reasoning behind disabling dependency resolution? Is it to ensure that every dependent plugin is manually added at a specific version?

**Pull request merged**
