### PR TITLE
bump login plugin for bearer token after restart fix

### PR DESCRIPTION
**Pull request by gabemontero**
for https://bugzilla.redhat.com/show_bug.cgi?id=1533938

@bparees @jupierce @adammhaile fyi - will propose to support / customer that this will go out with the next errata; hopefully that is sufficient, along with downloading the plugin from the jenkins update center, vs. a hot fix

### CODE REVIEW

**Comment by gabemontero** [comment]
[merge]

**Comment by bparees** [comment]
> @bparees @jupierce @adammhaile fyi - will propose to support / customer that this will go out with the next errata; hopefully that is sufficient, along with downloading the plugin from the jenkins update center, vs. a hot fix

makes sense to me.

**Comment by gabemontero** [comment]
[merge]

**Comment by gabemontero** [comment]
[merge]

**Comment by bparees** [comment]
@gabemontero I see the issue.

Since we updated our images to use version specific tags, the older branches that are using latest are now not using our specially crafted rhel7 base image:

we build this:
````
docker build --rm -t registry.access.redhat.com/openshift3/ose 
```

which has the subscriptions built in.

But for the v3.6 branch, the image Dockerfile is still using:
```
-> Building registry.access.redhat.com/openshift3/jenkins-slave-base-rhel7 ...
Sending build context to Docker daemon 23.55 kB

Step 1 : FROM registry.access.redhat.com/rhel7
```

in master we've moved to the ose image:
https://github.com/openshift/jenkins/blob/master/2/Dockerfile.rhel7#L1

same for 3.7:
https://github.com/openshift/jenkins/blob/openshift-3.7/2/Dockerfile.rhel7#L1

So you have three choices:

1) update our CI job to go back to also producing a "rhel7" image w/ subscriptions built in.
2) update the 3.6 branch code to base off the ose image (not sure if that will necessitate other changes)
3) manually merge this change and accept that we can't build rhel7 images for the 3.6 branch (just rely on brew for that).

**Comment by bparees** [comment]
that's why your ultimate failure, while docker building the jenkins image, is:
```
This system is not receiving updates. You can use subscription-manager on the host to register and assign subscriptions.
[91mThere are no enabled repos.
 Run "yum repolist all" to see the repos you have.
 To enable Red Hat Subscription Management repositories:
     subscription-manager repos --enable <repo>
 To enable custom repositories:
     yum-config-manager --enable <repo>
```

**Comment by gabemontero** [comment]
So quick refresher.  Those Dockerfile links @bparees posted do not have tags with them.  Rationale is from https://github.com/openshift/jenkins/pull/454#issue-283749122

Key point is our internally built rhel images from this PR are not what end up in the brew pipeline.  Those are driving by builds from:

3.6) http://pkgs.devel.redhat.com/cgit/rpms/openshift-jenkins-2-docker/tree/Dockerfile?h=rhaos-3.6-rhel-7#n1

3.7) http://pkgs.devel.redhat.com/cgit/rpms/openshift-jenkins-2-docker/tree/Dockerfile?h=rhaos-3.7-rhel-7#n10

3.9) http://pkgs.devel.redhat.com/cgit/rpms/openshift-jenkins-2-docker/tree/Dockerfile?h=rhaos-3.9-rhel-7#n10

Note the difference in the from clauses for each of those.  Also, the 3.6 image is old school and not based off the ose image.  Nor does it have the oit comments around using https://github.com/openshift/enterprise-images

@jupierce - does it make sense / is it feasible to update the dist-git for the 3.6 image to mirror what we do for 3.7 and 3.9?

If so, I'll update this repo's Dockerfile.rhel7 per @bparees earlier comment, and we'll have the CD team drive the dist git updates I would think

If not, then we are left with some form of 1) and/or 3)

**Comment by bparees** [comment]
I think i'm most in favor of (1) at this point.  (2) gets confusing since either

a) it'll mean the github dockerfile and dist-git dockerfile are way out of sync (specifying different FROM base images at a minimum, possibly removing the openshift client install logic from one of them as well)

or

b) we'll actually have to update the 3.6 jenkins images we ship to be based on the ose image(and stop explicitly installing the openshift client tools) which is a pretty substantial change (should be low risk but really not something i'd be excited to take on).

**Comment by gabemontero** [comment]
OK, I'll start hunting for 1).

Howe about additionally do 3) in the interim to get the brew pipeline cooking for an image to resolve the bugzilla ?

**Comment by bparees** [comment]
@gabemontero https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/common/test_cases/rhel_base_images.yml#L42-L82

**Comment by gabemontero** [comment]
Ok, @jupierce stopped by, and he, @bparees and I chatted.

I'm going to hit the merge button on this PR.  Between @jupierce and @adammhaile either seeing this commit come down and/or seeing the 3.6 flavor of the distgit/brew build fail, adjust things accordingly and get this change started in the errata process.

Meantime I'll update our CI job to tag a fake rhel image from the ose image per the link @bparees just posted, and future 3.6 PRs should work.

thanks folks

**Pull request merged**
