### PR TITLE
allow escaped space in JENKINS_JAVA_OVERRIDES and JNLP_JAVA_OVERRIDES

### LINKED ISSUE #471: JENKINS_JAVA_OVERRIDES -D parameter is getting quoted and so not working for me
Hi tried to add 

JENKINS_JAVA_OVERRIDES

-Dhudson.model.DirectoryBrowserSupport.CSP="default-src 'none'; img-src 'self'; style-src 'self'; script-src 'self'; font-src 'self';"

to my deployment (config) but at startup Jenkins is complaining...the parameter is getting 'quoted' in a way that it's not working. What can i do?

+ exec java -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dfile.encoding=UTF8 -Duser.home=/var/lib/jenkins -Djavamelody.application-name=JENKINS '-Dhudson.model.DirectoryBrowserSupport.CSP=\"default-src' ''\''none'\''' img-src ''\''self'\'';' style-src ''\''self'\'';' script-src ''\''self'\'';' font-src ''\''self'\'';\"' -jar /usr/lib/jenkins/jenkins.war
--
  | Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true
  | Error: Could not find or load main class 'none'

### PR DESCRIPTION
**Pull request by jim-minter**
fixes #471

### CODE REVIEW

**Comment by jim-minter** [comment]
@gabemontero @bparees ptal, if you're happy with this I'll squeeze a doc update into https://github.com/openshift/openshift-docs/pull/6981

**Comment by jim-minter** [comment]
@jr00n fyi

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
Yeah I just saw this in another jenkins PR today:

```
devmapper: Thin Pool has 2115 free data blocks which is less than minimum required 2128 free data blocks. Create more free space in thin pool or use dm.min_free_space option to change behavior
make: *** [build] Error 1
++ export status=FAILURE
```

And I saw reference to this in some of the ci infra issues being worked in origin.

Just saw an announcement that some of it may have been resolved.  Will resubmit the test again in a short bit (give things a chance to settle).

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
ok ci system healed, test is passing again

in case it got lost in the shuffle @jim-minter - I'd still like to here about the possibilities of you adding a test case per https://github.com/openshift/jenkins/pull/478#pullrequestreview-88472277

thanks

**Comment by jim-minter** [comment]
[test]

**Comment by jim-minter** [comment]
@stevekuznetsov is it possible that the robot won't listen to me on this repo?  Can that be changed?
@gabemontero please could you run a test?

**Comment by bparees** [comment]
@jim-minter I think the rosie polling interval is 12 minutes these days.

**Comment by jim-minter** [comment]
> @jim-minter I think the rosie polling interval is 12 minutes these days.

But I want instant gratification, and I want it now! :smile:

**Comment by gabemontero** [comment]
cool passing tests ... squash the commits @jim-minter and we'll merge

**Comment by gabemontero** [comment]
[merge]

**Pull request merged**
