### PR TITLE
bump client/sync plugins for recent changes

### PR DESCRIPTION
**Pull request by gabemontero**
@openshift/sig-developer-experience fyi

skipping 1.0.11 of the sync plugin cause a useful addition from upstream came in after cutting 1.0.11 but before I got around to updating this image

### CODE REVIEW

**Comment by gabemontero** [comment]
yum mirror problem

/retest

**Comment by bparees** [comment]
Not immediately obvious what aspec of 
```
The command '/bin/sh -c yum-config-manager --disable epel >/dev/null || : &&     INSTALL_PKGS="bc gettext git java-1.8.0-openjdk-headless java-1.8.0-openjdk-headless.i686 lsof rsync tar unzip which zip bzip2" &&     yum install -y --setopt=tsflags=nodocs install $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum clean all &&     mkdir -p /home/jenkins &&     chown -R 1001:0 /home/jenkins &&     chmod -R g+w /home/jenkins &&     chmod 664 /etc/passwd &&     chmod -R 775 /etc/alternatives &&     chmod -R 775 /var/lib/alternatives &&     chmod -R 775 /usr/lib/jvm &&     chmod 775 /usr/bin &&     chmod 775 /usr/lib/jvm-exports &&     chmod 775 /usr/share/man/man1 &&     chmod 775 /var/lib/origin &&     unlink /usr/bin/java &&     unlink /usr/bin/jjs &&     unlink /usr/bin/keytool &&     unlink /usr/bin/orbd &&     unlink /usr/bin/pack200 &&     unlink /usr/bin/policytool &&     unlink /usr/bin/rmid &&     unlink /usr/bin/rmiregistry &&     unlink /usr/bin/servertool &&     unlink /usr/bin/tnameserv &&     unlink /usr/bin/unpack200 &&     unlink /usr/lib/jvm-exports/jre &&     unlink /usr/share/man/man1/java.1.gz &&     unlink /usr/share/man/man1/jjs.1.gz &&     unlink /usr/share/man/man1/keytool.1.gz &&     unlink /usr/share/man/man1/orbd.1.gz &&     unlink /usr/share/man/man1/pack200.1.gz &&     unlink /usr/share/man/man1/policytool.1.gz &&     unlink /usr/share/man/man1/rmid.1.gz &&     unlink /usr/share/man/man1/rmiregistry.1.gz &&     unlink /usr/share/man/man1/servertool.1.gz &&     unlink /usr/share/man/man1/tnameserv.1.gz &&     unlink /usr/share/man/man1/unpack200.1.gz' returned a non-zero code: 2
```

is failing, you may have to spin up an ami and run it yourself to get the failure output.

(i'm not sure why doing the docker build manually shows better output than our builds do)

you could also just submit a debug PR that breaks the dockerfile commands out into individual lines instead of using && which might make it easier to see which line is failing.

**Comment by gabemontero** [comment]
So the rpm -V $INSTALL_PKGS is the command that is failing.

This output that occurs after the successful yum install is from that command:

```
.M.......  g /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre/lib/amd64/server/classes.jsa
.M.......  g /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.i386/jre/lib/i386/server/classes.jsa
.M.......  g /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.i386/jre/lib/i386/server/classes.jsa

```

Now, when I run 
```
INSTALL_PKGS="bc gettext git java-1.8.0-openjdk-headless java-1.8.0-openjdk-headless.i686 lsof rsync tar unzip which zip bzip2" ;    yum install -y --setopt=tsflags=nodocs install $INSTALL_PKGS ;    rpm -V $INSTALL_PKGS
```

 from the command line of a openshfit rhel ami I provisioned, after I ran the same "jenkins repo setup" steps our aos-cd-job does, I don't see the error.

However, running `make build TARGET=rhel7 ... ` from the same ami instances repros the error above occurs.

I'll start backtracking and add additional elements for the rhel7 dockerfile (like the yum cfg mgr calls, et c.) from my command line invocations, and see if I can repro the break from the command line, and hopefully isolate which command breaks the jdk install.

**Comment by bparees** [comment]
> @bparees thoughts? ... did you run into anything like this when you first crafted the rhel_base_images.yml file?

no i don't think so.

> Unless some change occurred that required an update to the aos-cd-job rhel_base_images.yml file, I think it is time to open a bugzilla (either the CD team or the RPM team they open Jira's against).

sounds like it.  weird.

**Comment by gabemontero** [comment]
Been working with @jupierce today ... based on a few factors, pretty sure the rpm verify issue stemmed from the upgrade to rhel 7.5 in our ci related repo's last week.

He confirmed my prior finding that it only occurs when installing java in our docker builds, when we leverage the newly built ose image that the jenkins build ci job employs (meaning the logic in https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/common/test_cases/rhel_base_images.yml ... though that logic should be fine).

Some 7.4 rpms must be getting installed on 7.5 in that scenario.

Tackling from 2 fronts:
1) I've updated my debug commit to temporarily remove `rpm -V` ... just to see if the yum installs are in fact usable, at least to some degree ... not sure how the presumably missing file would manifest as a problem, but this will at least be a point of cross reference of some sort 

2) @jupierce is reaching out to the owner of the repos our ci infra is leveraging that contain the java rpms

**Comment by jupierce** [comment]
After digging more, this does not appear to be an RPM being out of date. Instead, it just doesn't seem to install in such a way that it can be verified successfully on RHEL 7.5. I've sent an email to the package owner to see what they say about the issue.

**Comment by gabemontero** [comment]
Quick update:  @jupierce started an email thread with the folks in redhat who managed 7.5 rhel we are picking.  Looks like there is already a fix in fedora, and the verification complaint stems from file permissions, and is not a breaker.

Working with them and @jupierce to get a bugzilla we can track and expedite update for us, but in the interim, I'm removing the rpm -V for the java rpms (I've added back in the rpm -V for any other rpms we install) to unblock updating the image with fixes/features.

**Pull request merged**
