### PR TITLE
goto v1027 of pipeline

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees @csrwng fyi - has the plugin version for the fix @csrwng needs

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by bparees** [comment]
more jenkins rhel failures :(

[test]

**Comment by bparees** [comment]
(failing job in case you want to look at it: https://ci.openshift.redhat.com/jenkins/job/jenkins/417/console)

**Comment by bparees** [comment]
hm
-> Re-tagging openshift/jenkins-slave-base-rhel7-candidate image to openshift/jenkins-slave-base-rhel7
unknown shorthand flag: 'f' in -f
See 'docker tag --help'.

might be caused by the docker1.12 update @danmcp just noted.  we may have to remove that flag from the vagrant plugin.

**Comment by danmcp** [comment]
@bparees You will.

**Comment by bparees** [comment]
@gabemontero you'll need to rebase on top of https://github.com/openshift/jenkins/pull/176 to get this PR to pass testing.

**Comment by bparees** [comment]
this should be able to pass now, w/ a rebase.

**Comment by gabemontero** [comment]
rebased

[test]

but most likely will cut new version of plugin based on https://github.com/openshift/jenkins-plugin/pull/102, and will then tweak this to go to v1.0.28

**Comment by gabemontero** [comment]
actually I think we will be OK .... will elaborate at https://github.com/openshift/jenkins-plugin/pull/102

**Comment by gabemontero** [comment]
So just to summarize on the latest code, the "triggered in jenkins" annotations occur:
1) on the Build object [here](https://github.com/openshift/jenkins-plugin/blob/master/src/main/java/com/openshift/jenkins/plugins/pipeline/model/IOpenShiftBuilder.java#L210), whenever a build is triggered
2) on the ReplicationController object [here](https://github.com/openshift/jenkins-plugin/blob/master/src/main/java/com/openshift/jenkins/plugins/pipeline/model/IOpenShiftDeployer.java#L83), whenever a deployment is triggered
3) on the ReplicationController object [here](https://github.com/openshift/jenkins-plugin/blob/master/src/main/java/com/openshift/jenkins/plugins/pipeline/model/IOpenShiftPlugin.java#L521), whenever the user selects to verify after triggering a build that deployments listening for the build output image in fact triggered

**Comment by gabemontero** [comment]
test job passed ...merging

**Pull request merged**
