### PR TITLE
bump sync plugin to 0.1.10

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees FYI

@tdawson - can we use this PR to initiate the generation of a new RPM for the openshift-sync-plugin?  If not of course just let me know how you want us to register the ask.

However initiated, once that new RPM is ready, and after we merge https://github.com/openshift/jenkins/pull/238 tomorrow (march 3) we'll want to also have a new set of jenkins images created on brew-pulp to facilitate QE's testing of few features we have ready (and with 3.5 code freeze tomorrow march 3, we feel safe in doing so now)

thanks

### CODE REVIEW

**Comment by bparees** [comment]
to be clear, the new RPMs would be intended for jenkins images built for 3.6, not for 3.5.

**Comment by tdawson** [comment]
If this is for 3.6, then it will be a week or two.  We still don't have the 3.6 build queues and targets setup.
But this is fine for a request.  I'll let you  know when it's been built and is ready.

**Comment by gabemontero** [comment]
gotcha - thanks for the info / help @tdawson

**Comment by gabemontero** [comment]
it isn't the gating factor, but as a fyi, https://github.com/openshift/jenkins/pull/238 has been merged

**Comment by gabemontero** [comment]
hey @tdawson - it has been a week since we last talked.  Just curious if the ETA for 3.6 build queues and targets setup is any clearer ... thanks.

**Comment by tdawson** [comment]
They are being created as I write this, so hopefully we'll have this ready by end of day today.

**Comment by gabemontero** [comment]
Great - thanks as always @tdawson !!

Heads up, I got a bug from QE this morning testing our centos image that
will necessitate another bump to openshift-sync.  I'll tag you in the PRs I
create to cut the new version of openshift-sync.

**Comment by tdawson** [comment]
No images yet, but updated rpm is built, and is in the 3.6 puddles, and on the mirrors on enterprise-3.6

**Pull request merged**
