### PR TITLE
Bug 1891694: Update Jenkins to 2.277.3 and disable setup wizard

### PR DESCRIPTION
**Pull request by waveywaves**

### CODE REVIEW

**Comment by jkhelil** [comment]
https://issues.redhat.com/browse/ART-3020

**Comment by adambkaplan** [comment]
@waveywaves @jkhelil @akram after this change, Jenkins is failing QA.

Given that the CVEs in the security advisory are rated "Moderate" and we are now in maintenance support, we should revert this change and roll back the ART bump.

**Pull request merged**
