### PR TITLE
Bug 1972354: Bump jenkins version 2.289.2

### PR DESCRIPTION
**Pull request by akram**
This PR updates broken Jenkins image in 4.7 and 4.8 which introduced a faulty dependant plugin.
The updated plugin needs this version of Jenkins.

### CODE REVIEW

**Comment by akram** [comment]
ART request:
https://issues.redhat.com/browse/ART-3068
https://issues.redhat.com/browse/ART-3067

**Comment by jitendar-singh** [comment]
Jenkins Version updated to  2.289.1
 jsingh@fugaku  ~  oc rsh jenkins-1-wv8b2
sh-4.4$  cat /var/lib/jenkins/plugins/kubernetes-client-api/META-INF/MANIFEST.MF |grep Implementation-Version
Implementation-Version: 4.13.3-1

**Comment by akram** [comment]
We are over code freeze, we will have to wait for 4.8.z for this one.
/bugzilla refresh

**Comment by jkhelil** [comment]
/retitle Bug 1972354: Bump jenkins version 2.289.2

**Comment by sdodson** [comment]
Re-validating bugzilla status after prow config updates.
/bugzilla refresh

**Pull request merged**
