### PR TITLE
update openshift-client 0.9.2

### PR DESCRIPTION
**Pull request by gabemontero**

### CODE REVIEW

**Comment by bparees** [comment]
lgtm

**Comment by gabemontero** [comment]
well it wouldn't be a jenkins image bump without having to adjust for upstream plugin churn ... sorting through list now.

**Comment by bparees** [comment]
Lol, yeah I figured you weren't going to get away with that :)

Ben Parees | OpenShift

**Comment by bparees** [comment]
For what it's worth it makes me feel really good about putting in the
plugin load test.

Ben Parees | OpenShift

**Comment by gabemontero** [comment]
Cool

**Pull request merged**
