### PR TITLE
add note explaining how to replace existing plugins via s2i

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees ptal

### CODE REVIEW

**Comment by bparees** [comment]
i know your change didn't cause the failure but i want to see if this is a flake.
[test]

**Comment by gabemontero** [comment]
10-4

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[test]

**Comment by gabemontero** [comment]
running
```
sudo env PATH=/data/src/github.com/openshift/source-to-image/_output/local/go/bin:/data/src/github.com/openshift/source-to-image/_output/local/bin/linux/amd64:/data/src/github.com/openshift/origin/_output/etcd/bin:/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64:/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin SKIP_SQUASH=1 SKIP_RHEL_SCL=1 make test TARGET=rhel7
```
in my personal ec2 instance works fine, with all the slaves built.  But in the latest test job, the nodejs slave image build fails with some nodejs dependency issues:
```
--> Finished Dependency Resolution
[91mError: Package: python-devel-2.7.5-38.el7_2.x86_64 (oso-rhui-rhel-server-releases)
           Requires: python(x86-64) = 2.7.5-38.el7_2
           Installed: python-2.7.5-39.el7_2.x86_64 (@anaconda/7.2)
               python(x86-64) = 2.7.5-39.el7_2
           Available: python-2.7.5-16.el7.x86_64 (oso-rhui-rhel-server-releases)
               python(x86-64) = 2.7.5-16.el7
           Available: python-2.7.5-18.el7_1.1.x86_64 (oso-rhui-rhel-server-releases)
               python(x86-64) = 2.7.5-18.el7_1.1
           Available: python-2.7.5-34.el7.x86_64 (oso-rhui-rhel-server-releases)
               python(x86-64) = 2.7.5-34.el7
           Available: python-2.7.5-38.el7_2.x86_64 (oso-rhui-rhel-server-releases)
               python(x86-64) = 2.7.5-38.el7_2
[0m You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by bparees** [comment]
@gabemontero thanks, i spun up an ami too but i only tested building the main jenkins, didn't think about the slaves causing the failure.  guessing the yum repos are in a bad state, hopefully it will be fixed soon.  I'm going to continue holding off on merging this until that situation is resolved because if i merge it now, it'll just cause the image pusher job to try to build the images and fail, repeatedly.

**Comment by gabemontero** [comment]
NP and yep if it persists I suppose we'll have to ping Troy.  And +1 on
delaying.

**Comment by bparees** [comment]
[test]

**Pull request merged**
