### PR TITLE
add back in rpm -V for java rpms since now on 7.6 rhel; don't try to …

### PR DESCRIPTION
**Pull request by gabemontero**
…install 'install' RPM

/assign @bparees

### CODE REVIEW

**Comment by gabemontero** [comment]
`yum flake network unreachable`

**Comment by gabemontero** [comment]
@sosiouxme with this PR we have gotten rid of the `install` yum stutter in all the applicable openshift/jenkins branches

**Comment by sosiouxme** [comment]
@gabemontero great, thanks!

**Pull request merged**
