### PR TITLE
change maintainer in dockerfiles to Akram

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/jenkins/issues/894

@bparees fyi

/assign @akram @waveywaves

### CODE REVIEW

**Comment by akram** [comment]
Tests infra looks quite sensitive. I will try other runs when us timezone will be less loaded, and then put the lgtm tag.

**Comment by bparees** [comment]
@akram if you just lgtm it it the bot will periodically retry it until it succeeds.  Not a good idea if you're not sure why the tests are failing (no reason to make the bot retry a PR that is fundamentally broken, forever), but for something like this it should be safe enough.

**Comment by akram** [comment]
ok; so 
/lgtm

**Comment by gabemontero** [comment]
If you look at the build log, you'll see RPM / mirror issues during the image build:

```
 Error downloading packages:
  gtk2-2.24.31-1.el7.x86_64: [Errno 256] No more mirrors to try.
  giflib-4.1.6-9.el7.x86_64: [Errno 256] No more mirrors to try.
error: build error: running 'yum-config-manager --disable epel >/dev/null || : &&     yum-config-manager --enable rhel-7-server-ose-onlineint-rpms || : &&     ln -s /usr/lib/jenkins /usr/lib64/jenkins &&     INSTALL_PKGS="dejavu-sans-fonts wget rsync gettext git tar zip unzip openssl bzip2 dumb-init  java-1.8.0-openjdk java-1.8.0-openjdk-devel" &&     yum install -y $INSTALL_PKGS &&     rpm -V  $INSTALL_PKGS &&     yum clean all  &&     localedef -f UTF-8 -i en_US en_US.UTF-8' failed with exit code 1
2019/07/24 09:57:32 Build jenkins-agent-nodejs succeeded after 2m12s
2019/07/24 09:57:32 Tagging jenkins-agent-nodejs into stable
2019/07/24 10:03:45 Build jenkins-agent-maven succeeded after 8m26s
2019/07/24 10:03:45 Tagging jenkins-agent-maven into stable
2019/07/24 10:03:46 Ran for 31m50s
2019/07/24 10:03:46 Submitted failure event to sentry (id=8d181fa1d9cd432b80fec26715a9d830)
error: could not run steps: step jenkins failed: could not wait for build: the build jenkins failed after 15m29s with reason DockerBuildFailed: Docker build strategy has failed.
Error downloading packages:
  gtk2-2.24.31-1.el7.x86_64: [Errno 256] No more mirrors to try.
  giflib-4.1.6-9.el7.x86_64: [Errno 256] No more mirrors to try.
```

Sometimes this is intermittent, sometimes this means either the api.ci mirrors need reset, or the broader RedHat ones do.

If this persists @akram, start working with the ART or DPTP (forum-testplatform), or @jupierce (though he may be on PTO), or @smarterclayton even as a last resort, to reconcile.

**Comment by bparees** [comment]
@gabemontero @akram the last 5 test runs failed for legit jenkins e2e test failure reasons... seems like the builds being run during the pipeline may be timing out.  It's not rpm mirror issues anymore.

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_jenkins/895/pull-ci-openshift-jenkins-master-e2e-aws-jenkins/335
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_jenkins/895/pull-ci-openshift-jenkins-master-e2e-aws-jenkins/333/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_jenkins/895/pull-ci-openshift-jenkins-master-e2e-aws-jenkins/331/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_jenkins/895/pull-ci-openshift-jenkins-master-e2e-aws-jenkins/329/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_jenkins/895/pull-ci-openshift-jenkins-master-e2e-aws-jenkins/326/

(not the same failure every time either, unfortunately)

**Comment by akram** [comment]
> @gabemontero @akram the last 5 test runs failed for legit jenkins e2e test failure reasons... seems like the builds being run during the pipeline may be timing out. It's not rpm mirror issues anymore.
> 
> https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_jenkins/895/pull-ci-openshift-jenkins-master-e2e-aws-jenkins/335
> https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_jenkins/895/pull-ci-openshift-jenkins-master-e2e-aws-jenkins/333/
> https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_jenkins/895/pull-ci-openshift-jenkins-master-e2e-aws-jenkins/331/
> https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_jenkins/895/pull-ci-openshift-jenkins-master-e2e-aws-jenkins/329/
> https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_jenkins/895/pull-ci-openshift-jenkins-master-e2e-aws-jenkins/326/
> 
> (not the same failure every time either, unfortunately)

thank you @bparees , I am reaching out #forum-testplatform if they can give more visibility.

**Comment by bparees** [comment]
> thank you @bparees , I am reaching out #forum-testplatform if they can give more visibility.

@akram i'm not sure what the testplatform team would do to help you here.  The logs+artifacts related to the test failure should already be getting gathered and this doesn't look like a test infrastructure problem at first blush.  The next steps in my mind are to dig into what the jenkins pipeline execution was doing when it failed and determine why it failed (at a quick glance it looked like the pipeline had kicked off a gradle or nodejs image build on openshift and then the pipeline timed out waiting for that image build to complete)

**Comment by gabemontero** [comment]
to reiterate what @bparees said, the e2e-jenkins test is failing, vs. some sort of infrastructure flake.

The last run at https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_jenkins/895/pull-ci-openshift-jenkins-master-e2e-aws-jenkins/349 has the necessary debug data to sort out what is going on (the timing was as such that the jobs logs were not available in the yum-config-repo PR, but we got those logs here).

@akram @waveywaves - I'm going to let you guys dive into the logs and see if you can sort it out.

That said, given the nature of the problem, I'll give you all a small hint:
- it is related to https://github.com/openshift/cluster-samples-operator/pull/158
- a change somewhat similar to https://github.com/openshift/origin/pull/23452 will be needed, though the language stack is not ruby in this case

Let's see how far you all can get.

**Comment by akram** [comment]
> to reiterate what @bparees said, the e2e-jenkins test is failing, vs. some sort of infrastructure flake.
> 
> The last run at https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_jenkins/895/pull-ci-openshift-jenkins-master-e2e-aws-jenkins/349 has the necessary debug data to sort out what is going on (the timing was as such that the jobs logs were not available in the yum-config-repo PR, but we got those logs here).
> 
> @akram @waveywaves - I'm going to let you guys dive into the logs and see if you can sort it out.
> 
> That said, given the nature of the problem, I'll give you all a small hint:
> 
> * it is related to [openshift/cluster-samples-operator#158](https://github.com/openshift/cluster-samples-operator/pull/158)
> * a change somewhat similar to [openshift/origin#23452](https://github.com/openshift/origin/pull/23452) will be needed, though the language stack is not ruby in this case
> 
> Let's see how far you all can get.

pfewww

finally, I got it @gabemontero 
```
Caught: hudson.AbortException: start-build returned an error;
401
{reference={}, err=The ImageStreamTag "nodejs:4" is invalid: from: Error resolving ImageStreamTag nodejs:4 in namespace openshift: unable to find latest tagged image
```

I will look on how to fix it now...thanks

**Comment by gabemontero** [comment]
On Thu, Jul 25, 2019 at 11:32 AM Akram Ben Aissi <notifications@github.com>
wrote:

> to reiterate what @bparees <https://github.com/bparees> said, the
> e2e-jenkins test is failing, vs. some sort of infrastructure flake.
>
> The last run at
> https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_jenkins/895/pull-ci-openshift-jenkins-master-e2e-aws-jenkins/349
> has the necessary debug data to sort out what is going on (the timing was
> as such that the jobs logs were not available in the yum-config-repo PR,
> but we got those logs here).
>
> @akram <https://github.com/akram> @waveywaves
> <https://github.com/waveywaves> - I'm going to let you guys dive into the
> logs and see if you can sort it out.
>
> That said, given the nature of the problem, I'll give you all a small hint:
>
>    - it is related to openshift/cluster-samples-operator#158
>    <https://github.com/openshift/cluster-samples-operator/pull/158>
>    - a change somewhat similar to openshift/origin#23452
>    <https://github.com/openshift/origin/pull/23452> will be needed,
>    though the language stack is not ruby in this case
>
> Let's see how far you all can get.
>
> pfewww
>
> finally, I got it @gabemontero <https://github.com/gabemontero>
>
> Caught: hudson.AbortException: start-build returned an error;
> 401
> {reference={}, err=The ImageStreamTag "nodejs:4" is invalid: from: Error resolving ImageStreamTag nodejs:4 in namespace openshift: unable to find latest tagged image
>
> I will look on how to fix it now...thanks
>

Yep that’s it.  Good job.   That bluegreen pipeline is defined in
openshift/origin.

**Comment by bparees** [comment]
/hold

Please unhold this when the e2e is fixed. Thanks


Ben Parees | OpenShift

**Pull request merged**
