### PR TITLE
update Jenkins to 2.150.2 LTS

### LINKED ISSUE #770: Included Jenkins version (2.138.4) has multipile security issues
It complains as soon as you bring it up:
https://jenkins.io/security/advisory/2019-01-16/

Can we have the included version be updated to 2.150.2 ?

### PR DESCRIPTION
**Pull request by jekader**
This PR bumps Jenkins core version to the latest LTS release.

Fixes #770

### CODE REVIEW

**Comment by gabemontero** [comment]
hit our known client plugin flake

**Comment by gabemontero** [comment]
either via https://github.com/openshift/jenkins/pull/767 or a new PR, we will pull in v1.0.24 of the client plugin, which should help with the e2e-aws-jenkins test flakes

thanks @jekader

**Comment by svenstaro** [comment]
Will you backport this fix to the v3.11 and v3.10 images as well considering this is a security fix?

**Comment by gabemontero** [comment]
we'll backport to 3.11 @svenstaro , but moving forward, if you are on a 3.10 cluster, we'll recommend you use the 3.11 image on your 3.10 cluster

we don't have the resources to keep up with the continual onslaught of jenkins security advisories across all the 3.X releases

**Comment by svenstaro** [comment]
That's fair! Thankfully we use 3.11 Jenkins :)

**Comment by gabemontero** [comment]
login plugin integration portion of tests failed ... I seem to remember this occurring when someone tried to bump to 2.150.1

I am probably going to have to build this manually and investigate.

**Comment by gabemontero** [comment]
(note ... we are waiting on https://github.com/openshift/origin/pull/21907 to test the contents of this PR)

but I wanted to get a warm fuzzy for the 2.138.4 login plugin update we pushed today

**Comment by gabemontero** [comment]
ok that passed ... good

**Comment by gabemontero** [comment]
if the latest test run here passes and the test run in https://github.com/openshift/jenkins/pull/782 fails as expected I think we are good with merging this

**Comment by gabemontero** [comment]
rhel jenkins core rpm job:  https://buildvm.openshift.eng.bos.redhat.com:8443/job/devex/job/devex%252Fjenkins-bump-version/29/

dist git: http://pkgs.devel.redhat.com/cgit/rpms/jenkins/commit/?h=rhaos-4.0-rhel-7&id=9a5e7f449346a75d02f59dedd80f6243d32f88af

**Comment by bparees** [comment]
@gabemontero  So i just checked the latest jenkins image in the payload:

oc get istag origin-v4.0:jenkins -n openshift  -o yaml

which gave me:

registry.svc.ci.openshift.org/openshift/origin-v4.0@sha256:3f1d23473329c68738fab3c184d3b3deb74b6251b07d28a4d29daa87b9f0316d

and it still contains 2.138:

$ rpm -qa | grep jenkins
jenkins-2.138.4-1.1.noarch

same for
quay.io/openshift/origin-jenkins:v4.0

It's possible it's because a release hasn't been built yet or something, but at a minimum i think we need to watch this carefully to make sure the payload+quay images get updated as we expect.

**Comment by bparees** [comment]
It also looks like that image was created yesterday, so it doesn't correspond to this merge..perhaps it's just that a new payload hasn't been built yet:

```
    - created: 2019-01-31T15:22:56Z
      dockerImageReference: docker-registry.default.svc:5000/openshift/origin-v4.0@sha256:
3f1d23473329c68738fab3c184d3b3deb74b6251b07d28a4d29daa87b9f0316d
      generation: 2989
      image: sha256:3f1d23473329c68738fab3c184d3b3deb74b6251b07d28a4d29daa87b9f0316d
```

**Comment by bparees** [comment]
https://origin-release.svc.ci.openshift.org/ shows a new payload built an hour ago :(

**Pull request merged**
