### PR TITLE
[release-4.4] Bug 1857558: Bump matrix plugin

### PR DESCRIPTION
**Pull request by jkhelil**

### CODE REVIEW

**Comment by akram** [comment]
aws cluster flakes:
invalid IP returned by infra
ebs volume cannot be detached
/test e2e-aws

**Comment by akram** [comment]
flake:
```
Unable to connect to the server: dial tcp: lookup api.ci-op-mb6sgr31-66ceb.origin-ci-int-aws.dev.rhcloud.com on 10.142.0.122:53: no such host

```

/retest

**Comment by akram** [comment]
flake with jenkins update site 
/retest

**Comment by akram** [comment]
Countless flakes 

/retest

**Comment by sdodson** [comment]
@jkhelil ptal at the e2e-aws failure

**Comment by akram** [comment]
@sdodson can you restore the cherry-pick-approved label for this one ?

**Comment by sdodson** [comment]
> @sdodson can you restore the cherry-pick-approved label for this one ?

It should be restored by this week's patch manager (not me) when the merge window opens again.

**Pull request merged**
