### PR TITLE
OCPBUGS-15530: Bump Jenkins , Jenkins Plugins and Go dependencies

### PR DESCRIPTION
**Pull request by coreydaley**
FYI: I have updated the script that lists the plugins in the Jenkins Script Console, so there are some plugins in this pull request that are the same version, but just rearranged in the list.

### CODE REVIEW

**Comment by coreydaley** [comment]
/assign @divyansh42 @mbharatk @apoorvajagtap
for lgtm

**Comment by coreydaley** [comment]
/hold
While I research if this fixes any CVEs

**Comment by apoorvajagtap** [comment]
@coreydaley I have been looking through the golang specific CVEs, and I think most of them are fixed with go v1.20.6. Should we consider bumping the go version for 1.20.6 or above?

**Comment by coreydaley** [comment]
/close
in favor of #1739

**Pull request closed without merging**
