### PR TITLE
update oc client version and jenkins LTS

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero ptal, i've opened a separate bug for @tdawson to package the new jenkins LTS for rhel.

**Comment by gabemontero** [comment]
yep, I believe the failed merge job was from rhel testing, perhaps because of the java 7 stuff with rhel you've been (thought I thought that might have merged??)

**Comment by gabemontero** [comment]
Here was the message that caught my eye:

```
The command '/bin/sh -c yum-config-manager --enable rhel-server-rhscl-7-rpms &&     yum-config-manager --disable epel >/dev/null || : &&     INSTALL_PKGS="java-1.8.0-openjdk-devel rh-maven33*" &&     yum install -y $INSTALL_PKGS &&     rpm -e java-1.7.0-openjdk --nodeps &&     rpm -e java-1.7.0-openjdk-devel --nodeps &&     rpm -e java-1.7.0-openjdk-headless --nodeps &&     rpm -V ${INSTALL_PKGS//\*/} &&     yum clean all -y &&     mkdir -p $HOME/.m2' returned a non-zero code: 1
```

**Comment by bparees** [comment]
> yep, I believe the failed merge job was from rhel testing, perhaps because of the java 7 stuff with rhel you've been (thought I thought that might have merged??)

yes it's because this PR wasn't based on a branch that included the java7 fix.  i've rebased it.  (rebasing is necessary here because the PR tester tests exactly what is in your branch.  Rosie tests your commits on top of the master branch which is why rebasing is not necessary in rosie-managed repos)

**Pull request merged**
