### PR TITLE
allow override of plugin list, jenkins config, after initial containe…

### PR DESCRIPTION
**Pull request by gabemontero**
…r start

Fixes https://github.com/openshift/jenkins/issues/335

@bparees @scoheb

### CODE REVIEW

**Comment by gabemontero** [comment]
[test] passed locally ... let's see how ec2/ci.openshift handle it

**Comment by gabemontero** [comment]
quick update ... refactoring this PR along the discussion in the issue ... will push an update once I overcome some bash parsing pain that I'm currently enduring

**Comment by gabemontero** [comment]
disdain for bash reaffirmed ... updates pushed

**Comment by gabemontero** [comment]
the git diff is less than ideal, even with `?w=1` ... but the change moved common blocks of existing code to common routines, and added an else block to the if !configured then block

**Comment by bparees** [comment]
mostly lgtm but i do wonder if we need to have per-config file granularity on this.  It seems like maybe "overwrite pv config" and "overwrite pv plugins" might be sufficient for the requested use case and easier for users.. wdyt?

**Comment by gabemontero** [comment]
yeah, that was my original thought, and went per config file based on my interpretation of your comment https://github.com/openshift/jenkins/issues/335#issuecomment-316701484

I'm fine either way, and if I misinterpreted your comment and went overboard wrt granularity, I can certainly course correct.

**Comment by bparees** [comment]
> yeah, that was my original thought, and went per config file based on my interpretation of your comment #335 (comment)
> I'm fine either way, and if I misinterpreted your comment and went overboard wrt granularity, I can certainly course correct.

yeah let's just go w/ plugins + config as the two things you can choose to keep from the PV, or replace from the image.  (with the default still being to keep what's on the PV)

**Comment by gabemontero** [comment]
OK, I've left some of the new functions just cause I think it makes the script's main path more readable, but I've removed the specific credentials/sshd/admin user overrides, leaving just main jenkins config and plugins.

Also made a small update to the readme to document the new env vars.

**Comment by bparees** [comment]
lgtm. @scoheb are you happy w/ this implementation/capability?

**Comment by scoheb** [comment]
so for my use case... I just need to set 

> OVERRIDE_PV_PLUGINS_WITH_IMAGE_PLUGINS

Looks good to me!

Thanks guys!

**Comment by gabemontero** [comment]
cool / thanks @scoheb !

I'll merge after the last test complete @bparees - thanks !

**Comment by gabemontero** [comment]
[merge]

**Comment by bparees** [comment]
@gabemontero let's make sure the new env vars make it into the docs (repo
readme at a minimum but probably the official docs need an explanation of
how config is managed too)


Ben Parees | OpenShift

**Comment by bparees** [comment]
Oops, you covered the readme already. Nm.

Ben Parees | OpenShift

**Comment by gabemontero** [comment]
mirror issue building the centos image during merge ... trying again

[merge]

**Comment by gabemontero** [comment]
ahhhh ... flake https://github.com/openshift/origin/issues/14898

[merge]

**Comment by gabemontero** [comment]
ok ... flake https://github.com/openshift/jenkins/issues/348 in the jenkins repo to pacify rosie

[merge]

**Pull request merged**
