### PR TITLE
Bug 2054822: allow Pipeline Utility Steps (2.12.0) to start

### PR DESCRIPTION
**Pull request by gabemontero**
```
java.io.IOException: Failed to load: Pipeline Utility Steps (2.12.0)
 - Update required: Script Security Plugin (1.78) to be updated to 1131.v8b_b_5eda_c328e or higher
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:1016)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:535)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1151)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

note those 2 tag levels of script security plugin seem to be at the same commit level, but plugin manager does not care.

### CODE REVIEW

**Comment by gabemontero** [comment]
/hold

I want to start this PR with clusterbot and verify things .... currently our e2e's do not parse the jenkins log for startup failures in plugins we do not depend on for "core" functionality vs. "nice to haves" our users have asked for.

**Comment by gabemontero** [comment]
@akram - I am a bit confused as to why jenkins-check-plugins-supply-chain-change failed given I ran `make plugins-list`, commited the chagnes, and pushed.

Do they have to be part of the same commit as the base-plugins.txt change?

**Comment by gabemontero** [comment]
> > @akram - I am a bit confused as to why jenkins-check-plugins-supply-chain-change failed given I ran `make plugins-list`, commited the chagnes, and pushed.
> > Do they have to be part of the same commit as the base-plugins.txt change?
> 
> I've tried squashing the commit @akram ... we'll see what happens

that did not work either @akram 

and when I run `make plugins-list` locally it does not generate any changes

what am I missing ?  ... or is there some inconsistency perhaps in how `make plugins-list` works?

**Comment by gabemontero** [comment]
yeah looking at the diffs to bundle-plugins.txt @akram most of it was alphabetical sorting changes 

I wonder if an explicit use of `sort` should be employed in the `make plugins-list` path

**Comment by gabemontero** [comment]
> yeah looking at the diffs to bundle-plugins.txt @akram most of it was alphabetical sorting changes
> 
> I wonder if an explicit use of `sort` should be employed in the `make plugins-list` path

sure enough @akram when I just took the master branch copy of bundle-plugins.txt and changed the script-security plugin to the new version, jenkins-check-plugins-supply-chain-change passes in CI

I believe there could be ordering differences in the output from install-plugins.sh, and we should add an explicit use of `sort` in the `make plugins-list` directive.

WDYT?

**Comment by gabemontero** [comment]
/hold cancel

@jitendar-singh @akram I can confirm via cluster-bot that with this PR I no longer get 

```
java.io.IOException: Failed to load: Pipeline Utility Steps (2.12.0)
 - Update required: Script Security Plugin (1.78) to be updated to 1131.v8b_b_5eda_c328e or higher
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:1016)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:535)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1151)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

and that plugin we are trying to include with this BZ if in fact fully loaded and usable and script security is at version 1131.v8b_b_5eda_c328e

**Comment by akram** [comment]
makes sense @gabemontero , I will add the `sort` there.

**Comment by gabemontero** [comment]
Installed plugins:

```
ace-editor:1.1
ant:1.11
apache-httpcomponents-client-4-api:4.5.13-1.0
authentication-tokens:1.4
blueocean-autofavorite:1.2.4
blueocean-bitbucket-pipeline:1.24.8
blueocean-commons:1.24.8
blueocean-config:1.24.8
blueocean-core-js:1.24.8
blueocean-dashboard:1.24.8
blueocean-display-url:2.4.1
blueocean-events:1.24.8
blueocean-github-pipeline:1.24.8
blueocean-git-pipeline:1.24.8
blueocean-i18n:1.24.8
blueocean:1.24.8
blueocean-jwt:1.24.8
blueocean-personalization:1.24.8
blueocean-pipeline-api-impl:1.24.8
blueocean-pipeline-editor:1.24.8
blueocean-pipeline-scm-api:1.24.8
blueocean-rest-impl:1.24.8
blueocean-rest:1.24.8
blueocean-web:1.24.8
bootstrap4-api:4.6.0-3
bouncycastle-api:2.25
branch-api:2.6.4
caffeine-api:2.9.2-29.v717aac953ff3
checks-api:1.7.2
cloudbees-bitbucket-branch-source:746.v350d2781c184
cloudbees-folder:6.16
config-file-provider:3.8.1
configuration-as-code-groovy:1.1
configuration-as-code:1.55.1
credentials-binding:1.27.1
credentials:2.6.1
display-url-api:2.3.5
docker-commons:1.18
durable-task:493.v195aefbb0ff2
echarts-api:5.0.2-1
favorite:2.3.1
font-awesome-api:5.15.2-2
git-client:3.10.0
github-api:1.114.2
github-branch-source:2.6.0
github:1.34.0
git:4.10.1
git-server:1.9
google-oauth-plugin:1.0.6
groovy:2.4
handy-uri-templates-2-api:2.1.8-1.0
htmlpublisher:1.25
jackson2-api:2.13.1-242.v1a45bad25ceb
javax-activation-api:1.2.0-2
javax-mail-api:1.6.2-2
jenkins-design-language:1.24.8
jira:3.5
job-dsl:1.77
jquery3-api:3.6.0-1
jsch:0.1.55.2
junit:1.52
kubernetes-client-api:5.10.1-171.vaa0774fb8c20
kubernetes-credentials:0.9.0
kubernetes:1.31.0
lockable-resources:2.11
mailer:408.vd726a_1130320
mapdb-api:1.0.9.0
matrix-auth:2.6.8
matrix-project:1.20
mercurial:2.15
metrics:4.0.2.8.1
oauth-credentials:0.4
okhttp-api:3.12.12.2
openshift-client:1.0.35
openshift-login:1.0.27
openshift-sync:1.0.53
pam-auth:1.6
pipeline-build-step:2.14
pipeline-graph-analysis:1.10
pipeline-input-step:2.12
pipeline-milestone-step:1.3.1
pipeline-model-api:1.9.3
pipeline-model-definition:1.8.4
pipeline-model-extensions:1.9.3
pipeline-rest-api:2.15
pipeline-stage-step:2.5
pipeline-stage-tags-metadata:1.8.4
pipeline-utility-steps:2.12.0
plain-credentials:1.7
plugin-util-api:2.4.0
popper-api:1.16.1-2
prometheus:2.0.10
pubsub-light:1.13
scm-api:2.6.5
script-security:1131.v8b_b_5eda_c328e
snakeyaml-api:1.29.1
sse-gateway:1.24
ssh-credentials:1.19
structs:308.v852b473a2b8c
subversion:2.15.1
token-macro:267.vcdaea6462991
trilead-api:1.0.13
variant:1.4
workflow-api:2.47
workflow-basic-steps:2.20
workflow-cps-global-lib:2.17
workflow-cps:2648.va9433432b33c
workflow-durable-task-step:2.35
workflow-job:2.41
workflow-multibranch:2.26
workflow-scm-step:2.13
workflow-step-api:622.vb_8e7c15b_c95a_
workflow-support:3.8
```

**Comment by gabemontero** [comment]
ART req https://issues.redhat.com/browse/ART-3817

**Pull request merged**
