### PR TITLE
update jenkins version to 2.89.3 for centos image

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/jenkins/issues/487

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
@openshift/sig-developer-experience fyi

**Comment by gabemontero** [comment]
https://buildvm.openshift.eng.bos.redhat.com:8443/job/devex/job/devex%252Fjenkins-bump-version/9/ should be handling the rhel image

**Comment by bparees** [comment]
lgtm

**Comment by bparees** [comment]
I assume the process is to wait for the package to build, then re-test this PR to ensure the rhel build done here picks up the new rpm?

**Comment by gabemontero** [comment]
that is correct  .... the current test run is verifying the centos path ... will then rerun once the new rhel build is done and available

**Comment by gabemontero** [comment]
And the above job just finished and we have a new commit at http://pkgs.devel.redhat.com/cgit/rpms/jenkins/?h=rhaos-3.9-rhel-7

**Comment by gabemontero** [comment]
From centos test job:

```
Installed:
  dejavu-sans-fonts.noarch 0:2.33-6.el7                                         
  dumb-init.x86_64 0:1.1.3-9.el7.centos                                         
  gettext.x86_64 0:0.19.8.1-2.el7                                               
  java-1.8.0-openjdk.i686 1:1.8.0.161-0.b14.el7_4                               
  java-1.8.0-openjdk.x86_64 1:1.8.0.161-0.b14.el7_4                             
  java-1.8.0-openjdk-devel.i686 1:1.8.0.161-0.b14.el7_4                         
  java-1.8.0-openjdk-devel.x86_64 1:1.8.0.161-0.b14.el7_4                       
  jenkins.noarch 0:2.89.3-1.1                                                   
  unzip.x86_64 0:6.0-16.el7                                                     
  zip.x86_64 0:3.0-11.el7                                                       
```

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
the rhel image is still at 2.89.2 for jenkins

but I think it might be a matter of being patient; if I understood @jupierce correctly this morning, some additional steps have to occur after the completion of https://buildvm.openshift.eng.bos.redhat.com:8443/job/devex/job/devex%252Fjenkins-bump-version/9/ and when they have completed we should see an email on aos-cicd indicating an update ... then openshift jenkins rhel image builds should pick up the new rpm.

**Comment by jupierce** [comment]
@gabemontero Whatever is in master builds M,W,F unless we trigger it manually before that. So after running this job for 3.9, the RPM will be pulled into the subsequent 3.9 build images.

**Comment by gabemontero** [comment]
ah thanks @jupierce 

I'll look out for any aos-cicd notices along those lines Wednesday, or otherwise try again EOB Wed or Thursday AM.

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
ok our test output shows both the centos and rhel jenkins images at version 2.89.3

**Comment by gabemontero** [comment]
[merge]

**Pull request merged**
