### PR TITLE
Move nss_wrapper to container entrypoint

### PR DESCRIPTION
**Pull request by mfojtik**
(Should) fix: https://github.com/openshift/jenkins/issues/83

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
@bparees my faith here is that the entrypoint will always set the nss_wrapper right for any command that user run with "docker exec" or "oc rsh" or "oc exec". What do you think?

(need to test this in OpenShift)

**Comment by rhcarvalho** [comment]
@mfojtik `oc rsh` replaces the entrypoint, by default with "/bin/bash", or with any other command you pass in the CLI. And `oc rsh` is using the same code path as `oc exec`, which is the one replacing the entrypoint, so no luck there AFAICT.

Last, `docker exec` is also ignoring the entrypoint. The entrypoint is only used as a default for `docker run`.

**Comment by mfojtik** [comment]
@rhcarvalho yeah, you're right. I thought `oc rsh` respects the entrypoint. @bparees so there is no good
solution for this other than executing the entrypoint.sh with /bin/bash as argument...

**Comment by mfojtik** [comment]
OK scratch this PR... this actually breaks the S2I build (assemble will generate passwd first and the run can't access that file anymore...).

**Pull request closed without merging**
