### PR TITLE
bump sync plugin to address blueocean plugin api change

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/origin/issues/15685

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
test flake https://github.com/openshift/jenkins/issues/348

mirrors are a broader issue at the moment getting worked by the ops team ... will try again once they announce some progress on the matter

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
flake was provisioning ec2 instance but not going to open a separate flake in jenkins repo for that too so https://github.com/openshift/jenkins/issues/348

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
back to mirror flake https://github.com/openshift/jenkins/issues/348

will try again later

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Pull request merged**
