### PR TITLE
Fix ocp3.11 image label for rhel7

### PR DESCRIPTION
**Pull request by akram**

### CODE REVIEW

**Comment by gabemontero** [comment]
> /override ci/prow/e2e-gcp

so you now have the power @akram ;-)

**Comment by akram** [comment]
I knew about it before, but I tried to keep it secret .... cause we all know the Spiderman Theorem

**Comment by gabemontero** [comment]
> I knew about it before, but I tried to keep it secret .... cause we all know the Spiderman Theorem

heh ;-) .... I *think* I may have it as well for the jenkins repos, but never tried it.

**Pull request merged**
