### PR TITLE
WIP: Import some functionality from CI demos

### PR DESCRIPTION
**Pull request by mfojtik**
@bparees this will import:

* Pre-install kubernetes, git, promoted-builds, credentials, etc plugins
* Add auto-slave discovery based on image stream labels
* Auto configuration of Kubernetes plugin

Currently **only** for centos7 image, for RHEL7 I have to figure out how to install the plugins ;-)

### CODE REVIEW

**Comment by bparees** [comment]
i'm a little worried about forking the centos vs rhel image behavior.... it's going to lead to a lot of questions and we don't really have the doc in place to support the centos image behavior.

**Comment by mfojtik** [comment]
@bparees agree, we have to find a way to make this work in RHEL7 image

**Comment by mfojtik** [comment]
[extended:core(s2i)]

**Comment by mfojtik** [comment]
Closed in favor of using the S2I approach.

**Pull request closed without merging**
