### PR TITLE
switch master branch to v3.10

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees ptal

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by bparees** [comment]
lgtm.  after this merges and the jenkins push job runs, we should see a v3.10 tag on docker hub, so that's the thing(well, a thing) to check for....

**Comment by gabemontero** [comment]
yep

**Comment by gabemontero** [comment]
[merge]

**Comment by gabemontero** [comment]
ok I'm monitoring https://hub.docker.com/r/openshift/jenkins-2-centos7/tags/ and the push_jenkins_images job ... I'll report back with results when the next push_jenkins_images run succeeds.

**Pull request merged**
