### PR TITLE
various new launcher related fixes; add verifyService to client plugin

### PR DESCRIPTION
**Pull request by gabemontero**

### CODE REVIEW

**Comment by gabemontero** [comment]
Hmm ... got a `No package dumb-init available.` on the rhel build .... short term hiccup or something has changed in rhel repo land?

Let's try again and see

**Comment by gabemontero** [comment]
dumb-init on rhel does in fact appear to be broken

will have to try and track down what is going on .... might have to provision a rhel instance and try it manually ... perhaps it moved repos ... perhaps another motivator for getting rid of our rhel build on aos-cd-jobs @bparees 

jenkins is the gift that keeps on giving

**Comment by gabemontero** [comment]
OK I just provisioned a rhel instance based on our ami's via `oct` and am seeing the same thing, that `dumb-init` is no longer available with the set of repo's set up there.

I do see the existence of the rpm in the fedora/centos/rhel space in some sense ... see https://rpms.remirepo.net/rpmphp/zoom.php?rpm=dumb-init

@bparees - this feels like we've been caught up in the transition in our ci, with the ami's etc. getting more and more stale / unsupported, and differing all the new rpm/mirroring/etc. stuff happening with our prow stuff ... do you agree?

And if so, as we discussed yesterday, it is time to rip our rhel tests out.

Or do we need the pursue what is up with our ami's etc. and possibly the rhel repos referenced by them and try to find out what happened?

**Comment by gabemontero** [comment]
I do have an aos-cd-jobs commit/branch ready to turn into a PR to remove building the jenkins rhel image if we want @bparees

**Comment by gabemontero** [comment]
Also I am running a centos build locally to see if it can still find dumb init since the rhel failure prevents out test job from trying out centos

Granted not an entirely apples to apples comparison, but hopefully a good warm fuzzy check.

**Comment by gabemontero** [comment]
centos build finding dumb-init at https://copr-be.cloud.fedoraproject.org/results/alsadi/dumb-init/

**Comment by bparees** [comment]
yes, rip them out

**Comment by gabemontero** [comment]
ok job updated to just do centos

**Comment by gabemontero** [comment]
Installed plugins:
```
ace-editor:1.0.1
apache-httpcomponents-client-4-api:4.5.5-2.0
authentication-tokens:1.1
blueocean-autofavorite:1.2.0
blueocean-bitbucket-pipeline:1.4.1
blueocean-commons:1.4.1
blueocean-config:1.4.1
blueocean-core-js:1.4.1
blueocean-dashboard:1.4.1
blueocean-display-url:2.1.1
blueocean-events:1.4.1
blueocean-github-pipeline:1.4.1
blueocean-git-pipeline:1.4.1
blueocean-i18n:1.4.1
blueocean-jira:1.4.1
blueocean:1.4.1
blueocean-jwt:1.4.1
blueocean-personalization:1.4.1
blueocean-pipeline-api-impl:1.4.1
blueocean-pipeline-editor:1.4.1
blueocean-pipeline-scm-api:1.4.1
blueocean-rest-impl:1.4.1
blueocean-rest:1.4.1
blueocean-web:1.4.1
branch-api:2.0.11
cloudbees-bitbucket-branch-source:2.2.5
cloudbees-folder:6.1.2
conditional-buildstep:1.3.1
config-file-provider:3.2
credentials-binding:1.15
credentials:2.1.17
display-url-api:2.1.0
docker-commons:1.11
docker-workflow:1.9
durable-task:1.16
favorite:2.3.1
git-client:2.7.0
github-api:1.90
github-branch-source:2.3.6
github:1.29.2
github-organization-folder:1.6
git:3.9.1
git-server:1.5
handlebars:1.1
htmlpublisher:1.16
jackson2-api:2.8.11.2
jenkins-design-language:1.4.1
jira:3.0.2
job-dsl:1.70
jquery-detached:1.2.1
jsch:0.1.54.1
junit:1.26.1
kubernetes-credentials:0.3.0
kubernetes:1.12.1
lockable-resources:2.3
mailer:1.21
mapdb-api:1.0.9.0
matrix-auth:2.2
matrix-project:1.12
mercurial:2.3
momentjs:1.1
openshift-client:1.0.20
openshift-login:1.0.9
openshift-pipeline:1.0.55
openshift-sync:1.0.29
parameterized-trigger:2.35.2
pipeline-build-step:2.7
pipeline-github-lib:1.0
pipeline-graph-analysis:1.6
pipeline-input-step:2.8
pipeline-milestone-step:1.3.1
pipeline-model-api:1.2.5
pipeline-model-declarative-agent:1.1.1
pipeline-model-definition:1.2.5
pipeline-model-extensions:1.2.5
pipeline-rest-api:2.9
pipeline-stage-step:2.2
pipeline-stage-tags-metadata:1.2.5
pipeline-stage-view:2.4
pipeline-utility-steps:1.5.1
plain-credentials:1.3
pubsub-light:1.12
run-condition:0.10
scm-api:2.2.6
script-security:1.41
sse-gateway:1.15
ssh-credentials:1.14
structs:1.13
subversion:2.10.3
token-macro:2.0
variant:1.1
workflow-aggregator:2.5
workflow-api:2.25
workflow-basic-steps:2.3
workflow-cps-global-lib:2.7
workflow-cps:2.42
workflow-durable-task-step:2.18
workflow-job:2.14.1
workflow-multibranch:2.16
workflow-remote-loader:1.4
workflow-scm-step:2.4
workflow-step-api:2.14
workflow-support:2.18
```

**Comment by gabemontero** [comment]
plugin rhel rpm job:  https://buildvm.openshift.eng.bos.redhat.com:8443/job/devex/job/devex%252Fjenkins-plugins/68/

**Comment by gabemontero** [comment]
jenkins update center hiccup ... now https://buildvm.openshift.eng.bos.redhat.com:8443/job/devex/job/devex%252Fjenkins-plugins/69/

**Comment by gabemontero** [comment]
again hiccup on the jenkins update center ... very choppy from the browser too ... will wait until it seems more stable before resubmitting

**Comment by gabemontero** [comment]
core job clean again @bparees 

keeping an eye on the push job

**Comment by gabemontero** [comment]
Initiated a push job ... blanks for all the params ... failed with:

```
+ docker run -e JOB_SPEC= -v /data:/data:z registry.svc.ci.openshift.org/ci/initupload:latest --clone-log=/data/clone.json --dry-run=false --gcs-path=gs://origin-ci-test --gcs-credentials-file=/data/credentials.json --path-strategy=single --default-org=openshift --default-repo=origin
{"component":"initupload","error":"could not resolve job spec: malformed $JOB_SPEC: unexpected end of JSON input","level":"fatal","msg":"Failed to initialize job","time":"2018-10-10T20:30:03Z"}
++ export status=FAILURE
```

Will look at last successful job, try to reverse engineer

**Comment by gabemontero** [comment]
OK way too complicated ... going to wait for a merge, see what happens

**Comment by gabemontero** [comment]
ok jenkins upd center calmed down .... https://buildvm.openshift.eng.bos.redhat.com:8443/job/devex/job/devex%252Fjenkins-plugins/70/ did the trick

**Comment by gabemontero** [comment]
let's see if all the ci-operator stuff has been updated

**Comment by gabemontero** [comment]
I was able to inject the config map with the new template into api.ci, but the presubmits are mkpj type stuff I believe, and I don't *think* those updates are there yet ... 

still have `Running in parallel across 30 nodes`

So most like will be too constrained, but we'll see 

I'll tap DPTP folks Thursday AM as needed to make sure all openshift/release updates are there

**Comment by bparees** [comment]
> but the presubmits are mkpj type stuff I believe, and I don't think those updates are there yet ...

mkpj?

in my experience merging the change to pre-submit and seeing the bot comment was sufficient for the changes to take effect on the next job run.

**Comment by gabemontero** [comment]
@bparees so @stevekuznetsov did note there was an hiccup with the prow yaml update (which was my suspicion ... I may have been off on how that happens, but I think it is a mkpj invocation once the PR merges)

but he also found a spot in the plugins.yaml that I needed to change .... https://github.com/openshift/release/pull/1893

**Comment by gabemontero** [comment]
@bparees tide seems to be busted and got no response on forum-testplatform ... all the tests passed this AM but no merge ... can you hit the green button?

Aside from getting this change in, I want to see how the updated push jenkins job does on PR merge.

**Pull request merged**
