### PR TITLE
Bug 2058747: Update base-plugins.txt

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by coreydaley** [comment]
Manual backport of #1416

**Comment by gabemontero** [comment]
installed plugins list from https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_jenkins/1424/pull-ci-openshift-jenkins-openshift-3.11-images/1514279998775627776 for ART request @coreydaley 

```
2022-04-13T16:38:57.856716213Z Installed plugins:
2022-04-13T16:38:57.864711933Z ace-editor:1.1
2022-04-13T16:38:57.871436356Z ant:1.11
2022-04-13T16:38:57.878129576Z apache-httpcomponents-client-4-api:4.5.13-1.0
2022-04-13T16:38:57.884968095Z authentication-tokens:1.4
2022-04-13T16:38:57.891355345Z blueocean-autofavorite:1.2.3
2022-04-13T16:38:57.898149233Z blueocean-bitbucket-pipeline:1.24.4
2022-04-13T16:38:57.904587760Z blueocean-commons:1.24.4
2022-04-13T16:38:57.910929880Z blueocean-config:1.24.4
2022-04-13T16:38:57.917333111Z blueocean-core-js:1.24.4
2022-04-13T16:38:57.924044555Z blueocean-dashboard:1.24.4
2022-04-13T16:38:57.930840831Z blueocean-display-url:2.2.0
2022-04-13T16:38:57.937329939Z blueocean-events:1.24.4
2022-04-13T16:38:57.943723220Z blueocean-github-pipeline:1.24.4
2022-04-13T16:38:57.950543743Z blueocean-git-pipeline:1.24.4
2022-04-13T16:38:57.957236192Z blueocean-i18n:1.24.4
2022-04-13T16:38:57.963885548Z blueocean:1.24.4
2022-04-13T16:38:57.970444204Z blueocean-jwt:1.24.4
2022-04-13T16:38:57.977514143Z blueocean-personalization:1.24.4
2022-04-13T16:38:57.984305408Z blueocean-pipeline-api-impl:1.24.4
2022-04-13T16:38:57.990847735Z blueocean-pipeline-editor:1.24.4
2022-04-13T16:38:57.997239638Z blueocean-pipeline-scm-api:1.24.4
2022-04-13T16:38:58.003614012Z blueocean-rest-impl:1.24.4
2022-04-13T16:38:58.010041962Z blueocean-rest:1.24.4
2022-04-13T16:38:58.016569837Z blueocean-web:1.24.4
2022-04-13T16:38:58.023035952Z bouncycastle-api:2.18
2022-04-13T16:38:58.029359435Z branch-api:2.7.0
2022-04-13T16:38:58.035864282Z caffeine-api:2.9.1-23.v51c4e2c879c8
2022-04-13T16:38:58.042837562Z cloudbees-bitbucket-branch-source:2.4.4
2022-04-13T16:38:58.049449799Z cloudbees-folder:6.16
2022-04-13T16:38:58.055983334Z conditional-buildstep:1.3.1
2022-04-13T16:38:58.062759814Z config-file-provider:3.7.1
2022-04-13T16:38:58.069466668Z configuration-as-code-groovy:1.1
2022-04-13T16:38:58.076337583Z configuration-as-code:1.51
2022-04-13T16:38:58.083313424Z credentials-binding:1.23
2022-04-13T16:38:58.089775862Z credentials:2.6.1
2022-04-13T16:38:58.096287029Z display-url-api:2.3.4
2022-04-13T16:38:58.102584353Z docker-commons:1.18
2022-04-13T16:38:58.109131614Z docker-workflow:1.23
2022-04-13T16:38:58.115804746Z durable-task:1.35
2022-04-13T16:38:58.122399071Z echarts-api:4.7.0-4
2022-04-13T16:38:58.129207120Z favorite:2.3.1
2022-04-13T16:38:58.135757247Z git-client:3.7.1
2022-04-13T16:38:58.142328602Z github-api:1.114.2
2022-04-13T16:38:58.148651293Z github-branch-source:2.6.0
2022-04-13T16:38:58.155222846Z github:1.33.1
2022-04-13T16:38:58.161815787Z git:4.7.2
2022-04-13T16:38:58.168271519Z git-server:1.10
2022-04-13T16:38:58.174976651Z google-oauth-plugin:1.0.0
2022-04-13T16:38:58.182031407Z groovy:2.2
2022-04-13T16:38:58.188986804Z handlebars:1.1
2022-04-13T16:38:58.195682857Z handy-uri-templates-2-api:2.1.6-1.0
2022-04-13T16:38:58.202325430Z htmlpublisher:1.21
2022-04-13T16:38:58.208836414Z jackson2-api:2.12.2
2022-04-13T16:38:58.215395143Z jenkins-design-language:1.24.4
2022-04-13T16:38:58.221942861Z jira:3.0.17
2022-04-13T16:38:58.228392611Z job-dsl:1.77
2022-04-13T16:38:58.234726627Z jquery3-api:3.5.1-1
2022-04-13T16:38:58.241595168Z jquery-detached:1.2.1
2022-04-13T16:38:58.247863994Z jsch:0.1.55.2
2022-04-13T16:38:58.254292032Z junit:1.30
2022-04-13T16:38:58.260862006Z kubernetes-client-api:4.13.3-1
2022-04-13T16:38:58.267857644Z kubernetes-credentials:0.8.0
2022-04-13T16:38:58.274629223Z kubernetes:1.29.7
2022-04-13T16:38:58.281468742Z lockable-resources:2.10
2022-04-13T16:38:58.288281558Z mailer:1.34
2022-04-13T16:38:58.294668512Z mapdb-api:1.0.9.0
2022-04-13T16:38:58.301431677Z matrix-auth:2.6.6
2022-04-13T16:38:58.307794644Z matrix-project:1.18
2022-04-13T16:38:58.314280967Z mercurial:2.12
2022-04-13T16:38:58.320754053Z metrics:4.0.2.7
2022-04-13T16:38:58.327081469Z momentjs:1.1
2022-04-13T16:38:58.333573545Z oauth-credentials:0.3
2022-04-13T16:38:58.340196736Z okhttp-api:3.12.12.2
2022-04-13T16:38:58.346550829Z openshift-client:1.0.35
2022-04-13T16:38:58.353064802Z openshift-login:1.0.26
2022-04-13T16:38:58.359412888Z openshift-pipeline:1.0.57
2022-04-13T16:38:58.366140966Z openshift-sync:1.0.46
2022-04-13T16:38:58.372842648Z pam-auth:1.6
2022-04-13T16:38:58.379790069Z parameterized-trigger:2.39
2022-04-13T16:38:58.386574580Z pipeline-build-step:2.16
2022-04-13T16:38:58.393136996Z pipeline-github-lib:1.0
2022-04-13T16:38:58.399437732Z pipeline-graph-analysis:1.10
2022-04-13T16:38:58.406028609Z pipeline-input-step:2.11
2022-04-13T16:38:58.412598302Z pipeline-milestone-step:1.3.1
2022-04-13T16:38:58.419394170Z pipeline-model-api:1.7.2
2022-04-13T16:38:58.425862146Z pipeline-model-declarative-agent:1.1.1
2022-04-13T16:38:58.432291445Z pipeline-model-definition:1.6.0
2022-04-13T16:38:58.438896138Z pipeline-model-extensions:1.7.2
2022-04-13T16:38:58.445384712Z pipeline-rest-api:2.15
2022-04-13T16:38:58.451971567Z pipeline-stage-step:2.3
2022-04-13T16:38:58.458297257Z pipeline-stage-tags-metadata:1.6.0
2022-04-13T16:38:58.464853106Z pipeline-stage-view:2.10
2022-04-13T16:38:58.471422097Z pipeline-utility-steps:2.12.0
2022-04-13T16:38:58.478587023Z plain-credentials:1.7
2022-04-13T16:38:58.485121150Z plugin-util-api:1.2.2
2022-04-13T16:38:58.491851368Z prometheus:2.0.10
2022-04-13T16:38:58.498108503Z pubsub-light:1.13
2022-04-13T16:38:58.504529289Z run-condition:0.10
2022-04-13T16:38:58.510904243Z scm-api:2.6.5
2022-04-13T16:38:58.517435134Z script-security:1.78
2022-04-13T16:38:58.524224059Z snakeyaml-api:1.29.1
2022-04-13T16:38:58.530638744Z sse-gateway:1.24
2022-04-13T16:38:58.537179959Z ssh-credentials:1.19
2022-04-13T16:38:58.543567498Z sshd:3.0.4
2022-04-13T16:38:58.549935816Z structs:308.v852b473a2b8c
2022-04-13T16:38:58.556123068Z subversion:2.15.1
2022-04-13T16:38:58.562488069Z token-macro:267.vcdaea6462991
2022-04-13T16:38:58.569293286Z trilead-api:1.0.13
2022-04-13T16:38:58.575857381Z variant:1.4
2022-04-13T16:38:58.582623913Z workflow-aggregator:2.6
2022-04-13T16:38:58.589286407Z workflow-api:2.47
2022-04-13T16:38:58.596264380Z workflow-basic-steps:2.18
2022-04-13T16:38:58.602861839Z workflow-cps-global-lib:564.ve62a_4eb_b_e039
2022-04-13T16:38:58.609494293Z workflow-cps:2660.vb_c0412dc4e6d
2022-04-13T16:38:58.615820961Z workflow-durable-task-step:2.35
2022-04-13T16:38:58.622158188Z workflow-job:2.41
2022-04-13T16:38:58.628726628Z workflow-multibranch:711.vdfef37cda_816
2022-04-13T16:38:58.635210062Z workflow-remote-loader:1.5
2022-04-13T16:38:58.641982150Z workflow-scm-step:2.13
2022-04-13T16:38:58.648526638Z workflow-step-api:622.vb_8e7c15b_c95a_
2022-04-13T16:38:58.654847503Z workflow-support:3.6
```

**Comment by gabemontero** [comment]
took a peek at the e2e failure at https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_jenkins/1424/pull-ci-openshift-jenkins-openshift-3.11-e2e-gcp-jenkins/1514279998683353088 @coreydaley 

from what I see, jenkins came up without any issues with the plugins, but its attempts to access the openshift api server in the test env failed with socket timeouts

so IMO these are "environmental" issues

let's try a few retests to see if we can get "lucky" with the 3.11 gcp environment, but if need be, we'll see about overriding e2e-gcp-jenkins and merging this

and finally, with 3.11 about to be totally out of service, I at least don't think we go through the pain of working with test platform to "bolster" the env 

And then we just wait for @jitendar-singh to verify the 3.11 level with the ART changes you'll request and circle back if need be, though again, the plugin startup from the log dumps looked good, and we have the positive 4.x results as well.

@adambkaplan @jitendar-singh FYI

/retest

**Comment by gabemontero** [comment]
Cool we got non constrained run @coreydaley !

Now you can just mimic the ART request like I did in the 4.6 PR so they update the plugin RPM for the official builds

**Comment by coreydaley** [comment]
ART request: https://issues.redhat.com/browse/ART-3975

**Pull request merged**
