### PR TITLE
tweak java settings per jboss tuning script

### PR DESCRIPTION
**Pull request by gabemontero**
java tuning tweaks per recent exchange with jboss folks

@bparees ptal

@openshift/devex fyi

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero please update https://github.com/openshift/jenkins/blob/master/slave-base/contrib/bin/run-jnlp-client too.

**Comment by gabemontero** [comment]
run-jnlp-client updated

**Comment by gabemontero** [comment]
[test]

**Comment by bparees** [comment]
lgtm

**Pull request merged**
