### PR TITLE
pick up recent syn plugin commits

### PR DESCRIPTION
**Pull request by gabemontero**

### CODE REVIEW

**Comment by gabemontero** [comment]
never got to plugin tests:  `FINISHED STAGE: FAILURE: BUILD BASE RHEL IMAGES`

**Comment by gabemontero** [comment]
mirrors still unhealthy ... will try again in a bit

**Comment by gabemontero** [comment]
OK, some findings re: the build rhel problem:

- if you go to mirror.openshift.com/pub/openshift-origin/nightly, you only see a rhel-6 subdir ... do that would explain why we get a 404 for any URLs with a rhel-7 subdir

- that mirror URL with rhel-7 is coming from the /etc/yum.repos.d/openshift-rhel7-dependencies.repo that exists in our aMI

- In my AWS instance that I ramped up April 16th, and had performed successful jenkins rhel image builds with, /etc/yum.repos.d/openshift-rhel7-dependencies.repo also exists

That would imply to me that the mirror changed recently and the rhel-7 content was removed.

**Comment by gabemontero** [comment]
Yep there is an email thread on #aos-cicd that this would appear to fall under

Crafting an aos-cd-jobs PR to remove that file

**Comment by gabemontero** [comment]
With https://github.com/openshift/aos-cd-jobs/pull/1343

no longer complaining about the openshift mirror, but it is complaining about 

`https://mirror.ops.rhcloud.com/enterprise/enterprise-3.1/latest/RH7-RHAOS-3.1/x86_64/os/repodata/repomd.xml`

I'll spin up a new ami(s) and try to hack on this manually until I've removed all presumably failing mirrors.

**Comment by stevekuznetsov** [comment]
@gabemontero see https://github.com/openshift/origin-ci-tool/commit/0121d6b215e92c60fde693e25b86e0a89acf4f9e https://github.com/openshift/origin-ci-tool/commit/b34575b65df3be8e8d3538884ad726f24f038fef

You can add a `yum disablerepo` command to your job for now.

**Comment by gabemontero** [comment]
ok the build base rhel image phase just passed in the current run ...

**Comment by gabemontero** [comment]
well ... onion peeling is the word with this one.

All the rhel images built fine, and did the centos slave base, but the jenkins-2-centos7 image failed getting the dumb-init rpm installed:

```
File contains no section headers.
file: file:///etc/yum.repos.d/alsadi-dumb-init-epel-7.repo, line: 1
'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n'
The command '/bin/sh -c curl https://pkg.jenkins.io/redhat-stable/jenkins.repo -o /etc/yum.repos.d/jenkins.repo &&     rpm --import https://pkg.jenkins.io/redhat-stable/jenkins-ci.org.key &&     yum install -y centos-release-scl-rh &&     curl https://copr.fedorainfracloud.org/coprs/alsadi/dumb-init/repo/epel-7/alsadi-dumb-init-epel-7.repo -o /etc/yum.repos.d/alsadi-dumb-init-epel-7.repo &&     INSTALL_PKGS="dejavu-sans-fonts rsync gettext git tar zip unzip openssl bzip2 dumb-init java-1.8.0-openjdk java-1.8.0-openjdk.i686 java-1.8.0-openjdk-devel java-1.8.0-openjdk-devel.i686 jenkins-2.107.2-1.1" &&     yum -y --setopt=tsflags=nodocs install $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum clean all  &&     localedef -f UTF-8 -i en_US en_US.UTF-8' returned a non-zero code: 1
make: *** [build] Error 1
```

*Feels* like a yum flake ... that is not a repo file that is part of our ami.  We are past that it would seem.

Running a few sanity checks locally, and pending no surprises, will retest again.

**Comment by gabemontero** [comment]
I was getting cached content on my fedora laptop.  After a `sudo dnf clean all`, I see the problem there as well.

And while I see rpms at https://copr-be.cloud.fedoraproject.org/results/alsadi/dumb-init/epel-7-x86_64/00448255-dumb-init/

The file https://copr.fedorainfracloud.org/coprs/alsadi/dumb-init/repo/epel-7/alsadi-dumb-init-epel-7.repo that our dockerfile tries to download does not exist.

Our rhel image build does not have download that repo file to install dumb-init.  But the centos image build does not find the dumb-init rpm with the other repo's at its disposal.

**Comment by gabemontero** [comment]
Looks like the whole https://copr.fedorainfracloud.org site is down ... can't find if it is a planned outage but will try again later.

**Comment by gabemontero** [comment]
plugins:

```
ace-editor:1.0.1
apache-httpcomponents-client-4-api:4.5.3-2.0
authentication-tokens:1.1
blueocean-autofavorite:1.2.0
blueocean-bitbucket-pipeline:1.4.1
blueocean-commons:1.4.1
blueocean-config:1.4.1
blueocean-core-js:1.4.1
blueocean-dashboard:1.4.1
blueocean-display-url:2.1.1
blueocean-events:1.4.1
blueocean-github-pipeline:1.4.1
blueocean-git-pipeline:1.4.1
blueocean-i18n:1.4.1
blueocean-jira:1.4.1
blueocean:1.4.1
blueocean-jwt:1.4.1
blueocean-personalization:1.4.1
blueocean-pipeline-api-impl:1.4.1
blueocean-pipeline-editor:1.4.1
blueocean-pipeline-scm-api:1.4.1
blueocean-rest-impl:1.4.1
blueocean-rest:1.4.1
blueocean-web:1.4.1
branch-api:2.0.11
cloudbees-bitbucket-branch-source:2.2.5
cloudbees-folder:6.1.2
conditional-buildstep:1.3.1
config-file-provider:2.17
credentials-binding:1.15
credentials:2.1.15
display-url-api:2.1.0
docker-commons:1.11
docker-workflow:1.9
durable-task:1.16
favorite:2.3.1
git-client:2.7.0
github-api:1.86
github-branch-source:2.2.3
github:1.26.0
github-organization-folder:1.6
git:3.8.0
git-server:1.5
handlebars:1.1
htmlpublisher:1.16
jackson2-api:2.7.3
jenkins-design-language:1.4.1
jira:2.4.2
job-dsl:1.68
jquery-detached:1.2.1
jsch:0.1.54.1
junit:1.24
kubernetes-credentials:0.3.0
kubernetes:1.2
mailer:1.21
mapdb-api:1.0.9.0
matrix-auth:2.2
matrix-project:1.12
mercurial:2.3
momentjs:1.1
openshift-client:1.0.12
openshift-login:1.0.8
openshift-pipeline:1.0.54
openshift-sync:1.0.18
parameterized-trigger:2.35.2
pipeline-build-step:2.7
pipeline-github-lib:1.0
pipeline-graph-analysis:1.6
pipeline-input-step:2.8
pipeline-milestone-step:1.3.1
pipeline-model-api:1.2.5
pipeline-model-declarative-agent:1.1.1
pipeline-model-definition:1.2.5
pipeline-model-extensions:1.2.5
pipeline-rest-api:2.9
pipeline-stage-step:2.2
pipeline-stage-tags-metadata:1.2.5
pipeline-stage-view:2.4
pipeline-utility-steps:1.5.1
plain-credentials:1.3
pubsub-light:1.12
run-condition:0.10
scm-api:2.2.6
script-security:1.41
sse-gateway:1.15
ssh-credentials:1.13
structs:1.13
subversion:2.10.3
token-macro:2.0
variant:1.1
workflow-aggregator:2.5
workflow-api:2.25
workflow-basic-steps:2.3
workflow-cps-global-lib:2.7
workflow-cps:2.42
workflow-durable-task-step:2.18
workflow-job:2.14.1
workflow-multibranch:2.16
workflow-remote-loader:1.4
workflow-scm-step:2.4
workflow-step-api:2.14
workflow-support:2.18

```

**Comment by gabemontero** [comment]
rpm job:  https://buildvm.openshift.eng.bos.redhat.com:8443/job/devex/job/devex%252Fjenkins-plugins/46/

**Comment by grdryn** [comment]
@gabemontero that list of plugins that the build outputs is useful! :-) Not sure if I've mentioned it before, but in our downstream repo, we commit that as a file called installed.txt, so that we can see and review the diff in pull requests. Of course, we currently have to keep that updated manually, but it's nice to be able to see the history of the plugin set caused by a particular change (for me, the context of the list (diff of what was added/removed/updated, and when those changes happened) is more useful than the list as a single thing).

Here's our list: https://github.com/feedhenry/wendy-jenkins-s2i-configuration/blob/master/installed.txt
When we rebuild on a new version of your image, or change our own plugins.txt, I'll paste the new list into the file and see exactly which plugins have changed since our old image (including plugins from your layer since our last rebase).

**Comment by gabemontero** [comment]
Cool deal @grdryn !

And thanks for the pointer to your team's image (I've been meaning to ask for while but always forget)

**Pull request merged**
