### PR TITLE
switch 3.6 to 1 plugin rpm a la 3.7 and later

### PR DESCRIPTION
**Pull request by gabemontero**
per discussion with @jupierce and success of https://buildvm.openshift.eng.bos.redhat.com:8443/job/devex/job/devex%252Fjenkins-plugins/21/

@jupierce @bparees ptal

### CODE REVIEW

**Comment by gabemontero** [comment]
Even if change is valid, I'm assuming test/merge will fail until https://github.com/openshift/aos-cd-jobs/pull/998 is sorted out.

@jupierce - if it came to hitting the merge button, would the resulting commit be enough to getting a jenkins-2-rhel7:v3.6 image starting in the errata pipeline?

**Comment by jupierce** [comment]
@gabemontero yes. FYI @adammhaile this will likely be a manual reconcile to distgit until oit manages 3.6.

**Comment by adammhaile** [comment]
@jupierce - ACK. And I've been given go-ahead by @smunilla to start with
3.6, will start working on that after 3.5 build tests wrap.

**Comment by gabemontero** [comment]
Thanks gentlemen - I've hit the merge button.

**Comment by gabemontero** [comment]
@adammhaile @jupierce - hey, any update on the 3.6 conversion here?  Is there another github issue / bugzilla / trello card I should subscribe to for tracking?

thanks

**Comment by jupierce** [comment]
@gabemontero The first 3.6 since this was merged kicked off this morning: https://buildvm.openshift.eng.bos.redhat.com:8443/job/aos-cd-builds/job/build%252Fose/153/console . This run includes a sizable migration to the new oit tooling, so I expect some hiccups, but the next build of 3.6 (email to aos-cicd mailing list) should contain this.

**Comment by gabemontero** [comment]
cool thanks @jupierce

**Pull request merged**
