### PR TITLE
update plugins per Aug 8 sec advisory

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/jenkins/issues/355

@openshift/devex @jupierce @smunilla fyi

The plugin list with this change was:

```
Installed plugins:
ace-editor:1.0.1
authentication-tokens:1.1
blueocean-autofavorite:1.0.0
blueocean-commons:1.1.6
blueocean-config:1.1.6
blueocean-dashboard:1.1.6
blueocean-display-url:2.0
blueocean-events:1.1.6
blueocean-github-pipeline:1.1.6
blueocean-git-pipeline:1.1.6
blueocean-i18n:1.1.6
blueocean:1.1.6
blueocean-jwt:1.1.6
blueocean-personalization:1.1.6
blueocean-pipeline-api-impl:1.1.6
blueocean-pipeline-editor:0.2.0
blueocean-pipeline-scm-api:1.1.6
blueocean-rest-impl:1.1.6
blueocean-rest:1.1.6
blueocean-web:1.1.6
branch-api:2.0.9
cloudbees-folder:6.0.4
conditional-buildstep:1.3.1
config-file-provider:2.16.2
credentials-binding:1.12
credentials:2.1.13
display-url-api:2.0
docker-commons:1.8
docker-workflow:1.9
durable-task:1.13
favorite:2.3.0
git-client:2.4.4
github-api:1.85.1
github-branch-source:2.0.8
github:1.26.0
github-organization-folder:1.6
git:3.3.2
git-server:1.5
handlebars:1.1
icon-shim:2.0.3
jackson2-api:2.7.3
javadoc:1.0
job-dsl:1.60
jquery-detached:1.2.1
junit:1.20
kubernetes:0.10
mailer:1.20
managed-scripts:1.3
mapdb-api:1.0.1.0
matrix-auth:1.5
matrix-project:1.7.1
maven-plugin:2.0
mercurial:1.54
metrics:3.1.2.9
momentjs:1.1
multiple-scms:0.6
openshift-client:0.9.6
openshift-login:0.12
openshift-pipeline:1.0.48
openshift-sync:0.1.27
parameterized-trigger:2.35.1
pipeline-build-step:2.5.1
pipeline-github-lib:1.0
pipeline-graph-analysis:1.3
pipeline-input-step:2.8
pipeline-milestone-step:1.3
pipeline-model-api:1.1.4
pipeline-model-declarative-agent:1.1.1
pipeline-model-definition:1.1.4
pipeline-model-extensions:1.1.4
pipeline-rest-api:2.4
pipeline-stage-step:2.2
pipeline-stage-tags-metadata:1.1.4
pipeline-stage-view:2.4
pipeline-utility-steps:1.1.5
plain-credentials:1.3
project-inheritance:1.5.3
promoted-builds:2.27
pubsub-light:1.8
rebuild:1.22
run-condition:0.10
scm-api:2.1.1
script-security:1.31
sse-gateway:1.15
ssh-credentials:1.13
structs:1.7
subversion:2.9
support-core:2.32
token-macro:2.0
variant:1.1
vsphere-cloud:1.1.11
workflow-aggregator:2.5
workflow-api:2.18
workflow-basic-steps:2.3
workflow-cps-global-lib:2.7
workflow-cps:2.39
workflow-durable-task-step:2.11
workflow-job:2.10
workflow-multibranch:2.14
workflow-remote-loader:1.2
workflow-scm-step:2.4
workflow-step-api:2.10
workflow-support:2.14
```

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by bparees** [comment]
lgtm

**Comment by jupierce** [comment]
This RPM contains the updated plugins: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=13841921 . Once the Jenkins-2 Dockerfile in dist-git is updated to use jenkins-2-plugins, you should be good.

**Comment by gabemontero** [comment]
thanks @jupierce 

[merge]

**Pull request merged**
