### PR TITLE
optimize jvm gc/heap settings for lower memory usage

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero ptal

**Comment by gabemontero** [comment]
Wow, some serious and specific `-XX` usage.  Did it originate from a recommendation from someone, or from GC analysis of note?

**Comment by bparees** [comment]
yeah it was recommendations we got from the JDK team back in the v2 days, but for some reason we didn't carry it forward into v3, see:
https://github.com/openshift/origin-server/blob/master/cartridges/openshift-origin-cartridge-jenkins/bin/control#L50-L58

**Comment by gabemontero** [comment]
i see ... ok, cool ... lgtm

**Pull request merged**
