### PR TITLE
add blueocean to jenkins-2-rhel7 image

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees @smunilla @jupierce correct PR to pull in blueocean to rhel image

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by bparees** [comment]
lgtm

**Comment by bparees** [comment]
but since the 3.6 repos aren't available to our CI job (right?) this is going to fail tests, right?

**Comment by gabemontero** [comment]
I wasn't sure about the first question, so decided to give it a go.

**Comment by gabemontero** [comment]
My PR to add the 3.6 repo into aos-cd-tools merged a few days ago.  Not sure of the AMI status since it merged.

**Comment by bparees** [comment]
this job still uses the vagrant process so it's still using the old vagrant amis, not the new oct amis, as i understand the situation.

**Comment by bparees** [comment]
(also the oct amis haven't been rebuilt in like a week, steve's still working on issues there)

**Comment by gabemontero** [comment]
Ah right.  So yeah, this test will fail and we'll need to not merge this PR until either your switch of the job happens or @dobbymoodge fixes the RHCL ruby per https://github.com/openshift/vagrant-openshift/pull/549#issuecomment-312305604

**Comment by gabemontero** [comment]
assuming oct amis == https://ci.openshift.redhat.com/jenkins/job/ami_build_origin_int_rhel_base/  ... that came up somewhere else recently (just remembered)

**Comment by dobbymoodge** [comment]
re-[test]

**Comment by gabemontero** [comment]
[test]

**Comment by bparees** [comment]
i think it's safe to say we're not going to want to do this for the 3.6.0 release at this point, we'll merge this after we get the 3.6.0 jenkins images out the door.

**Comment by gabemontero** [comment]
On Thu, Jul 6, 2017 at 2:49 PM Ben Parees <notifications@github.com> wrote:

> i think it's safe to say we're not going to want to do this for the 3.6.0
> release at this point, we'll merge this after we get the 3.6.0 jenkins
> images out the door.
>
10-4.  As much as anything I'm just curious on if this passes with your
recent changes along with the recent activity from @smunilla.

**Comment by bparees** [comment]
surprising.  so that would imply we've got all the blueocean plugin rpms at least.

**Comment by gabemontero** [comment]
do we want to revisit this for 3.6 given the release date change?

**Comment by bparees** [comment]
> do we want to revisit this for 3.6 given the release date change?

no, i'm not convinced there's enough regression time at this point, still.

**Comment by gabemontero** [comment]
10-4

**Comment by gabemontero** [comment]
The rhel image's install of blueocean failed in the following manner:

```
SEVERE: Failed Loading plugin Blue Ocean v1.1.2 (blueocean)
java.io.IOException: Blue Ocean v1.1.2 failed to load.
 - REST Implementation for Blue Ocean v1.0.1 is older than required. To fix, install v1.1.2 or later.
 - Git Pipeline for Blue Ocean v1.0.1 is older than required. To fix, install v1.1.2 or later.
 - Config API for Blue Ocean v1.0.1 is older than required. To fix, install v1.1.2 or later.
 - Autofavorite for Blue Ocean v0.7 is older than required. To fix, install v1.0.0 or later.
 - Personalization for Blue Ocean v1.0.1 is older than required. To fix, install v1.1.2 or later.
 - REST API for Blue Ocean v1.0.1 is older than required. To fix, install v1.1.2 or later.
 - i18n for Blue Ocean v1.0.1 is older than required. To fix, install v1.1.2 or later.
 - Events API for Blue Ocean v1.0.1 is older than required. To fix, install v1.1.2 or later.
 - Common API for Blue Ocean v1.0.1 is older than required. To fix, install v1.1.2 or later.
 - Web for Blue Ocean v1.0.1 is older than required. To fix, install v1.1.2 or later.
 - Pipeline REST API for Blue Ocean v1.0.1 is older than required. To fix, install v1.1.2 or later.
 - Dashboard for Blue Ocean v1.0.1 is older than required. To fix, install v1.1.2 or later.
 - JWT for Blue Ocean v1.0.1 is older than required. To fix, install v1.1.2 or later.
 - GitHub Pipeline for Blue Ocean v1.0.1 is older than required. To fix, install v1.1.2 or later.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:621)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:517)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$7.runTask(Jenkins.java:1089)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

```

Looks like we've now got a series of dependency plugin RPM bumps that are needed.  A sanity check against the centos image will probably be in order as well.

Postponing blueocean until after 3.6 validated @bparees :-)

**Comment by bparees** [comment]
@gabemontero @smunilla now that the dust is settling on 3.6, let's see if we can move this forward.. @smunilla I assume step one is for you guys to create the "jenkins plugin bundle rpm" and then start getting the right versions of the plugin deps in there so we can include the blueocean plugin.

**Comment by bparees** [comment]
blueocean is going to be part of the unified plugin rpm that @jupierce just built, so this PR is no longer necessary ( @coreydaley will need to make a new one to switch us to the unified rpm after he finishes vetting it).

**Pull request closed without merging**
