### PR TITLE
update to LTS 2.89.2

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/jenkins/issues/439
fixes https://github.com/openshift/jenkins/issues/445

### CODE REVIEW

**Comment by gabemontero** [comment]
lgtm

**Comment by bparees** [comment]
didn't pick up the new rhel rpm.  discussing with @smunilla

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
> Package jenkins.noarch 0:2.73.3-1.el7 will be installed

still getting 2.73.

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
updated this to use 2.89.2, rhel is picking it up as well.
[merge]

**Pull request merged**
