### PR TITLE
pipeline plugin to v1.0.26, login plugin to v.0.2

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees @csrwng @jupierce @oatmealraisin FYI

To minimize impact on Troy, current thinking is we'll get QE started on feature verification using the centos image, sort through any bugs on centos, then cut the RHEL RPMs / image and have QE do a regression.  They were amenable to that approach in the past.

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by bparees** [comment]
@gabemontero so in theory this could be the finalized oauth-enabled image (for centos) too, right?

**Comment by bparees** [comment]
our jenkins rhel images are failing testing with somewhat alarming frequency, going to need to look into why soon.
[test]

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
gotta a test pass this time .... in the meantime, I found a bug in the test connection fix I submitted yesterday;
I've started a cut v1.0.26 of the plugin.  Once it is available I'll update this PR, the re test and merge if successful.

**Comment by gabemontero** [comment]
v1.0.26 is available...have pushed corresponding update.

[test]

**Comment by gabemontero** [comment]
test passed ... console output confirmed 1.0.26 of pipeline and 0.2 of login plugins installed for centos

merging

**Comment by gabemontero** [comment]
On Fri, Oct 21, 2016 at 11:47 AM, Ben Parees <notifications@github.com>
wrote:

> @gabemontero <https://github.com/gabemontero> so in theory this could be
> the finalized oauth-enabled image (for centos) too, right?
>
Correct

**Pull request merged**
