### PR TITLE
Add .NET Core 2.0 kube-slave config.

### PR DESCRIPTION
**Pull request by jerboaa**
The .NET Core 2.0 jenkins slave image will be delivered to
the Red Hat Container Registry and is maintained upstream
separately in this repository:
https://github.com/redhat-developer/dotnet-jenkins-slave

This patch adds relevant kubernetes slave configuration for
the .NET Core 2.0 jenkins slave image so that jobs can be
scheduled on pods with .NET Core 2.0 installed. Jobs need
to be configured - via restrictions - to only run on nodes
with label expression "dotnet-20".

This PR resolves https://bugzilla.redhat.com/show_bug.cgi?id=1451403

### CODE REVIEW

**Comment by jerboaa** [comment]
@bparees Please have a look. It's my understanding that this is all that's needed on your end. Thanks!

**Comment by bparees** [comment]
this looks fine but we can't merge it until your images actually exist in registry.access.redhat.com, any ETA on that?

**Comment by bparees** [comment]
also there are no plans to do a centos version of the slave?

**Comment by bparees** [comment]
[test]

**Comment by jerboaa** [comment]
@bparees RHEL image delivery to registry.access.redhat.com. No ETA. It'll be soon, though. At some point there will be a centos image for this. It will come as a follow up.

**Comment by bparees** [comment]
@jerboaa ok, can you come back and bump this PR once the rhel images are available, in case i forget about it?

**Comment by jerboaa** [comment]
@bparees sure.

**Comment by jerboaa** [comment]
@bparees The .NET jenkins slave image is now available: https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/dotnet/dotnet-20-jenkins-slave-rhel7

**Comment by bparees** [comment]
@jerboaa awesome, thanks.
[merge]

**Pull request merged**
