### PR TITLE
bump sync to 0.1.14

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees @tdawson FYI

@jim-minter - this will pull into the openshift jenkins centos image the sync plugin change to be more prudent on when bc's are updated

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
@stevekuznetsov sorry, but something happened since the successful test run in the last PR ... there are some ruby NoMethodError's in this test log.

**Comment by stevekuznetsov** [comment]
@gabemontero I sent out another e-mail -- the previous one was a little premature. I'll either fix Rosie this morning or get her out of this repo.

**Comment by gabemontero** [comment]
Ah - gotcha - I misinterpreted the timing between that email and the last successful test run; yeah, just let us know, thanks

**Comment by stevekuznetsov** [comment]
@gabemontero we're back in business baby

**Comment by gabemontero** [comment]
cool deal @stevekuznetsov !

going for broke ..... [merge]

**Pull request merged**
