### PR TITLE
[release-4.13] OCPBUGS-13651: Sync updates from master

### PR DESCRIPTION
**Pull request by coreydaley**
Backport all changes from master branch to release-4.13 with only minimal version dependent changes.

### CODE REVIEW

**Comment by coreydaley** [comment]
/assign @divyansh42 @mbharatk @apoorvajagtap
for lgtm
/label backport-risk-assessed
/label cherry-pick-approved

**Review by divyansh42 — COMMENTED** [review]
/lgtm

**Comment by coreydaley** [comment]
/assign @bparees 
for staff-eng-approved label

**Comment by bparees** [comment]
image is not in the ocp payload in 4.11+, so no reason to hold up the pr

**Pull request merged**
