### PR TITLE
switch rhel images to public base image

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/jenkins/issues/313

### CODE REVIEW

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
(ultimately we want to base on openshift/origin instead, but this is step one and easier)

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
@stevekuznetsov so here's a problem.  since this fast-merged, it didn't run the merge job which means it didn't build/push the new images.  so i either need a way to trigger my push job on a merge, or i need a way to disable fast merge.

**Comment by bparees** [comment]
(building+pushing here for now: https://ci.openshift.redhat.com/jenkins/view/All/job/push_jenkins_images/1/)

**Comment by stevekuznetsov** [comment]
What a tangled web we weave ... I would still suggest doing the (unsavory) thing and making a job in Jenkins that triggers off of `master` updates that has sub-jobs like the push ...

**Pull request merged**
