### PR TITLE
bump login plugin to move off of /oapi endpoints

### PR DESCRIPTION
**Pull request by gabemontero**
/assign @bparees 

in theory when the client plugin bump gets pushed to dockerhub, this PR's test job should pass

let's refrain from green buttoning this one immediately, see what happens

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero not seeing our jenkins image push job getting kicked so far:
https://ci.openshift.redhat.com/jenkins/job/push_jenkins_images/

(supposed to get kicked on merge to the jenkins repo).

**Comment by gabemontero** [comment]
jenkins e2e tests passed @bparees ....don't get a dump of the jobs on success, so can't tell if this picked up the new client plugin or missed the failure timing window

**Comment by gabemontero** [comment]
ok @bparees the `e2e-aws` failure is unrelated to the jenkins image, and `e2e-aws-jenkins` passed

let's green button this one 

then after (manual if need be) push_jenkins_image job updates docker.io, we can retrigger `e2w-aws-build` in @deads2k PR

**Comment by bparees** [comment]
@gabemontero didn't see the job kick immediately so i just launched one:
https://ci.openshift.redhat.com/jenkins//job/push_jenkins_images/276/

**Pull request merged**
