### PR TITLE
⬆ Upgrade Jenkins to latest LTS 2.121.2

### PR DESCRIPTION
**Pull request by grdryn**
https://jenkins.io/security/advisory/2018-07-18/

### CODE REVIEW

**Comment by bparees** [comment]
kicked off new jenkins package.
/lgtm

**Comment by gabemontero** [comment]
cross ref job for enkins rpm bump:  https://buildvm.openshift.eng.bos.redhat.com:8443/job/devex/job/devex%252Fjenkins-bump-version/18/

**Comment by gabemontero** [comment]
@bparees :  fyi, this version is suppose to have our remoting jar fix for NO_PROXY ... I'll verify on Monday

**Comment by gabemontero** [comment]
Confirmed:  remoting version:  

org.jenkins-ci.main:remoting:3.21
--

3.21 contains my change

**Pull request merged**
