### PR TITLE
clean up sample config; use default api endpoint and project

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees PTAL

### CODE REVIEW

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
(lgtm but seems to be hitting some test infrastructure issues)

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[test]

**Comment by gabemontero** [comment]
Yum repos are proving quite obstinate

**Comment by bparees** [comment]
@gabemontero i'm starting to think something more fundamental is going wrong here, can you spin up an AMI and see if you can successfully build/test the centos+rhel images yourself?

**Comment by bparees** [comment]
@gabemontero looks like the issue is this, maybe ping @tdawson about getting updated packages on our mirrors:

```
---> Package rh-nodejs4-nodejs-repeat-string.noarch 0:1.5.2-4.el7 will be installed
--> Finished Dependency Resolution
[91mError: Package: glibc-2.17-106.el7_2.6.i686 (oso-rhui-rhel-server-releases)
           Requires: glibc-common = 2.17-106.el7_2.6
           Installed: glibc-common-2.17-106.el7_2.8.x86_64 (@anaconda/7.2)
               glibc-common = 2.17-106.el7_2.8
           Available: glibc-common-2.17-55.el7.x86_64 (oso-rhui-rhel-server-releases)
               glibc-common = 2.17-55.el7
           Available: glibc-common-2.17-55.el7_0.1.x86_64 (oso-rhui-rhel-server-releases)
               glibc-common = 2.17-55.el7_0.1
           Available: glibc-common-2.17-55.el7_0.3.x86_64 (oso-rhui-rhel-server-releases)
               glibc-common = 2.17-55.el7_0.3
           Available: glibc-common-2.17-55.el7_0.5.x86_64 (oso-rhui-rhel-server-releases)
               glibc-common = 2.17-55.el7_0.5
           Available: glibc-common-2.17-78.el7.x86_64 (oso-rhui-rhel-server-releases)
               glibc-common = 2.17-78.el7
           Available: glibc-common-2.17-105.el7.x86_64 (oso-rhui-rhel-server-releases)
               glibc-common = 2.17-105.el7
           Available: glibc-common-2.17-106.el7_2.1.x86_64 (oso-rhui-rhel-server-releases)
               glibc-common = 2.17-106.el7_2.1
           Available: glibc-common-2.17-106.el7_2.4.x86_64 (oso-rhui-rhel-server-releases)
               glibc-common = 2.17-106.el7_2.4
           Available: glibc-common-2.17-106.el7_2.6.x86_64 (oso-rhui-rhel-server-releases)
               glibc-common = 2.17-106.el7_2.6
[0m You could try using --skip-broken to work around the problem
```

**Comment by gabemontero** [comment]
I built the centos image locally, but sure, I'll spin up an ami and try
both ... I'll update with the results in a bit.

**Comment by bparees** [comment]
yeah it's the rhel one that's failing.

**Comment by gabemontero** [comment]
ok i'll confirm the same thing occurs from my ami and ping @tdawson pending
the results

**Comment by tdawson** [comment]
It looks like what happens when they push out an update (which just happened) but only did the x86_64 and not the i386 packages.  You can see it's trying to install the i386 package, because it matches what is already installed, but then the rest of the glib dependencies fail horribly.

**Comment by gabemontero** [comment]
I believe I got a different error running on a personal AMI:
```
zip_safe flag not set; analyzing archive contents...
websocket._http: module references __file__
websocket.tests.test_websocket: module references __file__
zip_safe flag not set; analyzing archive contents...
error: Setup script exited with error in docker-py setup command: Invalid environment marker: python_version < "3.5"
make: *** [build] Error 1
```

**Comment by gabemontero** [comment]
I did not get the message @bparees posted.

**Comment by bparees** [comment]
@tdawson is there someone we can ping?

**Comment by tdawson** [comment]
@bparees Yes, but I just checked again, and it looks like it's already fixed.  Please try again.

**Comment by bparees** [comment]
[test]

**Comment by gabemontero** [comment]
I realized wrt the error message I posted earlier, the jenkins-1-rhel7 image still got successfully and generated.  Right before the error message I posted, I get `Successfully built 294d9f006715`, where that hash corresponds to the jenkins-1-rhel7 image.  However, none of the new slave images get generated.

**Comment by bparees** [comment]
thanks @tdawson !

**Comment by bparees** [comment]
@gabemontero needs a rebase

**Comment by gabemontero** [comment]
@bparees `git rebase ...` and `git push -f ...` have been executed.

**Pull request merged**
