### PR TITLE
Update install-plugins.sh

### PR DESCRIPTION
**Pull request by ggareth**
This adds an ability to retry downloads of plugins when mirrors are incomplete/returning 404s
This doesn't unfortunately fix when a file only downloads 16mb of a 40mb plugin, but at least reduces some of the errors

This is in reference to #1446

### CODE REVIEW

**Review by ggareth — COMMENTED** [review]
/assign @sbose78

**Comment by coreydaley** [comment]
/hold
The `xmlstarlet` package not being available is a known issue and we are working to resolve it, putting a hold on this pull request until it is fixed, no sense in consuming resources re-running tests that have to chance to pass.

**Comment by coreydaley** [comment]
/assign @akram 
Can you please take a look at this and see if it looks O.K. to you?

**Pull request merged**
