### PR TITLE
bump sync plugin version

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero fyi

@tdawson can you package the 0.15 sync plugin and respin the jenkins rhel images? (no need to do the slave images, just v1 and v2)

**Comment by gabemontero** [comment]
@tdawson @bparees while we are at it, we need updates to openshift-login and openshift-pipeline as well.  v1.0.31 of openshift-pipeline and v0.8 of openshift-login.  The RHEL images on brew pulp are currently at 1.0.28 and 0.6.  

Same caveats about not needing to do the slave images, just v1 and v2.

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[test]

**Comment by gabemontero** [comment]
@bparees @tdawson I just had to cut a new version of openshift-pipeline (v1.0.32) for https://bugzilla.redhat.com/show_bug.cgi?id=1392780

do we want to handle bumping to that with this pull or a separate pull?

If with this pull, I'll update this PR when v1.0.32 is available for download from jenkinsci (should be later today)

**Comment by bparees** [comment]
@gabemontero looks like it's available now, i'll update this PR to pick it up.

**Comment by gabemontero** [comment]
Cool - thx @bparees

**Comment by tdawson** [comment]
rpms built, puddles built

jenkins-plugin-openshift-login-0.8-1.el7
jenkins-plugin-openshift-pipeline-1.0.32-1.el7
jenkins-plugin-openshift-sync-0.0.15-1.el7

Should I wait for this pull request before creating the images?

**Comment by bparees** [comment]
@tdawson nope, shouldn't matter.  you can create the rhel images.

**Comment by gabemontero** [comment]
thx @tdawson

**Comment by tdawson** [comment]
Images created, with this pull request in.

openshift3/jenkins-1-rhel7:1.651.2-29
openshift3/jenkins-2-rhel7:2.7-14

**Pull request merged**
