### PR TITLE
add workflow / fabric related plugins

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees PTAL (though given your PTO certainly wait until next week if you like ;-) )

Note:  technically, I only need the `# Pipeline plugin - https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Plugin` list of plugins for the [new DSL for OpenShift Pipeline Plugin](https://trello.com/c/jOEuMkze/924-5-provide-jenkins-dsl-for-openshift-pipeline-plugin-steps-plug-points), but I went ahead and added the complete list from https://github.com/fabric8io/openshift-jenkins-s2i-config/blob/master/plugins.txt, except for the fact that our image was already pulling in credentials:1.24 (where the plugins.txt from the fabric folks was pulling in credentials:1.22).

@jimmidyson @rawlingsj - FYI

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
Sorry, also minimally need these:
# seem to be missing from the Jenkins docs but required to run these plugins..
structs:1.1
git-client:1.19.0
git-server:1.5
plain-credentials:1.1
ace-editor:1.0.1

But per the PR, including the complete fabric list seems appropriate, but advise if you think otherwise @bparees

**Comment by gabemontero** [comment]
had a yum hiccup ... issuing a re [test]

**Comment by bparees** [comment]
lgtm

**Pull request merged**
