### PR TITLE
Add adambkaplan as approver

### PR DESCRIPTION
**Pull request by adambkaplan**
/assign @gabemontero

### CODE REVIEW

**Comment by gabemontero** [comment]
opened https://github.com/openshift/release/issues/3074 to resolve rpm problem in image job

**Comment by adambkaplan** [comment]
/hold
Jenkins build failing due to rpm mirror issue

**Comment by bparees** [comment]
@gabemontero looks like issues finding dumb-init again:
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_jenkins/817/pull-ci-openshift-jenkins-master-e2e-aws-jenkins/172/

**Comment by gabemontero** [comment]
ok like last time i've opened an openshift/release issue:  https://github.com/openshift/release/issues/3164

/hold

**Comment by bparees** [comment]
> and of course if we are anxious to have this merge, I at least am good with you employing the green button @bparees

not critical to me, i'll let the process play out.  thanks!

**Pull request merged**
