### PR TITLE
update agent config to leverage image reg for agent image refs

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees our slack discussion and your gist turned into a PR

thanks

### CODE REVIEW

**Comment by bparees** [comment]
lgtm.

/hold

until we get the rest of the bits in place, namely the samples operator needs to be installing/creating the agent imagestreams with pullspecs that reference the payload location.

**Comment by gabemontero** [comment]
Going to have to try this manually.  Our e2e which attempts to launch an agent based build where the pod template comes from a labelled imagestream is getting an NPE in the associated sync plugin path:

```
WARNING: Caught: java.lang.NullPointerException
java.lang.NullPointerException
	at io.fabric8.jenkins.openshiftsync.ImageStreamWatcher.eventReceived(ImageStreamWatcher.java:178)
	at io.fabric8.jenkins.openshiftsync.ImageStreamWatcher.eventReceived(ImageStreamWatcher.java:208)
	at io.fabric8.jenkins.openshiftsync.WatcherCallback.eventReceived(WatcherCallback.java:34)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onMessage(WatchConnectionManager.java:237)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:310)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Most likely this is a sample operator agent wiring / this PR's changes type of problem.   Secondary, some NPE protection in the sync plugin if this change could happen naturally from a customer imagestream is probably warranted.

**Comment by gabemontero** [comment]
got things sorted out ... update pushed

**Comment by gabemontero** [comment]
Also I cherrpicked the fix 2.150.2 commit into the branch to aid debug ... presumably the other PR is ahead in the queue

**Comment by bparees** [comment]
plugin install failures.

/retest

**Comment by gabemontero** [comment]
you beat me by 1 second @bparees

**Comment by gabemontero** [comment]
img pull errors on jenkins deployments

/retest

**Pull request merged**
