### PR TITLE
bump container cap to 100

### PR DESCRIPTION
**Pull request by Gl4di4torRr**
@gabemontero opening for #637

### CODE REVIEW

**Comment by gabemontero** [comment]
the test failure is unrelated to your change @Gl4di4torRr 

we've seen this from time to time ...some of our underlying rhel dependencies have changed and introduced some issues running `rpm -V` on the JDK

I'll have to pick a workaround we have and merge before we can merge this.

**Comment by Gl4di4torRr** [comment]
@gabemontero thanks. i was just looking at it.... looked like a flake to me.

**Comment by gabemontero** [comment]
ok the PR for the rpm -V changed merged

**Pull request merged**
