### PR TITLE
updated deps for the following sec advs:

### PR DESCRIPTION
**Pull request by jflowers**
https://jenkins.io/security/advisory/2019-09-12/#SECURITY-1534
https://jenkins.io/security/advisory/2020-03-09/#SECURITY-1723
https://jenkins.io/security/advisory/2019-11-21/#SECURITY-1658
https://jenkins.io/security/advisory/2020-02-12/#SECURITY-1713
https://jenkins.io/security/advisory/2020-03-09/#SECURITY-1754
https://jenkins.io/security/advisory/2020-02-12/#SECURITY-1725
https://jenkins.io/security/advisory/2020-02-12/#SECURITY-1710
https://jenkins.io/security/advisory/2019-11-21/#SECURITY-1106

### CODE REVIEW

**Comment by akram** [comment]
@jflowers  it seems that the e2e tests are not passing; but it looks related to a prometheus issue that probably appeared these days. I will ping the appropriate channels for follow up.

**Comment by akram** [comment]
/test ci/prow/e2e-aws

@jflowers in the meanwhile can you reorder the lines the in file for better follow and easier backport?

**Comment by jflowers** [comment]
@akram yes, I will do that

**Pull request closed without merging**
