### PR TITLE
bump login plugin for bearer token after restart fix

### PR DESCRIPTION
**Pull request by gabemontero**
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1533938

@bparees - figured will update 3.7 as well while we are at it (even though the customer in the bugzilla is at 3.5/3.6)

### CODE REVIEW

**Comment by gabemontero** [comment]
[merge]

**Comment by bparees** [comment]
> @bparees - figured will update 3.7 as well while we are at it (even though the customer in the bugzilla is at 3.5/3.6)

yeah we always have to do that (backport to every release later than the one we're fixing), otherwise the customer could get regressed when they update, if we leave an intermediary release w/o the fix.

**Comment by gabemontero** [comment]
[merge]

**Comment by gabemontero** [comment]
Ah - I missed this before:

```
[ERROR] No approval criteria are configured for 'openshift-3.7' branch of 'jenkins' repo.
Build step 'Execute shell' marked build as failure
```

@bparees do you remember setting up approval criteria for the 3.6 or master branches.  They are not hitting this immediate error out the gate like the 3.7 branch.

The complete job log only contains this:

```
Started by remote host 50.17.198.52
[EnvInject] - Loading node environment variables.
Building in workspace /var/lib/jenkins/jobs/merge_pull_request_jenkins_images/workspace
[WS-CLEANUP] Deleting project workspace...
[workspace] $ /bin/bash /tmp/jenkins6469583837604942961.sh
+ approve.sh jenkins openshift-3.7 none
[ERROR] No approval criteria are configured for 'openshift-3.7' branch of 'jenkins' repo.
Build step 'Execute shell' marked build as failure
[PostBuildScript] - Execution post build scripts.
[workspace] $ /bin/bash /tmp/jenkins330027329380399750.sh
########## STARTING STAGE: DEPROVISION CLOUD RESOURCES ##########
+ [[ -s /var/lib/jenkins/jobs/merge_pull_request_jenkins_images/workspace/activate ]]
+ oct deprovision
/tmp/jenkins330027329380399750.sh: line 3: oct: command not found
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
########## FINISHED STAGE: FAILURE: DEPROVISION CLOUD RESOURCES [00h 00m 00s] ##########
Build step 'Execute a set of scripts' marked build as failure
[PostBuildScript] - Execution post build scripts.
[PostBuildScript] Build is not success : do not execute script
Archiving artifacts
Recording test results
Publish artifacts to S3 Bucket No file(s) found: artifacts/**, .config/origin-ci-tool/**
Publish artifacts to S3 Bucket ‘artifacts/**’ doesn’t match anything, but ‘**’ does. Perhaps that’s what you mean?
[BFA] Scanning build for known causes...
[BFA] Found failure cause(s):
[BFA] Job Stage Failed
[BFA] Done. 0s
[WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] done
Finished: FAILURE
```

**Comment by bparees** [comment]
> @bparees do you remember setting up approval criteria for the 3.6 or master branches. They are not hitting this immediate error out the gate like the 3.7 branch.

I don't/didn't, but @jupierce may have.  @jupierce can we get approvals turned off on our 3.6 branch?  Or on this repository entirely for that matter?

**Comment by gabemontero** [comment]
[merge]

**Pull request merged**
