### PR TITLE
bump to latest k8s plugin

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/jenkins/issues/128

### CODE REVIEW

**Comment by bparees** [comment]
@tnozicka fyi when this goes in you should be able to specify the service account to use as part of the k8s cloud plugin configuration on the manage jenkins page.

**Comment by bparees** [comment]
autoconfiguring it will be slightly more complicated but i'll look into it.

**Comment by tnozicka** [comment]
@bparees I have tested it with our pipelines and here are my findings:

- If you specify only the service account name e.g. "jenkins", it works
- If you want to use namespace+SA name e.g. "myproject:jenkins", it doesn't work
- if you use the full account spec e.g. "system:serviceaccount:myproject:jenkins", it doesn't work

But for us to use it, it has to be pre-configured by default. Using `oc whoami` I am able to get current service account on master and could use it to fill the config template. I will send PR for it next week.

**Comment by bparees** [comment]
@tnozicka thanks.  I think it might be better to configure it from an env variable, and that env variable can be defined in the template that instantiates jenkins.

(the jenkins logic that creates the initial config from a template could consume the env variable in question).

**Pull request merged**
