### PR TITLE
don't override credentials if provided by user

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero ptal

**Comment by gabemontero** [comment]
LGTM

btw, did we do more than just fix the credentials piece, given that the config xml check changed and we lost the "Skipping kubernetes plugin configuration..." message ?

**Comment by bparees** [comment]
yeah i reworked it to just always avoid overwriting specific files, as opposed to the existing logic that would either overwrite all or no files, depending on whether a config.xml was present.  As for the lost message, I didn't feel it was all that critical of a message to have.

**Comment by gabemontero** [comment]
ok cool

**Pull request merged**
