### PR TITLE
JKNS-271 : Adding Test case Ids to ease polarion integration for jenkins

### PR DESCRIPTION
**Pull request by prietyc123**
Github integration with polarion identifies the test cases with unique ids. Introducing IDs for smoke tests.

### CODE REVIEW

**Comment by prietyc123** [comment]
For qe approval

/assign @jitendar-singh

**Comment by jitendar-singh** [comment]
@prietyc123 can you also tag them i.e. automated. As of now we dont have any thing manual but in future we might add feature that need only Manual testing

**Comment by prietyc123** [comment]
> @prietyc123 can you also tag them i.e. automated. As of now we dont have any thing manual but in future we might add feature that need only Manual testing

hmmm, make sense 👍

**Comment by prietyc123** [comment]
/hold

Need to add component/subcomponent label within the test

**Comment by prietyc123** [comment]
@akram According to our 1-1 conversation I have added `customer-scenario` tag for all the scenario. Let me know if I have been mistaken somewhere.

**Comment by prietyc123** [comment]
Removing hold from the pr.

/hold cancel

**Comment by prietyc123** [comment]
```
error: unable to parse image registry.build03.ci.openshift.org/ci-op-z36jtifg/stable@sha256:289bb6e5d42cabfe9cba9ca7ec0818628bebeb65be5f0e4d2aeaebf391a751a0: cannot retrieve image configuration for manifest sha256:289bb6e5d42cabfe9cba9ca7ec0818628bebeb65be5f0e4d2aeaebf391a751a0: received unexpected HTTP status: 500 Internal Server Error
```

/retest

**Comment by akram** [comment]
@prietyc123 that looks good to me...let's see why the tests do not run

/retest
/lgtm

**Comment by prietyc123** [comment]
Tests are failing due to
```error getting cluster version: Get "https://api.ci-op-l5wivskm-93a8f.origin-ci-int-aws.dev.rhcloud.com:6443/apis/config.openshift.io/v1/clusterversions/version": 
dial tcp: lookup api.ci-op-l5wivskm-93a8f.origin-ci-int-aws.dev.rhcloud.com on 172.30.0.10:53: no such host
ClusterID: 
ClusterVersion: Installing "" for <unknown>: <unknown>
error getting cluster operators:
 Get "https://api.ci-op-l5wivskm-93a8f.origin-ci-int-aws.dev.rhcloud.com:6443/apis/config.openshift.io/v1/clusteroperators":
 dial tcp: lookup api.ci-op-l5wivskm-93a8f.origin-ci-int-aws.dev.rhcloud.com on 172.30.0.10:53: no such host
ClusterOperators:
	clusteroperators are missing
Error running must-gather collection:
    <nil>
Falling back to `oc adm inspect clusteroperators.v1.config.openshift.io` to collect basic cluster information.
error running backup collection: 
Get "https://api.ci-op-l5wivskm-93a8f.origin-ci-int-aws.dev.rhcloud.com:6443/api?timeout=32s": 
dial tcp: lookup api.ci-op-l5wivskm-93a8f.origin-ci-int-aws.dev.rhcloud.com on 172.30.0.10:53: no such host
```

**Review by akram — APPROVED** [review]

**Pull request merged**
