### PR TITLE
sync up the base image names and use cli base image explicitly

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero the PR I was thinking of at lunch. I guess i never opened it.

at this point i'd say if it looks ok to you and it passes our new CI structure, it's probably good to merge.

**Comment by gabemontero** [comment]
I’ll have to find the PR that was previously submitted to switch to
origin-ci and remind myself how it failed.

But pending some disconnect then I agree.

**Comment by bparees** [comment]
@gabemontero best thing to do is probably to hold this PR until your samplesoperator changes land to switch the imagestream to point to the payload images.  Once that happens, we can re-test this PR knowing that it will be testing against the PR built image.

/hold

**Comment by bparees** [comment]
this is waiting for https://github.com/openshift/jenkins/pull/775 to merge so we can ensure our PR test jobs are using the just-built agent images.

**Comment by bparees** [comment]
@gabemontero i'll let you lgtm this just in case you have any ordering concerns or checks you want to do, given all the other jenkins churn recently.

**Comment by gabemontero** [comment]
thanks @bparees 

fortunately none of our other in flight or waiting to take off work touches the Dockerfiles

/lgtm

**Pull request merged**
