### PR TITLE
deprecate/stop testing the v1 image

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero ptal
[test]

**Comment by bparees** [comment]
> lgtm ... in addition to the push image job you changed, there is a test job on aos-cd-jobs to change as well, right?

the test job just runs make test, this will cover it.
https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/test_cases/test_branch_jenkins_images.yml#L19-L20

**Comment by bparees** [comment]
[merge]

**Comment by gabemontero** [comment]
On Fri, Aug 11, 2017 at 11:26 AM, Ben Parees <notifications@github.com>
wrote:

> lgtm ... in addition to the push image job you changed, there is a test
> job on aos-cd-jobs to change as well, right?
>
> the test job just runs make test, this will cover it.
> https://github.com/openshift/aos-cd-jobs/blob/master/sjb/
> config/test_cases/test_branch_jenkins_images.yml#L19-L20
>

ah cool thx for info

**Pull request merged**
