### PR TITLE
Need to quote JAVA_GC_ARGS

### PR DESCRIPTION
**Pull request by scoheb**

### CODE REVIEW

**Comment by bparees** [comment]
did you see an issue w/ this?

**Comment by scoheb** [comment]
Not sure you saw my commit message but:

>> otherwise, we get a "/usr/libexec/s2i/run: line 63: [: too many arguments" error

I wanted to override the _-XX:MaxMetaspaceSize=100m_ parameter...and to do that I needed to add the **JAVA_GC_ARGS** . When I added it to the DeploymentConfig, this error appeared. Does not pose a problem for me now since my JAVA_GC_ARGS value made it to the launched process.

**Comment by bparees** [comment]
hm.  the potential error makes sense, though i'm unable to reproduce it in a simple bash script.  Anyway please squash your commits and i'll merge.

**Comment by bparees** [comment]
[merge]

**Pull request merged**
