### PR TITLE
loosen /var/lib/origin permissions for oc

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/jenkins/issues/361

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero @csrwng ptal.  i'm a little concerned this seems to have just broken, any idea if i'm missing something here?

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
(also surprised it didn't break any of our jenkins openshift client plugin testing?)

**Comment by csrwng** [comment]
lgtm

**Comment by bparees** [comment]
well that makes me feel better that it's probably not a regression.
[merge]

**Comment by gabemontero** [comment]
re: the curiosity on previous breakage ...we don't do much if any project creation within our pipelines that I'm aware of ... I thought by default the jenkins SA by default does not have permission to do that anyway ... or I at least seem to remember it being that way at some point

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Pull request merged**
