### PR TITLE
Fix bash syntax errors

### LINKED ISSUE #710: Bash syntax errors
We founds somme syntax errors:

/usr/libexec/s2i/run: line 283: [: missing `]'
/usr/libexec/s2i/run: line 284: : command not found
/usr/libexec/s2i/run: line 383: [: missing `]'
/usr/libexec/s2i/run: line 403: [: missing `]'

### PR DESCRIPTION
**Pull request by mbecca**
fixes #710

### CODE REVIEW

**Comment by gabemontero** [comment]
a bit curious on why this only fails sometimes, as this is in the main path and so is part of everyone's startup of the jenkins image

@bparees @mbecca any thoughts?

**Comment by bparees** [comment]
i suspect this only fails when run with /bin/sh, not /bin/bash, or some other nuance.

**Comment by gabemontero** [comment]
thanks @bparees 

and thanks @mbecca

**Pull request merged**
