### PR TITLE
bump sync plugin; small fixes, 1st post 3.6 feature req

### PR DESCRIPTION
**Pull request by gabemontero**
@openshift/devex fyi

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
tst failure was flake https://github.com/openshift/jenkins/issues/348

[test]

**Comment by gabemontero** [comment]
more flake https://github.com/openshift/jenkins/issues/348

[test]

**Comment by gabemontero** [comment]
rpm downloading packages timed out ... basically flake https://github.com/openshift/jenkins/issues/348 again

[test]

**Comment by gabemontero** [comment]
bump @bparees - shall we merge ?

**Comment by bparees** [comment]
[merge]

**Pull request merged**
