### PR TITLE
fix -z option in $JAVA_GC_OPTS condition

### PR DESCRIPTION
**Pull request by h-sano**

### CODE REVIEW

**Comment by h-sano** [comment]
fix -z option in $JAVA_GC_OPTS condition

**Comment by bparees** [comment]
@h-sano thanks, looks like there are a few other spots w/ this problem too, can you fix them all?
(run-jnlp-client and the v2 run script)

**Comment by h-sano** [comment]
fix this problem in run-jnlp-client and the v2 run script.

**Comment by bparees** [comment]
[test]

**Pull request merged**
