### PR TITLE
still link plugins in Dockerfile so plugins available to s2i assemble…

### PR DESCRIPTION
**Pull request by gabemontero**
… script in extension scenario

@bparees the 3.7 version for https://github.com/openshift/jenkins/pull/453

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by bparees** [comment]
lgtm

**Comment by gabemontero** [comment]
[merge]

**Comment by bparees** [comment]
merge is broken on this branch, need @jupierce or @stevekuznetsov to turn off gating.

manually merging since it passed tests.

**Comment by gabemontero** [comment]
deprovision cloud issue on merge attempt ...trying again

**Comment by gabemontero** [comment]
ah .. never mind my window refreshed :-)

**Comment by gabemontero** [comment]
ok, so @jupierce explained to me on #aos-cd-team that release.access should get updated with the new version of the image based on this pull when the next errata is release.  That occurs on a 3 week cycle.

We pinged @adammhaile on #aos-cd-team to get a feel for when the next update should occur.  Between there or me mentioning him here, when we get a response we can update upstream users as needed.

**Comment by gabemontero** [comment]
OK, we should see registry.access updated on Jan 18 ... the version will be something greater than 3.7.14-5, but the precise number is variable based on how many internal iterations are required to pass verification.

**Pull request merged**
