### PR TITLE
add blueocean to v2 rhel image

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees @jupierce @smunilla FYI ... again, per recent email thread

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
I'll rebase once https://github.com/openshift/jenkins/pull/326 merges

**Comment by bparees** [comment]
lgtm (once you rebase)

**Comment by gabemontero** [comment]
wait a sec ... they are different files :-) .... this PR updates 2/Dockerfile.rhel7, the other PR 1/Dockefile.rhel7 

no rebase needed

**Comment by bparees** [comment]
well you're going to merge-conflict w/ yourself but hopefully git will recognize it's not actually a conflict.

**Comment by bparees** [comment]
(not sure why the v1 change is even in this pr)

**Comment by gabemontero** [comment]
I'm a bit confused by that as well .... I initiated the PR from my rhel ami instance (vs. my laptop) ... not a common occurrence for me.  Perhaps something unexpected happened.

I'm going to close this guy out and recreate via a PR from my laptop.

**Pull request closed without merging**
