### PR TITLE
bump login to 1.0.15 for 2.150.2 fix

### PR DESCRIPTION
**Pull request by gabemontero**

### CODE REVIEW

**Comment by bparees** [comment]
/lgtm

*now* we get to test publishing :)

**Comment by gabemontero** [comment]
terraform vpc pain on the last e2e-aws run

**Comment by gabemontero** [comment]
vpc flakes

announce-testplatform says github api usage is ok again

/retest

**Comment by gabemontero** [comment]
dist git http://pkgs.devel.redhat.com/cgit/rpms/jenkins-2-plugins/commit/?h=rhaos-4.0-rhel-7&id=d0763b187399563a55271668b67489030afe0b91

**Comment by bparees** [comment]
@gabemontero once again the ci push job (the old docker.io one) did not get kicked by this, yet it seems to have been kicked for the 3.11 branch.  I don't get it, but i'm also not sure we care anymore since 4.0+ will be put on quay via the ci-operator image publishing flow.

quay.io/openshift/origin-jenkins is showing the 1.015 login plugin, so things seem to have worked on that front.

i'm inclined to delete the 4.0 tag from docker.io and declare 3.11 will be the last centos image published to docker.io.

**Comment by gabemontero** [comment]
I'm good with that @bparees

**Pull request merged**
