### PR TITLE
[WIP] Move bash tests to go

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by jim-minter** [comment]
@gabemontero @bparees I think it'd be good to extend the test coverage of our Jenkins images, and I think we'd be better off not doing it in bash.  I've had a crack at moving the bash tests into Go - wdyt?

**Comment by coreydaley** [comment]
@jim-minter Did you write a script to translate the bash tests into go or ??

**Comment by jim-minter** [comment]
> @jim-minter Did you write a script to translate the bash tests into go or ??

@coreydaley I wish!  By steam.

**Comment by jim-minter** [comment]
[test]

**Comment by bparees** [comment]
no particular objections here.  I don't think this takes us particularly closer to running the origin extended tests, however.  That's more about buildling+standing up an origin cluster.  

(and on that topic, now that we have numerous non-origin repos (image-registry, webconsole, jenkins) we need to get serious about a CI flow that ensures changes in any one repo are run against tests from the other repos in some sane way.  I think that's a good discussion to have w/ the CI team before we one-off a solution for this repo)

**Comment by jim-minter** [comment]
@gabemontero 

> one big item on my wish list has been being able to execute the openshift extended tests from this repo

or at least, be able to run tests defined in this repo on an OpenShift instance?

> short term planning thought: with the dev sprints for 3.9 about to end, my initial inclination is to minimally hold this until we cut the 3.9 branch

it's only test changes, and I'd like to build on them.  If it's going to complicate the release of 3.9, so be it, but otherwise I wouldn't mind avoiding a huge delay.

> immediate comment: the jenkins 1 image is deprecated / no longer under development; you could avoid changes under the "1" directory.

agreed, I can take the changes out if appropriate but it was little effort to maintain consistency.  I wasn't planning on investing time in enhancing the jenkins 1 tests.

**Comment by gabemontero** [comment]
On Wed, Jan 17, 2018 at 10:16 AM, Jim Minter <notifications@github.com>
wrote:

> @gabemontero <https://github.com/gabemontero>
>
> one big item on my wish list has been being able to execute the openshift
> extended tests from this repo
>
> or at least, be able to run tests defined in this repo on an OpenShift
> instance?
>
Yep that would help wrt running our plugin extended tests, though the
implication being duplicating tests in openshift/origin here.  Obviously
not ideal in the generic "duplication is not ideal" sense.

And @bparees 's note around a generic solution for non-origin repos,
working with the CI/CD team is certainly pertinent and will need to be
factored into
ultimately pulling the trigger here.

short term planning thought: with the dev sprints for 3.9 about to end, my
> initial inclination is to minimally hold this until we cut the 3.9 branch
>
> it's only test changes, and I'd like to build on them. If it's going to
> complicate the release of 3.9, so be it, but otherwise I wouldn't mind
> avoiding a huge delay.
>
OK let's just check point when you think it is warranted to remove the do
not merge label.

> immediate comment: the jenkins 1 image is deprecated / no longer under
> development; you could avoid changes under the "1" directory.
>
> agreed, I can take the changes out if appropriate but it was little effort
> to maintain consistency. I wasn't planning on investing time in enhancing
> the jenkins 1 tests.
>
Yeah take out the version 1 changes then.  Among other things, it will help
having the current bash based version of tests readily available in the
repo (vs. having to hunt through
git history) for potential compares in the future.

**Comment by gabemontero** [comment]
ok started due diligence thorough scan

**Comment by gabemontero** [comment]
ok translating between bash and golang made my head hurt a little ;-)
but to be fair it was already fragile from my recent groovy within jenkins pipeline excursion

let's merge

and sure we'll leave the v1 change in

**Comment by gabemontero** [comment]
unless you had any last minute items beforehand @jim-minter ?

oh, and we'll not squash the commits so as to have the vendor changes pollute the test change

**Comment by jim-minter** [comment]
cool, please hit merge :)

**Comment by gabemontero** [comment]
[merge]

**Comment by arnaud-deprez** [comment]
Hi guys, 

I'm wondering with these changes from batch tests to golang test, how does it affect the source-to-image process and especially the test phase in Openshift ?

As far as I know, jenkins master and slaves were s2i images and one of the requirements is to have a test/run script to execute during source to image build https://docs.openshift.com/container-platform/3.9/creating_images/s2i_testing.html#testing-requirements.

So now that you removed that script, what should I understand ?
- Tests are not executed during your s2i build anymore ? Maybe no s2i build tests are run for these images at all ?
- Or source 2 image supports golang test now ? In this case, the doc should be updated I guess.

**Comment by bparees** [comment]
> I'm wondering with these changes from batch tests to golang test, how does it affect the source-to-image process and especially the test phase in Openshift ?

it doesn't.  there is no "test phase in openshift".

> As far as I know, jenkins master and slaves were s2i images

master is, slaves never were.

> So now that you removed that script, what should I understand ?

Nothing has changed.   We just invoke a go binary instead of a shell script.

There was nothing magical about "test/run" it was just a common place to put a test script.  The docs are overly ambitious in calling it a requirement to have one.

> Tests are not executed during your s2i build anymore ? Maybe no s2i build tests are run for these images at all ?

During what build?  When we build this repo(to produce a new jenkins image), we run the tests that were introduced by this PR (converted from bash) to ensure the new image is correct.

When you use our jenkins image as the base image for an s2i build (either via openshift or via the s2i CLI), no tests are executed, no tests are ever executed for any s2i build, it's not part of what s2i does.  `test/run` is irrelevant to that operation.

> Or source 2 image supports golang test now ? In this case, the doc should be updated I guess.

s2i never had any built in testing feature.  it was always up to image authors to write test logic (in whatever language they chose) to exercise their image before publishing a new version of it for end users.  `test/run` was just a minimal recommendation/example as an easy way to do it.

**Comment by arnaud-deprez** [comment]
@bparees maybe I wasn't clear enough. I know source 2 image has no built in test support but the openshift-sti-builder image has.

But from your reply, I understand that you've never tested these images with the openshift-sti-builder. Am I right ?

**Comment by bparees** [comment]
> But from your reply, I understand that you've never tested these images with the openshift-sti-builder. Am I right ?

we test it w/ the s2i cli, which is effectively equivalent.  i'm not sure if we have automated tests that use it with the openshift s2i builder strategy.  Such testing would be redundant if it existed.

**Comment by arnaud-deprez** [comment]
understood :-)
Thank you!

**Pull request merged**
