### PR TITLE
⬆ Upgrade Jenkins to latest LTS 2.121.1

### PR DESCRIPTION
**Pull request by grdryn**

### CODE REVIEW

**Comment by bparees** [comment]
built the rhel rpm.  let's see if it gets picked up.

/retest

**Comment by bparees** [comment]
rhel job did not pick up the new jenkins rpm:
Installing : jenkins-2.107.3.1525883128-1.el7.noarch                     8/75 

@adammhaile are you the one i need to talk to to understand why we might not be picking up the new jenkins rpm that i just built?

**Comment by adammhaile** [comment]
@bparees That build of jenkins-2 is only tagged for 3.11 -> https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=708443
So it won't make it into the yum repos for 3.10 and since we haven't cut a 3.10 branch yet, 3.11 isn't really valid yet.

**Comment by bparees** [comment]
> So it won't make it into the yum repos for 3.10 and since we haven't cut a 3.10 branch yet, 3.11 isn't really valid yet.

ok.  The intent was definitely to do it for 3.11 and not 3.10.  I thought that cut-over was already done for the jenkins repo (We have a 3.10 release branch now and the master branch represents 3.11 for us).

Sounds like we may have to wait for the rest of openshift to catch up though.

**Comment by gabemontero** [comment]
On Mon, Jun 11, 2018 at 1:53 PM, Ben Parees <notifications@github.com>
wrote:

> So it won't make it into the yum repos for 3.10 and since we haven't cut a
> 3.10 branch yet, 3.11 isn't really valid yet.
>
> ok. The intent was definitely to do it for 3.11 and not 3.10. I thought
> that cut-over was already done for the jenkins repo (We have a 3.10 release
> branch now and the master branch represents 3.11 for us).
>
Yeah us cutting the 3.10 branch in openshift/jenkins does not immediately
translate to to the dist git related jobs for building the plugin RPM and
updating jenkins core being able to build 3.11 content.  It still had not
been done when I left for PTO.

**Comment by bparees** [comment]
/retest
see if it picks up the new rpm now

**Comment by grdryn** [comment]
I have just rebased this branch since there are some (non-conflicting) changes on master since I opened it. I'm not sure if that's useful or not, but at least it shouldn't be harmful. :)

**Comment by bparees** [comment]
> I have just rebased this branch since there are some (non-conflicting) changes on master since I opened it. I'm not sure if that's useful or not, but at least it shouldn't be harmful. :)

yeah probably not needed, but appreciated :)  fyi we're blocked on this pending some internal CI work that needs to be done and then we'll get it merged, sorry for the delay and thanks for your patience.

**Comment by grdryn** [comment]
Periodic bump :)

**Comment by bparees** [comment]
@grdryn cute :)

believe it or not, this is still on our radar and we are still awaiting official 3.11 builds before we can merge it.

**Comment by grdryn** [comment]
@bparees thanks for the update, just making sure it wasn't forgotten :)

**Pull request merged**
