### PR TITLE
Removed ability to grab Image Streams at startup

### PR DESCRIPTION
**Pull request by gabemontero**
This feature will be moved to the OpenShift Sync Plugin.

rebase of https://github.com/openshift/jenkins/pull/289

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by bparees** [comment]
lgtm after the sync plugin is updated in the image of course.

**Comment by bparees** [comment]
(might make sense to just include the sync plugin version bump in this PR)

**Comment by gabemontero** [comment]
On Sun, Jun 11, 2017 at 9:11 PM Ben Parees <notifications@github.com> wrote:

> (might make sense to just include the sync plugin version bump in this PR)
>
The sync plugin version bump all the way to the image getting pushed to
docker hub happened prior to this PR's creation

**Comment by gabemontero** [comment]
[merge]

**Comment by gabemontero** [comment]
v0.1.18 has the sync plugin changes to replace this removal

**Pull request merged**
