### PR TITLE
Bug 1843941: bump jenkins to 2.222.1 and update plugins

### PR DESCRIPTION
**Pull request by jkhelil**

### CODE REVIEW

**Comment by jkhelil** [comment]
/retile Bug 1843941: bump jenkins to 2.222.1 and update plugins

**Comment by jkhelil** [comment]
/retitle Bug 1843941: bump jenkins to 2.222.1 and update plugins

**Comment by akram** [comment]
omg, 
still aws-flakes

/retest

**Comment by akram** [comment]
aws flake
```
level=error msg="Error: Error waiting for instance (i-0ab9d968571e16128) to become ready: Failed to reach target state. Reason: Client.UserInitiatedShutdown: Instance Terminated on Host Machine Without Notification"
level=error
level=error msg="  on ../tmp/openshift-install-334079763/bootstrap/main.tf line 116, in resource \"aws_instance\" \"bootstrap\":"
level=error msg=" 116: resource \"aws_instance\" \"bootstrap\" {"

```


/retest

**Comment by akram** [comment]
it was blocked by this: https://github.com/openshift/origin/pull/25171

**Comment by akram** [comment]
aws creds flake:
```
level=fatal msg="failed to fetch Cluster: failed to fetch dependency of \"Cluster\": failed to generate asset \"Platform Permissions Check\": validate AWS credentials: checking install permissions: error simulating policy: Throttling: Rate exceeded\n\tstatus code: 400, request id: 4246099a-6638-4745-a6ce-d4ff0f2470f3"
```

/retest

**Pull request merged**
