### PR TITLE
JKNS-384: Update Jenkins base images to RHEL9

### PR DESCRIPTION
**Pull request by avinal**
- update ubi7 to ubi9

Signed-off-by: Avinal Kumar <avinal@redhat.com>

### CODE REVIEW

**Comment by avinal** [comment]
I think the references to RHEL9 should be updated as well in this PR. Please let me know if that should be a different PR.

**Comment by adambkaplan** [comment]
We should aim to use RHEL 9/UBI9 in as many spots as possible. Note that there is a lot in this repo that appears to be way out of date, and isn't used either in OpenShift CI or our downstream build systems.

One thing I'd advise is to copy the `Dockerfile.rhel8` files to `Dockerfile.rhel9`, where you then update the base UBI images. That should help make the transition a bit smoother.

**Pull request merged**
