### PR TITLE
bump pipeline for swaggerapi url fix

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/origin/issues/15823
@openshift/devex

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
mirror flake https://github.com/openshift/jenkins/issues/348

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
flake https://github.com/openshift/jenkins/issues/348

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
flake https://github.com/openshift/jenkins/issues/348 again

i'll wait until later today, then try again

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
flake https://github.com/openshift/jenkins/issues/348 again

**Comment by gabemontero** [comment]
going to just try 

[merge]

the new plugin is there

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
@stevekuznetsov @dobbymoodge  - hey guys, jenkins repo / rosie builds have failing every time on yum repo / mirror issues for the last 2 days.

Is it possible some sort of set up change was made for the origin repo that needs to get made for this one?

**Comment by stevekuznetsov** [comment]
@gabemontero I'm not sure we run with onlineint on by default:

```
failure: repodata/repomd.xml from rhel-7-server-ose-onlineint-rpms: [Errno 256] No more mirrors to try.
```

@smunilla @jupierce @bparees would know better what is going on here

**Comment by gabemontero** [comment]
ah ... thanks for the highlighting @stevekuznetsov 

yeah, @bparees reminded me on the way to snack time that the onlineint stuff is used as part of the new method @jupierce put in for building the "super" RPM that contains all the plugins we install in the jenkins image.

Hence, this repo will always need onlineint as part of building the rhel image.  I certainly see refs to it in the xml files for this repo in aos-cd-jobs/sjb/generated.

@jupierce @smunilla @stevekuznetsov - how can we insure  / is it OK to insure that we run with onlineint on by default ?

**Comment by bparees** [comment]
[merge]

**Pull request merged**
