### PR TITLE
add ssh-agent plugin to base plugins

### PR DESCRIPTION
**Pull request by Gl4di4torRr**
Adding ssh-agent plugin. Refer to #613 for more details.

/assign @gabemontero @bparees making this change if you determine it satisfies the 80% criteria.

### CODE REVIEW

**Comment by Gl4di4torRr** [comment]
@gabemontero When I built the docker image locally, I had to delete my volume in order for the `ssh-agent` plugin to actually get the plugin installed. Is there some caching going on with this jenkins job?

**Comment by Gl4di4torRr** [comment]
@gabemontero reverted the test. I understand on the pending decision. I did this in case the decision is yes.

**Comment by gabemontero** [comment]
this time the red hat registry flaked ...

**Comment by gabemontero** [comment]
Hey @Gl4di4torRr - following up here.  After some internal polling, sorry, but I'm going to refrain from adding ssh-agent to the base jenkins image.  As discussed before, follow the intended pattern of building your own images off of the openshift/jenkins image, using one or our extension mechanisms, to add ssh-agent or other plugins that facilitate this scenario.

thanks

**Comment by Gl4di4torRr** [comment]
@gabemontero no worries. glad to help out where i can.

**Pull request closed without merging**
