### PR TITLE
Bug 2058794: Bump Jenkins LTS Version

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by coreydaley** [comment]
ART request: https://issues.redhat.com/browse/ART-3978

**Comment by gabemontero** [comment]
I *think* this is all that is not required for 4.x jenkins core bumps, but @akram is more familiar with the latest needs than I am ... ideally he plus one's that we are doing the correct things upstream (while the ART req @coreydaley opened handles downstream)

let's see if he is back this week from PTO and can chime in and lgtm

**Comment by gabemontero** [comment]
so yeah just heard in scrum @akram is still on PTO this week so I'll

/lgtm

and if something comes up during QE verifications we'll circle back with additional PRs

**Pull request merged**
