### PR TITLE
[head] Update and rename imagestreams files

### PR DESCRIPTION
**Pull request by yselkowitz**

### CODE REVIEW

**Comment by akram** [comment]
@yselkowitz , welcome to our great world of flakes:
```
level=error msg="Cluster operator kube-apiserver Degraded is True with NodeInstaller_InstallerPodFailed::StaticPods_Error: StaticPodsDegraded: pod/kube-apiserver-ip-10-0-151-199.us-east-2.compute.internal container \"kube-apiserver\" is not ready: CrashLoopBackOff: back-off 5m0s restarting failed container=kube-apiserver pod=kube-apiserver-ip-10-0-151-199.us-east-2.compute.internal_openshift-kube-apiserver(06cd7d5148adef33fbf2f700cbf3bd05)\nStaticPodsDegraded: pod/kube-apiserver-ip-10-0-151-199.us-east-2.compute.internal container \"kube-apiserver\" is waiting: CrashLoopBackOff: back-off 5m0s restarting failed container=kube-apiserver pod=kube-apiserver-ip-10-0-151-199.us-east-2.compute.internal_openshift-kube-apiserver(06cd7d5148adef33fbf2f700cbf3bd05)\nStaticPodsDegraded: pod/kube-apiserver-ip-10-0-151-199.us-east-2.compute.internal container \"kube-apiserver-check-endpoints\" is not ready: unknown reason\nStaticPodsDegraded: pod/kube-apiserver-ip-10-0-207-252.us-east-2.compute.internal container \"kube-apiserver\" is not ready: CrashLoopBackOff: back-off 5m0s restarting failed container=kube-apiserver pod=kube-apiserver-ip-10-0-207-252.us-east-2.compute.internal_openshift-kube-apiserver(2d58b2f4ddc2f5241a09588a856c59a2)\nStaticPodsDegraded: pod/kube-apiserver-ip-10-0-207-252.us-east-2.compute.internal container \"kube-apiserver\" is waiting: CrashLoopBackOff: back-off 5m0s restarting failed container=kube-apiserver pod=kube-apiserver-ip-10-0-207-252.us-east-2.compute.internal_openshift-kube-apiserver(2d58b2f4ddc2f5241a09588a856c59a2)\nStaticPodsDegraded: pod/kube-apiserver-ip-10-0-207-252.us-east-2.compute.internal container \"kube-apiserver-check-endpoints\" is not ready: CrashLoopBackOff: back-off 5m0s restarting failed container=kube-apiserver-check-endpoints pod=kube-apiserver-ip-10-0-207-252.us-east-2.compute.internal_openshift-kube-apiserver(2d58b2f4ddc2f5241a09588a856c59a2)\nStaticPodsDegraded: pod/kube-apiserver-ip-10-0-207-252.us-east-2.compute.internal container \"kube-apiserver-check-endpoints\" is waiting: CrashLoopBackOff: back-off 5m0s restarting failed container=kube-apiserver-check-endpoints pod=kube-apiserver-ip-10-0-207-252.us-east-2.compute.internal_openshift-kube-apiserver(2d58b2f4ddc2f5241a09588a856c59a2)\nNodeInstallerDegraded: 1 nodes are failing on revision 2:\nNodeInstallerDegraded: static pod of revision 2 has been installed, but is not ready while new revision 3 is pending"
```


/retest

**Comment by gabemontero** [comment]
LGTM

btw @akram @yselkowitz doing a quick scan of https://github.com/openshift/jenkins#installation-openshift-v4 I think Yaakov's corrections to the imagestream file image refs now match up with what was documented in the README :-)

at some point the image refs for the specific nodejs 8,10,12 images produced by CI, osbs/brew and sent to quay.io and registry.redhat.io  should be added to the README as well, with explanations of nodejs8's fate, how nodejs12 is the default in the imagestream, etc.

**Comment by akram** [comment]
@yselkowitz another flake
```
Aug 12 11:20:50.707: INFO: skipping dumping cluster info - cluster too large
1665
Aug 12 11:20:50.707: FAIL: Couldn't delete ns: "e2e-volume-3827": Delete https://api.ci-op-tl5mv8q0-93a8f.origin-ci-int-aws.dev.rhcloud.com:6443/api/v1/namespaces/e2e-volume-3827: dial tcp 18.214.107.10:6443: connect: connection refused (&url.Error{Op:"Delete", URL:"https://api.ci-op-tl5mv8q0-93a8f.origin-ci-int-aws.dev.rhcloud.com:6443/api/v1/namespaces/e2e-volume-3827", Err:(*net.OpError)(0xc0027ec8c0)})
1666

```
/retest

**Comment by akram** [comment]
/retitle [head] Update and rename imagestreams files

**Pull request merged**
